set(SDK_PATH "/Volumes/Resources/stash/matter/green/third_party/silabs/simplicity_sdk")
set(COPIED_SDK_PATH "simplicity_sdk_2024.6.0")

add_library(slc_generator OBJECT
    "${SDK_PATH}/../../../examples/platform/silabs/provision/AttestationKeyPSA.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionChannelRTT.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionEncoder.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionManager.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionProtocolV1.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionProtocolV2.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionStorage.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionStorageCustom.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionStorageDefault.cpp"
    "${SDK_PATH}/../../../src/crypto/CHIPCryptoPALPSA.cpp"
    "${SDK_PATH}/../../../src/lib/support/Base64.cpp"
    "${SDK_PATH}/../../../src/lib/support/BytesToHex.cpp"
    "${SDK_PATH}/../../../src/lib/support/logging/TextOnlyLogging.cpp"
    "${SDK_PATH}/../../../src/platform/silabs/Logging.cpp"
    "${SDK_PATH}/../../../src/platform/silabs/multi-ota/OtaTlvEncryptionKey.cpp"
    "${SDK_PATH}/../../../src/platform/silabs/SilabsConfig.cpp"
    "${SDK_PATH}/../../../src/setup_payload/Base38Encode.cpp"
    "${SDK_PATH}/platform/bootloader/app_properties/app_properties.c"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Source/os_systick.c"
    "${SDK_PATH}/platform/common/src/sl_assert.c"
    "${SDK_PATH}/platform/common/src/sl_core_cortexm.c"
    "${SDK_PATH}/platform/common/src/sl_syscalls.c"
    "${SDK_PATH}/platform/common/src/sli_cmsis_os2_ext_task_register.c"
    "${SDK_PATH}/platform/Device/SiliconLabs/EFR32MG26/Source/startup_efr32mg26.c"
    "${SDK_PATH}/platform/Device/SiliconLabs/EFR32MG26/Source/system_efr32mg26.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_default_common_linker.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_hal_flash.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_lock.c"
    "${SDK_PATH}/platform/emlib/src/em_cmu.c"
    "${SDK_PATH}/platform/emlib/src/em_core.c"
    "${SDK_PATH}/platform/emlib/src/em_emu.c"
    "${SDK_PATH}/platform/emlib/src/em_gpio.c"
    "${SDK_PATH}/platform/emlib/src/em_msc.c"
    "${SDK_PATH}/platform/emlib/src/em_se.c"
    "${SDK_PATH}/platform/emlib/src/em_system.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_attestation.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_cipher.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_entropy.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_hash.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_key_derivation.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_key_handling.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_signature.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_util.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sli_se_manager_mailbox.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/error.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/mbedtls_ecdsa_ecdh.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/mbedtls_sha.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/se_aes.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sl_entropy_hardware.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sl_mbedtls.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sl_psa_crypto.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sli_psa_crypto.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sl_psa_its_nvm3.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_psa_driver_common.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_psa_driver_init.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_psa_trng.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_aead.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_builtin_keys.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_cipher.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_key_derivation.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_key_management.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_mac.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_signature.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_opaque_driver_aead.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_opaque_driver_cipher.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_opaque_driver_mac.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_opaque_key_derivation.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_driver_aead.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_driver_cipher.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_driver_hash.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_driver_mac.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_key_derivation.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_version_dependencies.c"
    "${SDK_PATH}/platform/service/device_init/src/sl_device_init_dcdc_s2.c"
    "${SDK_PATH}/platform/service/device_init/src/sl_device_init_emu_s2.c"
    "${SDK_PATH}/platform/service/interrupt_manager/src/sl_interrupt_manager_cortexm.c"
    "${SDK_PATH}/platform/service/iostream/src/sl_iostream.c"
    "${SDK_PATH}/platform/service/iostream/src/sl_iostream_rtt.c"
    "${SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager.c"
    "${SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_cpp.cpp"
    "${SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_dynamic_reservation.c"
    "${SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_pool.c"
    "${SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_region.c"
    "${SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_retarget.c"
    "${SDK_PATH}/platform/service/memory_manager/src/sli_memory_manager_common.c"
    "${SDK_PATH}/platform/service/system/src/sl_system_init.c"
    "${SDK_PATH}/platform/service/system/src/sl_system_kernel.c"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Source/cmsis_os2.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/croutine.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/event_groups.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/list.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM33_NTZ/non_secure/port.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM33_NTZ/non_secure/portasm.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/MemMang/heap_3.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/queue.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/stream_buffer.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/tasks.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/timers.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/aes.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/asn1parse.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/asn1write.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/base64.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/bignum.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/bignum_core.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/bignum_mod.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/bignum_mod_raw.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/cipher.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/cipher_wrap.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/constant_time.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/ctr_drbg.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/ecdsa.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/ecp.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/ecp_curves.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/ecp_curves_new.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/entropy.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/entropy_poll.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/hmac_drbg.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/md.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/oid.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/pem.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/pk.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/pk_wrap.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/pkcs5.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/pkparse.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/pkwrite.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/platform.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/platform_util.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_aead.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_cipher.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_client.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_driver_wrappers_no_static.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_ecp.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_ffdh.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_hash.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_mac.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_pake.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_rsa.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_se.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_slot_management.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_storage.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_util.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/sha1.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/sha256.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/sha512.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/threading.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/x509.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/x509_create.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/x509_crl.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/x509_crt.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/x509_csr.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/x509write.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/x509write_crt.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/x509write_csr.c"
    "${SDK_PATH}/util/third_party/segger/systemview/SEGGER/SEGGER_RTT.c"
    "../../../generator/app.cpp"
    "../../../generator/efr32.cpp"
    "../../../generator/main.cpp"
    "../autogen/sl_device_init_clocks.c"
    "../autogen/sl_event_handler.c"
    "../autogen/sl_iostream_handles.c"
)

target_include_directories(slc_generator PUBLIC
   "../config"
   "../autogen"
   "../../../generator"
    "${SDK_PATH}/../../../examples"
    "${SDK_PATH}/../../../examples/platform/silabs"
    "${SDK_PATH}/../../../src"
    "${SDK_PATH}/../../../src/include"
    "${SDK_PATH}/../../../zzz_generated/app-common"
    "${SDK_PATH}/../../nlassert/repo/include"
    "${SDK_PATH}/../../nlio/repo/include"
    "${SDK_PATH}/platform/bootloader"
    "${SDK_PATH}/protocol/bluetooth/config"
    "${SDK_PATH}/platform/Device/SiliconLabs/EFR32MG26/Include"
    "${SDK_PATH}/platform/common/inc"
    "${SDK_PATH}/platform/CMSIS/Core/Include"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Include"
    "${SDK_PATH}/platform/service/device_init/inc"
    "${SDK_PATH}/platform/emdrv/common/inc"
    "${SDK_PATH}/platform/emlib/inc"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Include"
    "${SDK_PATH}/util/third_party/freertos/kernel/include"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM33_NTZ/non_secure"
    "${SDK_PATH}/platform/service/interrupt_manager/inc"
    "${SDK_PATH}/platform/service/interrupt_manager/inc/arm"
    "${SDK_PATH}/platform/service/iostream/inc"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/config"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/config/preset"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/inc"
    "${SDK_PATH}/util/third_party/mbedtls/include"
    "${SDK_PATH}/util/third_party/mbedtls/library"
    "${SDK_PATH}/platform/service/memory_manager/inc"
    "${SDK_PATH}/platform/service/memory_manager/src"
    "${SDK_PATH}/platform/emdrv/nvm3/inc"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/inc"
    "${SDK_PATH}/platform/security/sl_component/se_manager/inc"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src"
    "${SDK_PATH}/util/third_party/segger/systemview/SEGGER"
    "${SDK_PATH}/platform/common/toolchain/inc"
    "${SDK_PATH}/platform/service/system/inc"
)

target_compile_definitions(slc_generator PUBLIC
    CHIP_CONFIG_SHA256_CONTEXT_SIZE=256
    CHIP_CRYPTO_PLATFORM=1
    CHIP_LOG_FILTERING=1
    CHIP_PLATFORM_CONFIG_INCLUDE=<platform/silabs/CHIPPlatformConfig.h>
    CHIP_SYSTEM_CONFIG_USE_SOCKETS=1
    OTA_ENCRYPTION_ENABLE=1
    SILABS_PROVISION_PROTOCOL_V1=0
    SL_PROVISION_CHANNEL_ENABLED=1
    SL_PROVISION_GENERATOR=1
    EFR32MG26B410F3200IM48=1
    SL_APP_PROPERTIES=1
    configNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2
    SL_COMPONENT_CATALOG_PRESENT=1
    CMSIS_NVIC_VIRTUAL=1
    CMSIS_NVIC_VIRTUAL_HEADER_FILE="cmsis_nvic_virtual.h"
    MBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>
    SL_MEMORY_POOL_LIGHT=1
    MBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>
    RTT_USE_ASM=0
    SEGGER_RTT_SECTION="SEGGER_RTT"
    SL_CODE_COMPONENT_CORE=core
)

target_link_libraries(slc_generator PUBLIC
    "-Wl,--start-group"
    "stdc++"
    "gcc"
    "c"
    "m"
    "nosys"
   "${SDK_PATH}/platform/emdrv/nvm3/lib/libnvm3_CM33_gcc.a"
    "-Wl,--end-group"
)
target_compile_options(slc_generator PUBLIC
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:C>:-mthumb>
    $<$<COMPILE_LANGUAGE:C>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:C>:-mfloat-abi=hard>
    $<$<COMPILE_LANGUAGE:C>:-Wall>
    $<$<COMPILE_LANGUAGE:C>:-Wextra>
    $<$<COMPILE_LANGUAGE:C>:-Os>
    $<$<COMPILE_LANGUAGE:C>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:C>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:C>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:C>:-imacros sl_gcc_preinclude.h>
    $<$<COMPILE_LANGUAGE:C>:-Wno-unused-parameter>
    $<$<COMPILE_LANGUAGE:C>:-mcmse>
    $<$<COMPILE_LANGUAGE:C>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:C>:-g>
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:CXX>:-mthumb>
    $<$<COMPILE_LANGUAGE:CXX>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:CXX>:-mfloat-abi=hard>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-exceptions>
    $<$<COMPILE_LANGUAGE:CXX>:-Wall>
    $<$<COMPILE_LANGUAGE:CXX>:-Wextra>
    $<$<COMPILE_LANGUAGE:CXX>:-Os>
    $<$<COMPILE_LANGUAGE:CXX>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:CXX>:-imacros sl_gcc_preinclude.h>
    $<$<COMPILE_LANGUAGE:CXX>:-Wno-unused-parameter>
    $<$<COMPILE_LANGUAGE:CXX>:-mcmse>
    $<$<COMPILE_LANGUAGE:CXX>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:CXX>:-g>
    $<$<COMPILE_LANGUAGE:ASM>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:ASM>:-mthumb>
    $<$<COMPILE_LANGUAGE:ASM>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:ASM>:-mfloat-abi=hard>
    $<$<COMPILE_LANGUAGE:ASM>:-imacros sl_gcc_preinclude.h>
    $<$<COMPILE_LANGUAGE:ASM>:-x assembler-with-cpp>
)
set_property(TARGET slc_generator PROPERTY C_STANDARD 17)
set_property(TARGET slc_generator PROPERTY CXX_STANDARD 17)
set_property(TARGET slc_generator PROPERTY CXX_EXTENSIONS OFF)

target_link_options(slc_generator INTERFACE
    -mcpu=cortex-m33
    -mthumb
    -mfpu=fpv5-sp-d16
    -mfloat-abi=hard
    -T${CMAKE_CURRENT_LIST_DIR}/../autogen/linkerfile.ld
    --specs=nano.specs
    -Xlinker -Map=$<TARGET_FILE_DIR:generator>/generator.map
    -Wl,--wrap=_free_r -Wl,--wrap=_malloc_r -Wl,--wrap=_calloc_r -Wl,--wrap=_realloc_r
    -Wl,--gc-sections
    -Wl,--no-warn-rwx-segments
)

# BEGIN_SIMPLICITY_STUDIO_METADATA=eJztnQtz3LiV77+KS7V1a/fGakotyzPjnUnKI8sebSzLpdbMbhKlWGgS3c0RX+FDj0nNd78ACZLgEwABkEzdTU1sdzf5P78DAiCeB/88+np781+XF3fm7c3N3dG7o3/eH91efn5/d/XLpUn/dH/07v5otbo/+v3odXnP5ubn24vLDbrt+z89e+6rRxjFTuD/cH90ujq5P3oFfSuwHX+Pvvj57uPxt/dHf/rjvf99GAW/Qit5hW7x43deYEMXXXFIkvCdYTw9Pa1ixwXbeGUFnhHHxiZJbSdYQSuIIBJFd4cwSl42Fvob3UfU7o+Q9KtX3+8C14bRKx94+Ecr8HfOnvyGf3VcWPwWu6YHvSB6MfOrVgeknkYO+glf9s74JXBTD8bGLYyDNLLQv+IExAfDA0kCI2MfQegbyPyjg7024jQMgygx4C46W3v79Vsj1zW6DBldRJvLT58ub83buzvzAl2pDajDTieP/+idmTbcgdRNdCdSj61OrjAGphW9hEmgm6rTUicTesg2fHQsaDq+k5i2ZVsT5KsBk32UJCt6wAd7GE2X99sGOwk/IuXbu5vNhV6utpm+9HJ8JBylYVJ6EK8nSDWG2T5aXElOQNcww5nXIrhHwtNnuZbdTl4QhiZ5uTgw1k3Za42ndoFeOnHlUrfYyQg919nmOcOG23Svm3DAXm9+3EI7cbU/205LLCaS2tOhtQzmhN8beROqqzkF0iTYQ7+3PYUytetYIMGlLXkJoXo3CIHRY6wzkW/vLlE7xwsDH/pJrI+pbae/liZXmYgfuIGG500lVKc1nmrGcgPrAbXDNbJ1m+uDg4/YiwPwbRdGWtOsZYkPSWdStSz1tliCOIkg8Mi1GnN8jzFuMJ3J1WWMCZblQ8dHVn1rqoRr2+zBdBpvFZOo6cQcssmLmUTAj3dB5M0C3Gm9Fz3r8E2Yut32BvG2qeMmjj85Zr/dTlzX8R9ghL9ZubYutoaRTpCVFZX9YvRPXSgtM+zmVOx4uAnjJC9mbD+Y65P1m9VbPHJWulG7PHRBgjNy+Xvrig/Z25T6vXXFxkEGA/8z2Ma1y1oXXn68PVtff1q/bVzWVsySrXVVM/MmIErS0CzTbVzdnxycyDZDpPVi5KOERj0RjSKRjDwtDMpho/TJyKGNTiqD4clLnEBvaY50QDX9qOXE3sd55VtuajOfZ2lp++b0ZHe2PjlxvDffjquEVKUFQTf62RiPtrzRBJYXLsyZkonfibEtGI0+1Bs4bBe89Nla3pMoqbgd2aYR8JbmRwkl4kZiLdCNHIrbDctLl+YEQeJ2AY/2L82HgonfCaTv74LF+VFh8bviAXRfbEVOmAQjxyY0etSi43csdN3FuUOYuJ2AyyvwULDAwzRGFIvzoqTidmQXR9biinwJxe3GPkS9vKW5UUIJuOEs7mEUTEJOmLhfvkRPSjBudw67BZaQEkrAjecFevEs5oSzXlwhJ0j8LoDlNRULJn4nLGAdRk4oanSjpOJ25AG+xBYYOV6rzxMKi9sV17KX5gZBEnEhGrnQTqsT0U7MDdTAX5wXhEnIiectWFznieYSdgavaXT85Y3EdfHxOwcTxxs7A6/RpwqL35UltrVc4baWu8C2liva1vKA426D56X5QWHxuxKCw3aBQ740F78z8eLajwSJ34XHxc0iECRuF0LLX1z/tmDidyJa3JuQIIm4YMbO3gfuEl2h0bhdiuFCq94aGL87yxvtjQVHe2PUG9uNXBaq0YuSSsSRBU4ZVlTcjiyyxSve3k0X2eBNxVu8i5wOEZ8NebTB4kpHwcTtxJM9dgm7PicKJpYTHlmDvhB+Gkd0JdoiPOii4lqK1vFl66v2F839vp4X+EMLIB3fai18rC8G3zr6q5Wc00AwRmXRGMSyvNiJzSDbBYhvnpixy/wgsEPdAp8TE7E8ZDvxUPbQ/x6twTNRGCkf2NC0XBDHzo5sOJo68bsJWOk/N3cvwnB6Qz/VP25ST+DC5DAYcgNO0Oaoo1VGWbl0jlqBry7IdmlOjhZ1vESbYMhikurvx9fRKqPG0MuuvV8gYry7his63QvViZOIklnntpan9xS1SZEpo+zcjP9I4LM3MWLTNCN34zld1x250W40JG1WLIcnQeBaB+D4w5tT2o243tgD+d7/qQp4yV8U9RZFqynciT0zLw/o3rLMMIJO3uyfDbiNYSjvVWyDIHEDgL4Z6lnUIzoMVdT1K7UXzgq/EXXCaIMMFldWOl1cb642Q0l0kYVwGirZfduPaumXv1nwtnZn9D5wgfTL3DIwe9nJbRMMFpf8chIeaz5eCmAQN/kNb2RErxj9bd0O1rp1jnRFVcB8aUqMD2NmL23v7GwWTNr4IKYXpiaIvEf92/g6MGvGxavwVkWCgzutldU1qBU7UaJk3I08RqwPPrwgNhPHepiFkrLNfHK8+4ebzuFhRWxD98uS9o9srq1bV9+8QJ0O1rZtKkyKfMu4I+aK7lxDXDQo00UDrpuG1fpsBr5bigd9W+AY0byWgt+5KYmnFLeHJtjPzETVmu7i3OU36aX24Ag+uQU5UdEoeH+24g8O1zscz99pxzScLNu3LJejVJ1MrDzQDs441WgQy6FhNPFy3f0+qfd7axFJOpMsb8b4iNx8dKIkBfp3lPYnFK72AB5R6ITijprByBEzO9iHpKJmIIGrpCuEMgTWdKWGGCwLCwXALPNFvK4o0T8uzQIuIFQV6J7nMlkeLtwssi4FIPRc5gYuIBQUs3oMW/nCVtebLAfXzRb5uA3DNy5evtTsF/QTqrkjiA3lE8tLcqkPkOGm046WnU2wzuraAJTgU4tgAqI9nK7+5HpUNJXg85mswuF6MPzzS9WjDMMV+v+SHkeJJOhKGATusjJWQSRcSvaLq84qJj1NjmUUq/qk7fhSNdGks4gXvVPQoxon+SJP+UYJWSyKhy8my++5TWqtAk3AetDk8gcY+XC62qYTuWLQUyTplJkqJxNHi3VSdQKxZzMrcsWgfroAenb0ODRZ0LEIWjwDQLx0U3siZr7Qq+NKswoqKXykkGQq0KcSTZQY2GSWFE3bg9kfXzwHIBeYuYc+jBz9kzRdKUjZZoMeJhiZ7II89Aw+dgGaOxeZnwuzss6GxbN5s3AWhjXMYzXOKcMVl5lHIdfeGqA8xS2BYRKRrDQHeM06Z1aag7MwLJ6VXGc7nJXQBZmJi+uzs2wdEZjOP2Tb6LKvo7nSTAixHVmoNWUdHP3RGzLOvA1SWRxYXo2vmmDivo7VOT3fpspWJoIpWix1OMouY2/S5KlXNzqcghPt86mlHtc2H3TddoLdKjWwbXunSkeem2bzUT2/8ew9QtdFwNul/hSNTwqOMjpMN9Wi4Bpd70Lg9nOdYN9W46kyt22RqybsVTT4+vsUTc4plnbV8LoXcDWoJon5W8Pqjujb5JoizlQNqzOKVAfVLO/Tut1hxnjiUhpzlNGJQtjUuXoC1HSwJVD/+oYmG7HJwzZP7da2rXSHKmmA6e/HYZdwF64yyPGemxaLWGS/PybFgjypldXmk2IVFtnvj0mxiEFm3TwpVMyRr0hdNC1XaVNqk2EMLYScvAwNKdCH3jImKavzkMnRfqzlrvkRf8zz7qiDKIFlQRdG0wTgKJKndvCv0XazOhC6H5QVf4i6NfB8J8RrnSaIUSnjYoOTw0N89OXin2AXJPdKZuYAeHuqFRFFQfhiHkBkP4EJ3p3ciULmyLsAWZHAoiiYYl2kgCMlEjOfFrcvi7/OxXICZscDLsuBkokBX9wMLRsVRfSn/lkVIUe6+Tidig9gmd4QMHbpyI5Zjl7CRH+7VbSA1NE4X0jL9KXJNu4N1LUoo7++W8zbuFh1V3ExniWqWEwwwbISIQ8oKAa+ZXnLw6egWPgesBbIT1GxX5f50k5vUW3urBg00ViuHMDp8p4FTcV2YH3+dpEuUFxsJ85P14t0guJiOLFfYq20566VoPVrCB7g8lxogDHcSA4RBLbj75fnSAtNqPG4KFdaaGKNx4X50mTjey6PwE0nOFxrzHOp0MaGv+4arcTKduQ8traEjhvJyVM9ifz9fJ2JyqVaP6KA4szVucJUW0nEXGmwiXk02RbQUT717wXt8Ao1DMnSE9OGIfRt6FtTREAU8W2Akc9DkjDb1HETx88O1lyagz2IQv6hm+hW/jI9bEMK+4hqVGeyDeZjfaxDCvkIUHNooZ4VaEL+oB70Qt0hZELeZKd5JemcMyyDPtX4hDyznPAwSRyKMW5VcHw+JRHwY8SDtJft3yDoaF8PU+wikfe0wBzt5xLrygHM0X4usA7tpxT3ctmv9WFSPm+DEPwjXfIrsRNQyLdlP8ReyDHPb5mvkj7GMR4usWLtJuQblnISHFnQO1uQTy0utbOztYuQqY6LGkmVxSf0gYsqvDROoG3GSRChntp8g3lUmuFxPPTRGIJsZ4WOrP4v4SULlOlpvlBpSS6VRB0Ftjujc43CLcXFXjqxscUdzDpvMw6gD/tF80mMLy7JuwFG8XGbhTnWQBszHrBMjyo4mfHDZfrWhpQZB16uj2JLUlojd8t0zOM6qbneosUbk/GjXly92MUn5FnyEi6vtm+yiY9XLPaB9UKK+7jIR9cJqG42v1gmp2Yq36z05up2wmYU0ToSu+9cXW+miTNFgEVRP0ouIWfmHcEZckdg3Ia+jeyvWaJHFJqQS3NOYgz5wz1rQd+0jNHRIbdGDI02bz8A33ad+ZYusdyj+YScm33Wd8gzsSlf+k7MiHCXmiMbeHxtmOJmDzjuNnheil99bGJOBfEkJ/WIe1SAibtDjiWPkimOdBzrWhNS50Yqqok2e3IUQZRrSEJVjA13jj9fR2LAFRpNyKVZe0ZDDvH3aFvt5wV6U3CJVSlzD6A3PeqFE3pG5VxQtjJ0Ia4NAoo9teL2pbjWCyfWyTxA68HMo0IsxbMhPjHnluvWSIdmne8YdIh/sqOr371Ajyg08SGBBfpTcMkMCSzQrREzUb1d7oW6R/ONHBJYoGc1uNFDAgt0rIE3bkhgIX71sY2dz2BFbmt+rHdOcXOb6p02fqW8H4rztkNJhTvJwzHess40a4plkz0KvoOMA31nfuNkqV1WuJgfV2zkmEaNY9zowJVvuanN9Liwb2ocL2E5TVCNJgujOJaXe9lBfEuBL2mUTSTmp02xcjjenwy2bvcTr1356eKiZ/lm7bL3t9f52RFf7v7aeX3rDj/wzay26oLoeIIYefqSlienUaSXgZLDoH01KjeMgrBrhWSnOyDWFnZTnUcEktspD1iRtoAC6twqMYWe1uLdIpDdTvUudh1aB9u/QLZWnK+hdw38rliojaQ8QBCa2hbD86ckATYqHu7VwdxD7jwvVZAEnr7Q3sz0IJRGhcEKlhUFSNTX1vfgJqZBGMw2DCNoAbySPRt5d7SuoOL2oB+LFRroEa9C2qMECOf3ognDYP+IZG7vbjazc9MgDGbXibWtZuXmLSBYgTphHKNunblNdzt9Y4rc1G0cFn+YmmEUJIHWuS5+/hYOB/9TBMIQRsugp2EY7MXLcXZuGoTFHAW/otpz/rSmQRjM/0hhOn8ilxTM6JJeeJi/JqkwWLwJsB7MrIE/f65owjDYN/jy62WgN1iYqR5B4C3ltdOiYUUpBLG242m5oQsIFqvjLeHdUmFwDzp2dSPm6gjSAC0Hehvbc9E2IQaJs5biXKSF8UHC/NUzF2JpfZCxXoXMxdqiGGTGNch8mbS0PsyY1xuzQZbmG8ciccxqtcZ4SMjP4Tkn19lGIHoZPgBa43EXrSQh1AYBM3qOtajzxf4pulvfAVZsSpqAyfoUOcm8rCXBIOsWxPDtm9lAK/ODlHr3LDEp+zcmdVBmHd6ZUUuG4ZaFNR8nsc3iM600epyxaqojcNKaPnxaAHGBMUjtaYt1xCT1OoMY1WsnZ++n001Stmqn0jwHpdaDOzlRe47y7Ob1gvmefR2Bk9aMwHzlqo0xSB048yUusT3IF+o7cpPJF7aP3mzzPVjx+XyEhXVGjW/H2k4j46joiXVGOs6YiBx087bpKfsMznnb85R9Bue8rU/K/nDJ0btln112+vfld3GaYeBqCwDBC1tCDPdBksi0o622fejsDggFMEh6wOeLzYpaIxgeizuA09kwC+MswvX52zkZiXkW5fnpdAuWOyiJ+eEyFPjIPo6z43jz1fktiuFRzeIsqdl4awTDbymyW2C+1xQFwEWqNQIQN25vvJ86cwxmxqUAhsdJXdSn0hmpjz1OShMM90J900unW7jf6n2W5jlGc7XvKeYc1h3cPtw7gjIbc52BdwRlZlyCIDKCMj9xgSFAjfLSI4idx9nzRxcP96zAXOwNBkbrR2d0aY5mT1/46P42moltzEjchSJCP3d13Y/DnPEoo19oPF2Va86jCcJBPnOF0oTgH4mYjbgBMbwKyAuS6VaJNVFL64zZLxxtdTbIyjyLcta3B2V/mDOMNZ9NwEatITBptZ4VwQXbezZEixX3ridc2doFWyEwaZMIWPNVrTWC4d4ysN3Amm7tbauzXNlnjezP3kxoMHDNRMzIylVnFTMr83GW9rlGdRaQC7pIBtkjdAdqlZkH6E66K6lJ3sExPFodu6YNt+l+dvJOEia75TpzDq7VEZi0nhNPtw25i7UAYJKiG0/P5u8/dKNw0uuMpihA3hczsUb9fH7y3Wyj2YVxJqFpoebRjGsEGgw8vPPNEdAAPKTT7SfpIWXvKckvjOdbpUwDMEnnXc9SI+BjnT0T1Ch4mWfODjUKZvvSil7CJCje2XNOH7ZIONkXAC2S0jqPmhVJ574DZXtzyLzbMTpJeNnJYWVFVALTD8wsqqK2Y6lF3BmE4/UwdoOEPmFuAX51IHF7Q45+XYIXFQov/ZxbbNoYvNS7na3t+CER7IKDl1vnsUki3H3HJPVxkzPn58YmGLzUIXhYRLEsOHi5oxkX7bcxuOvBRaQ1x1p5ElqfvJ+1hspnT2x3swi1z+YcZ21wCLbPFkDeH7+/l33ONWAdHCLcc89+9uOMbB0vwZMOJPm2/vL8qsOJtC8X4AvBEGpfLgC74BBqXy6Au+/MjT7u2acqeli4+WdcSNTGEGnVL4C651j2wVb9ArALDu5WPfDtwJt3JWg/jkjfZAn0HKvS6r2CBUDHQvmlOSS1BAfaSKKjZEvwokJhRrhqxarqC1rOFfeqlUBgwgC+RYqUoW/JZ8AVtRdEzvQFv4VKIFissX86PyuB4GCdZ4FXF3DvUq/uoFxzI1cYLN48Ts7svCUGizd1XBu1RHfTHRTSy1xDYXBb6C/XXUBNQYOwmK35MwZhYJEeAPpvfTI/LgXCxRwGrrazLgWpCxQmt/7zYQXIhQ6DnWl0tUXNezSqNUdHtEXb0w1tbz4MQXK8Xmk7qpCfuIbC5MaZxwT2r2mcmC7cA+ulWBAyvyODbGM820WobzvHziku32g6Ie9wLya7ORdamHcddMLexSkea4bJcj3sIBTyMo6nH/8Z9ooQCXmRrTpelhsFEp8fC6ocuGsCKtzOAtDrNCz6IurW7OAUCIM529AyO3BJwaSdfyzJ5hpLsg/z97gIA4MUWjPMAzZRCwg26wKqtJKCSfvrLBM5bd5f+yZy2iEZFkDbOY3dE7xydtqKg0U8yzb3Fm/fVvcG7X4BI0Z7rhGjw4O9mx21gGCxlsEuZwemSRjUrjf/W5cwMEjJ1UsZ02rjsPinX+nYYu5c5NjiPF8A6DkPKfSC6IUcnWQC1w3mH4brYWJ44qPueBxYD3CGdThNDxosLHIH9Vwfpo9516KuOBjEOHj/3LSEgUGKw/jPTUoYWKTTx3dpgfKcrIiPHThdL4C1wODgnb82Lik4aL9ZBO03PLRFjOLZgSkQTuZljKG1aHjps+DFi6EvaFj0gftyenaygOJIgbCYI+cRJNAEFsKav2nRxmHxF5GuZyenQBjMkYPemfbp2/mXOdRIWNQLGHvrWRTbDLGDT2uYG7WAYLPiUxsWQEsw2LxnS6A942M9X0BbrsJg8S5g3pRvpjSLKwasw/wtjBoJD3W2ZCdOnWQBk0ldQDw+BMGDs5CkL1E4uBMHjxksgrtCYXBXR6rMjV0jYVE73iKQSwwG7yMqAc4Mu3abwBQHg3gRq0M414OUkd6WwFuA8DHPX1vQIFzM8fzTfDRIa/tS1xag1u4e1Jth7eyZeWklIjT4V1CSIA75MiqQ4v3SPti6cL6B3oq/D0vIJ7LQ6gG+IHtOZCYv4YwNnLZzvXxjvIxf/MB/mXFestc/mmz5O2CwG2K7X3Kf8T2J4+PgFmEQz9qUpp5EN5WYR2GEmiyJ87gsj+pUYh7hEocqdjysNmcLq8OrNhmfZ/mugCV4UpHwks+6MKFGzrvTphYpZabgOh0OtIAE/fAT+JzEC6vBhunGebi88s8mHOfpsuruYTo+D9GN0XyD7pQzJQgf98w7Wyhw/h0sJOTJ3FO+FLvArG8ZfoNkuyXg12A4+Z3fllF4SxBO7iRKrUW0SCoSPvLFdBMF+4OPwE2XAV6RcI20dHzZ9VV9NCaG+z2MGgMyzWte4gR6jw58YkVu2Vx++nR5yxreya8yb+/uJgt6mrtpVJ4YOYRRZ2HkkPziybIGA5ojS1PeLQS6YGHN6bhmlCTFSlbHt+F0W8Z7PeiBUlY4G1/UPtY/0EkFwpFba8IoeHTwnISxhz6MQBJEBhEzus1YYajSUCbXYcoDjq/SVqXXYQzuorO1SmuUYIe59+juLBBo4P8ZjmzHwmeAcjCsVpEVObvCaZthsnzdvB+bDMJApa0Oqq/FPRcH4Ptw5NQSB1KXIQ6e7FWhLZ16rQ2RXfpWMPr0UBEoyhAPzwTJVDM1xHSdRd6bII0oQzw8E6RRzdQQE/pHEljBBEWOtsRD9MvpFAnVtMZFNvrlMYqs/81SXruRiRYpArVpxoIc5PmE35Bjg3OPwKLs8aTWBA+xZoqD6SKNk8CbkIw2yMH3Ae5A6iYTAtYsdhD+KBFaMY4sHPDUiNMwDKLE+LERH7HL0EjPe0z1evWC2k53wU9j+0AtczW9YYOqPGwodhi9+Onq6+dgvx+9uqxp083FjIZwh+k7+Jzc+O5LcZUipwuATvkOjE2W/S8kZvIwQbM0NVVZhiWcHzTd57WCRG/aZSU0zhEX2Rjb1/efJfo92HY+Vmd0S/bUHGff5s3W8Q85hkkamiF4cQNgG01NllkJdwcM93l8k4A79xFdhJNHpt/b9ag99DpwjoMEGD1mOIEU5r5hpL5Uur18/+H6cuXZqsYhKEFiLp+ZT6OsF17YJa9UZBXBQ7f2zTYAkX2RrURwto7rJC/oZ/Q9Hidrfp0Ne3j79dvtm9OT3dn65MTx3nyLLk6CwLUOwPE7hGL7ofmthRogeUKu0K8r5KyF/nTQv9+tT9ZvVm9XJyvz7bdvvjk//Wb9phxq/t5DWdB9Z8PYipwssf/4vdH+Lh9KqyUE+u57nIC/QitB/z56fbS5uv76+eri6u4v5ubu5w9XN+b1zYefP19ujt4d/e2f+fKqxPEvn7MR+/j+6N3f/v76/iiCXvAIUXK/2wE3hq/LCzf5g8PXFRHUjI/oud3e3Wyqevl1+Vs1Umrin+s/ghAVvygIYZQ4kI4AUV0CPfQWys8Iyo+V77rIf/TO0M/Zo+68oHbcUPvnbIV+dgpR5282fHQsaDq+k5i2ZVs810Ev7bvM8VFmj9KwiKAfmfG679p2cIzOn4nlvqvyUArDvxYsfFdFcI+yG3UxzjQoi6YuRFnj/uh7kgnfXV9nX7569lw/fke+/eH+/v7okCThO8N4enoqyggqLkYc44YyvmgF8TPBV74ieS+7LYnS/EvHzj6n1iq3u8qq81VqkWxY1h6rvWVld4S2V5P4431WhLLZKlzhxKgywBVRbmj1f/GfBr6oLFOFO3/MUodgIYex4u+vZYsTXtmKqI3bu0sTVyWBD/08dsTr6kfX8R9ghOvTlWvXfkFPCRUo17GyqiCbKmzcm+VzomuiywBq1bUvobOx5QbWQ4ynk+rXwEcscQC+7eaH2g793LLgBHESQeCRKzr0W1f0a2ScThaE0Oq40GmUIZP8xL4wiYAfZxub+2/BFUu1oJKhn9VCrYsWVHLuoIcbAPBfsOy0Jwle904KvO5qQja/PJRfFb3Z13Sf/HW7Z/m62bt93dc6f93qIb5u9B1eD7Tsen7LVbomAjq+LofiX/cNdXf90NCqjcV2/dC4nh4o7fq+GKrs/G3d/q02BtX1w6Hza3pkqOPn2rhMx+/UWNzrWlP3dVfns/llfldnL/o1NTH5upwLfV2b1ntNzyiiD/X5X7NoVVbt+IvrzdXGuED1gXFFVmVYHmqCZi8Cp6qdxwuhGkJag9pQNlYna795Z2cSGl6YmiDyHr+V0Eh+K9Yyiong9vO6kSpBvJYRCeJs/+YYibxqxQp45QAWsfhEPmRtBzxY4qBk+Iy7kJcfb8/W15/Wb0uwsntlAssLeflEpcu2gHJlL322dGFvUU/O06edcJdVQW3LSzUp4x6XLml0OdnRo0PdA2bRXw+461lRI6HrapKG2h4pTGMQcVeQguK7OLJ0PdJ9aEW6MuM+dPRhO4GJh/E16R92+pL8sHvWJe2sdT1LB2irs5wyjIcG8Qf4EluAux0mqO5atj7laKdLG9XjGqWft0DXu6GQx0Ojjq+tPeRCHLZOmxMa6xZXX92CemnuNnjWpR6Cw1ZfQ9GLddVe3qOuhnNo+bpeb2Gkq+ggZTN29j5wdVmIod6cGGtrJKKep7Xb6xPX1xfSWR2mOutDnc3yRxvoSu8nO9CUT2rzv2pNeGSeRalqvs/DLPmViJPBoDhBmSMNKXEVY0KFeBOcU3sbBAlevQGjxmRy4yOvXr5RHm9gy6bT4hjyF4j6vVtn5I3l2B+1a3+ESmBD03KRB86OzAiOFZKBiLjzd/1OSI5HFr8Tz/ek3G/T2r0OlfbwOTETED9kM90ob3LX501F6eeQrVQq86JYPib3ksUNUQKfvXEK+GUMXFe0HOV3D6ermGK5Aqd43nvLQuUcki2ngmnbUsuXOahRIYskeMWgZ0ePdPaB1Dwk5914IUx2L/6HxK3FYhoZiX1tnmyUxAFwj2323G7uUNE7yIjgBRAj7sdrZ9H/M4mL67OzbJoMCMvgAtRY3YTzh5mvAuEtO12CVeJIiGSJw30/TpMsY3uCb9barVv+2r12n3VwuPue9Rv5uzjN+6jQR+K3C714G7fyv3dbN4oXXEpAYM6gdp/I4HftRoGhiuZ9Mg8nAt4u9ceZjsc9G7H+cPPWBHK3pzpulcoTgpP71b245TCm/OHqidwnVDcV9+HSM+ZGONJglvnH3Igz/5j74nH+kWzEeWsMrTRycAwCatUh+rZYQ1o22MtveJ+yuLIJqpVgGq1YB2g91FfQajGTxULXaUC3B4ITEiMsUEeOarJwEGhYjpDPVon7qJGG5+Q02mmHldNoKFvNWy151GEmG05PUv4G0AgbZRQmTfrFATkK5R1afwezFFLtgtOVf3XaEJzaYJooBjuqN5Kqd11LufZG0meFvCr0GSjqWX0WDgJ91BHyjfpPr6Gy/tNnpqr/9NnI6ie18p3lWqOJIFZYNfXok2HPKBFYyNtjq9rqVWzILrdmVftW8GlwLoxUvMi57AWe74ToNQL5Z97HmMPbZrS6ht8sAKL04x/wFNK2LE+fNj6iXJc4tH4NwQPUpr/XmDBlWfR0ZM/MwgGc6sPPTprTKX9+utYnX36tS77a0avTQhW1VIMFR7cT5VFYWp5zNigURYFs67JbufgOWjZKJPSnbBtw2AwqD1r0US0E+FcfiEm7ReMbNSsj+wlIN/l67RRlWZM8VQz0WHBUmsBSecTurJDhGMd5MZAtYB3C5SBQEqVxAm0zru1sVGoLJ9NU9opH0jqeQqMRRYMenWbKIO6otAPuRe7jLCgZ/WXYUDooyGFLYUtt0JbHvwZR0EAQgn+k0MSTgjjJdOUyYkbFAGSfiSzsQYjeJn6i3R3alk6fyBQkytMh9G3oW45aU9SLzEliM1t9o/A9Q7/F6lWmXiM4tIYuE0kkPQzWqd2oirVaoI7okm8cDVpSMo7LsKF0JJTDFlXpa7WFK32tBlQNufaZIZW+/mxdN6Q1z9VN6XtExM4keZt+m+l/WB3WtD6xDnsKpmYErOnLJLSxSXJKZ3uE21SU7aegwnQVQ1Ydkbu4GzlcoiKxGDglBVYMdimSllcrRF+8lknPDlUc0E9ctBXrL59sQFfkc0M+usp8dKIkFZmOGtKOOwIMyiuTBGmHLhTcVcCy4CiAJ4HhytQgn1Xp4HNzRmsV6VgwiSZbj07GJKhVj+jY2LowMu15NAW3RfRIFyOTdVy5JOjUNC0qJpdaZfvFBx4q/3gKNRJ93wjYCYNAYLpeQJg8ST3SCYj2UDZXF7WK0mzdLSrcJc+180W15SKwfLl11vEWhOwUeoBRFQRQVKra+1UyjXOuLkSYhqVaJ5ntIgjxSor8xVnueC2+Nr0slw87KizKXrjBkiT7W6uAbmPdzlPNsKIAXeOzuppMnTxC6x6phayWJ1OL7L0r40CPTrKG3gbHy74GyGVWO5ZbEiSBx9zGwK1WPgxFeqg7EEEL4ImXbIW0wzP2yq1ee+SKNF0nZlVU3FoejGNUkZIzCZWphineB54EPOPLQqpPEQhDyIwNwq2JJyzB1lWWm3DcXZSNlPH9I4WpMrgYeuFB2UPOIuvjAQKFVQVpWavNjXjrszItHGZE2t2sBEu+AIqca3y6uDDe317nO16/3P3V8APfzMZG8uw9mSEQs/pWam1JPgRuW1kWV2btGnrXwN8bBwhCkzVjxZTN6wdJkXqpkxTDpU26dUOKmaBK8yjs4jM7LC2/VOSwAtPxa8X+qUqtp8hJhN8VfYJbOuq6vJqzZwcX4VdLHdc2OaLIcitawIOuq+7RWpYyZ60DQP+tT9TqhYHL2qcnoMi9A5Nfk2fBDb8aew0Kv1a2gf14vWJtgRJQzI+nsH9N48R04R5YL3xLVOVM7KLAw3MleozgSZjMQm5Nn5E4xR0CmGg1FMfC4xx8ws/nJ98pVlb7SPEZL0kWXk+ZaBKZdrRVVldkZ1SpE1PWVrAPyl4C2VpsdVrqMgjZraJOjhUuhl+KazM6vxzHcmNusb265sHhwWYFYebXwvuaVJZM11NWmDoPZZNXZa0bFlA6VyaVT3Hk3TETuG6grPHio9dkHFgPMFH2YHwHvcUenlTJBY6yRxIyw+/wSwkPIPUrWfGp8ATHkJqyfIfFvlEmRqalVOspbYmUohzBH/hFUdfq9OxE3WPJ1kXBbDturKzY4pazSq8jBxU3+/Stsn5qpK6RgjeNKtRan7Ni/IqosUJGimidq6tZFHZ4Yrw+j+MADTHBbIAgTp1EXYM90w2CB0cpKT7KCwpP2PUplvtLlQk6nkI1vrhz3HIqe8dYy7QiZdma6Cl7srleLN3JwPsK1Y2QYjU1Y1GVUjH2gQ9kNaGPp0WkG31tdTIagtcWh8DhCyA13kz84gf+i3x/hzJQnXHrhUGsoqLrEBfadTjGAGq+eE7iPCql54oiKiaooltJCYrssh2lm513GevJHE0j2jJJ05CWzIKUI+m2JKWnZpyZElTVV6Iky41SKjWd35Q+lziJUktlIVZdw3NFIukVdJ1tBKIXgx2Lgi3hOnufY6c2Wyj2T9EvzFi0XEL5fLOkEJlnVqLCG/+QLZdPV8tCZSo8oY2FpJT4ZnoBa4+ciJIyJjMCT+q4MjWlbCiLPYIYVazSsr7ppdIZlUy9q2jDlJI8+xk5VbLlmiqlZH2Tao1VKvSkqKx3tJiJVZTiKasSy0lbSX/z2UdpEelchSRMK40e5V/OlZLpQ+nKC6uVEYHYIcQ49dTUWXxxZ3llzDBwhXekDGpJuldNf0pCuV4wfn6tEPGk38+eLbMUhFJRUfV6YSzZGaaVpGbjaSE8mDq+k0QroT4m82BBphCe/ZR86iGwOY5PYsswD51gSzzIKyh7fyEpFY2RQkaaBs/bSrMo6cqFD0o6coWMbMoUYyGyOLWpXVkx3kiGAko8YUqE5WQTv5JT0w1oCyokdB12GCMhQQW964acolcepUpGTMfug+NXNv0gO9fTYQWAUWNDnR8KOgcNNXVsux0zpq6wnDo6jtBCwnLq6FT1YmhJ+WY6pcaOlSSqpo4tW6SrDk5mzW+HXAR8O/CUjH7QqvIDDQ01dWwKmm01MYVkblCEAeIIEyijrJCZRExWyMoVg5lLUVUDFF+krDsU4fM93MQ8QFdFMyJbYSfpI1lZJ6+CV8HJquCVYHn7UjZlspBm23SvLKlx3B6HeQIrlw76fHqm7MVaKXIcn8dUqxa6ST7LbA2ZAg1UNUAg308ul6Gp0ZGuoMtlZwp0lAwklEKqvCNi4i7GcJ+FnspCKD068MnYXH76dHlL/hLN4Qw58/buTjFhJqmKEpXuKEmKbSmOb8NsB+zfkbgX2KkL74/e3R99jyOgQCt5d32dffnq2XP9+B359of7+/ujQ5KE7wzj6elpFTsu2MYr1EtGtYfxNb9oBXHXGV/5iiwiy25LojT/0rGzz6m1yu2uYpik4aoMAbrJPmanJwP0Gl/tLSu7L7S9mtAf7+/9V6++zxZ+4EWr8asQHxAY5eZW/xf/aeCLvjcaTv0xS1ICh9zGir+//mf51eVztpYkRj/9DadPBL3gEdro4w64MazuzSNVldctIh0vsiELovE1iJMf8WLS/03Pselpwx1IXZwr0R37+H8TcmxC/stnyfsjvOIZURsrK7KK9RronwuqRVOruH/y1P370eujzdX1189XF1d3fzE3dz9/uLoxv3643hy9O/r+TygJ7u9fkQ0GP9wfna5O7o/QN9C3AtxORF/9fPfx+Nv7oz8hm8gosYku8YEHf+jy9SJ/BHVXsSi6FzXWk5eNhf5GtxZaR5k0ugD99/0ucG0YVfr5A61dU1zpoAdbXldF3qyW7KBfCQVEDyZPYvyl6/gP2TdZtsrTc1C8evOb2Dul2viMDZPUZzrYa6PnytW7QlbrMdMKUqrcSBH28UILfzvkdLzWlFRklmSCp5AHztVhC4ShSSoMB8YTZF0cF12DFeihblP+RPIhC03PJe+jaVYn6SVn5Hsjr+Ppr8hC8a8gOaCPaeRgu0lqO8G74jVnFG+CXKt8/WWfXul5ld1BD895Q1UvM9JU4XqboQKA+pbZ5pBsET5J7rLdUSV2+wkwn+nt3SV6k5G+XaxUmj44wkT8wA32qg10nA9hqbWQx5jNjjnPJ9j1iSsmL0Pp5/rKH25LXxd/9nSdbN2tpdwNp1FjmqRo6jaTndCSraHRZTBr7+n1CZuoNlJqM5W9RCL83cq1x+mOfdeUFfVkL5vBkbbRL5yeEcrOF1Dj1mKxV8e1PXd8yGrl3ut77to4CDDwP6PeNuPWHoHLj7dn6+tP67dct/dRZCMKAgrdhSMBEXp6JtxFZ2tvv35LKsd6JkNPojphIE80g0oFo3SoCLrfKdsuPmKo+RkGqkk7VPlBO0qr4GMkBx/IPseSf/vm9GR3tj45cbw335LKbWwSFYcy9ItLPtJS2ASWF6qmLUXVUZZvdYWQuaY6Ri99tjSkZSmrjHSbRvnZUEpBS1WVnImlgzNXVcZp5ee5KaUkmsoYi2PslEIWouookX0SNUUtaKWrjtUDSDe2IidMgkg9ckteHXmY79ZSy0tElVFCDaUKKi5VMI1BHoJILWYpq4x0F0eW+nJVqirj3IdWpL6iKlUVcjrqk7MQVUppZqeQ6EAtlZXxHnY6cmmpqpDzWQfms1pKZ62+JBFNdYxAQ7ukEFVHWQZQVMtZyiojxWs/LeArR6V0lbG6lq2ck2iqZIx2OihzVXWcqL2oHpOIKqV83gL1rWVaWDltfjKhhiGILgPq6GF2jJN66EpXHauW976r/L3v6njvu6rf+x5w3G3wrByU0lXHGoLDVsdwFC2sjjZW31ghmuoYH9UPQhJNZYyh5avvkhSi6igj9VU+0VTJaMbO3geuFlZaWxlzDHXVUDVldbwaRqJixSNRMWqe7/bqMUtZlaQ6hvUrWWWketpP6ltPqZ7mU6q+/aRnuFT9aOmjDdTn0EJUGeWTHagv8YWoLKVHlt6pAqT1VC9oUIPYJatlRQPXpYyLWD+3N1fgbWmiK3Yc3+JcqdNc27d1OOqJHArHjjaqW3iSvGMhqhc7sRlkC+2LmEEixrvuH0XiUFLwOTHxgc7Z4nmUuTheRjUqptbItApsaFouiGNnR9YdCydXt8TYFJMG6tUYl0KQHLcskiTFPeMsIm7I82qt26zuGpsTRpUVuRJSRgoTsxlxvzraFnGUrJSjg1W3Wd01bJWvPm8t2IxG1q3DtQJzcR/xEZln1jCcS/p6c7MYC3XX+HyF/0jgsydqu3nvyHyGJ1lcNxa1Tt+nI68lQeBaB+CwGgA9t/M2A/qShWwly7eQcZfCEroojy0ZgdZZD5MsjCzF3rLMMIJkofp4mrYOVwaeoSG6DYLEDXDYYNHGaH2f4Ji6s67ALqQVq1G/1WgrSRVb0US8uN5cbUTT7wJvaB9V/sXXWjcSPn/J4I0PjsvTCs78MzBw2TtrS4wud7kUddbeSBhKYTRL8ltxfNMokPrtkimCKhGJ1CB3j2fI3sDe2dk4Bvru0QxemJog8h45NgB0MNTunqr+7SmyeHf7etbSjpqUvKmYwTayE7l99KMM4uzo0HEI1M3KnmNPagtvR2r7iQeuMC3zfUa7Srbx1G9faqMB9QvGbDijNg/P0/Dt2L3MzI/EV4O6t2jldcvJtD+bET2U4YlvLWDGbFDGJrCKXKZk83bweZ+NGa/ZRbwrCUgns0dP4RNSSVjJzfwmbUVzGVeVSOYGpx1Vhr88tG4tR386RWVyRDv2DfeADIt2WFt3aRZ9FTQ7rwPbqzlTN28X+SiNzEcnSlLAsQmoP01xvQjwiEKnqtadvMw8I+tXn+bcNQmJdzFLBVJG2xAoiOSOsvxRClJ1RBH3I0o4xohZNIXK0iqA3vTnz9yFx0WephSUpb80TaEyc+Gqhyubp4jVGfizdv2+IoO31eTHu8s3p/2CfkJ1fgQxRD5dqpS3z4KED047MmA2ESnHPaCqML0jmIBoDwXqO65EpmUVpix/rcCVpGrmaqoHFIYr9H+lCVlqKuQMg8BV/LwLSaU5c6++8FeiS38tK8r49SlKPfmed/5UBFFwNlXjCzxffjfPi5ss/cMDD/wFIb+JmsKnJWQeO5F6gJEPBSqQTp5KZOkFkU5A7ixOfC4W7NQl1D0DOZ5KZKnj69Czo0fR0XWuJaU6MgvEa/3YzyRzil7SVd43c02H44DPkGx0+HHe1MP3ZGnXvHl02cJCo6xLWzWzSIsOxxxHl+/UzXIUB55xuy6Cg/DQXLd1c+eSoyVHMVS3y5EUx2yLQxR3LnoCpxHsH1dCZh7mlP1Gp5zGb/NhKVX5YRRV7XYF+WEURHGn7vzgOtvx+QHdnMFeXJ+dZWtlgICr6GajS2C57Ql2WqnabIIaWNbB4dgznUHlDYHqlhHrfPHdPLPRdXsCc85d5rKVb4DrvV23St04cneGuL/1u8b5zLshouav1H4IdP+WZ5NAzeKWZ4NA73Pl3H5Rf6Yyuy/Q/RHwdqnP1QqirFJ3jTPLvdyyZlZwiWVXEvPsNWkk8OitJuRukZZmw7BoO7MNwLVSpmZXZD1MyxxfIL2aPZEweW2DXDE8avYEInR0mhtX99ZvHGc8Fs27sUTO5Q1BUDcoFGCg02gCOeZEm0bJTTJGR5bS9s0L2h1G3roczWjsEW5BV3dIVLCC9sgt4+s3MXtQxr+sshKzV9wyvn4Ts0fuGF3FiFmLJZ4dKbiCBsubJt1jE0MLESYvot0Y+lSkkbMZ1TFccRriIK0yK896j1UUenj0ATfAsqCLzyzhnI3K09GgE8Zo+0hO/TKGLMkGjqCkA893Qrw2gSeSlYwPDUMKXMCH8uh/Bl1WtC4LlBp960ksE/kZBeGLeQCR/QR4XlXcaUUm2rosyAZfiaKAa/mQAGmpKZ0BC3n1SUkJy1LC7HwQxYSlqCRdIQ4tGxUy9CfH6KsQabcBRdTxAWjCJcryObQ6CVd9Jq1rK6rONcE2xaesv8XmKll1jbpXXLEMphKWfIaoTjABz5SqECKlKslnWZ4GPkpVls8Dlg5ASlb+bZIvl/LUthazrNjUlmU9gFMNqUnLyhOuz9/qYaSE5SnPT9d6KClhScq9lrK9V1a2ofVrCB6gBsaGsiRncoggwMd5aiBtaStt3yh/Mda11bZvVMM2xdWk7CNwU57TAsakbKU9X2jJwvf2sBMmtCPnkXMDTZ+Qip57/miTyN9LtIorf2oN4kJVUebOLXCvHhZjbYirRebfQDMKesxOml5s1FAis8GmDUPo29C3uKI4icAPGFHjAkmZ4kxtfCyPcg96bCh1AInS7VZNLrStKHcC1VwO//63sU7UrSh1AqDGhS70QlspMOqX6eIl0kpxsxMUklRq6HgQumZAKbrlhAe+fahjuCt1NdBJBPw4BBGyrdmBQUvanDlwrbKVd+UgvBxX0BEtNc6AHW2O6KiJ+s2od0Pz+2vYlBp3ghD8I9X6aui0oBRe82PotaLjCWiqcfuM6HBBS/XUbULNeIOT4AA83plK6Jbw8qd+GiLIAWGRzlTOQgH5wEX1WRon0DbjJIhQl0JigIdKbjy2gz4aQ1ZEs0lvXp/GFZYlJe7k6xGUcpeSwsVSNMf3PqD24IcyD3vl1Q4J7WDWF5EZ/hwGpw1oHBZSij9gRH1fXjV5Q1tHD1MTcqWuc9hHE3zbis4BOI1OqJ2ebo3XaCL3lBzWVm/94R1Q+GGqr126DChFT15CDZViU1x9F1dfkvdaUe+EnsTvtLC8WcVifcv8U4pmxTK6qwWbga/qmvIdwkrPTBOHK/yPKGgprJRWcuRgiFfheAEtS1Zua0GmtJUySw0iDwErGzWmRRWNjA1xaxgWa8ofgG+7jsRCBBY/bUApvfzc1RC62okrWhkkCcSn7+nKNA19NW/8Qrw4wlwVeJ+4Wuog5osnLo5cKKvnJYcXRgnXWTNj2ZtWlj+SOtDukU+lIrZdTVNp6bfhzvElGswDrLS2Uma5Jv4QsbrOVasJqAO3EFZb2qVHJZvIvepKU7kcRc/WYOlI7pYFteleyOtJd1pdbV/kAK0HM9/MqiXZmwbU0mvk1kQsNww8SKxuDLirf6YDmdJW3/fTAXwQDujIQatolH2IW8MQe2/XTBc/bUBT308Hek1dW99PB3lDX0/fT8vrkhKfb5h3bJSV/h+afR7cguzt9LSPNj84kW2GIBKP1LKLIMS9unFRWrJeocyYtvDJn50ZsDottW+8AaenQSWTUfidn/1VnARaE5qyjyt+3mxnQhReDR48y0qL4gDYpphkLVHKedkBHsroSrnFTfvkMe9ligfeOQe27ph80VD6dHExeiVZQ+r97XUegPfL3V9HavYo+4FvZi8FcYeZ2Q8n5YjqIX+GRvEgDJSOBp0ARsVsFCbGrQ1jsIO4P2aYOnxiRYsHHrCi/u2v6nwo7Wh7Dvp9IFZkPBi5oE/q5tGLCBsVwTX0roEvHrCt86kdIAjN/oXF/A+NUBmVoPZFlkpGz1W0LEASeANhQpmJSDCMSkc2YkoUIKN+f8+OG4lWkoSyYRhBC+C1wtkguzO8bIcbsV9XNjbFI145s0cpECrAbKpJwn1EZm7vbjbyYLSSJJTrxP0rDbmBChXZcGQwjlG32Nymu93A2CM3VltPFjBMzTAKkmB4bogfsKWnAPApAmEII0V4tJokXPHmkQejlWShouBXVAkpSC1aSRLqHylMFSRTKSMdLMsLDwrKY6UjC5QA68HMWsYKHlxTTRJug+WuFbE1xKTTLTveWVX92pKTDdkE4v7zo7ipChVZGMdTUolWOlpH4Lpbk6N7CbSCAPdAc2w0SlNlNE7WShmNUdw92nxeG4+2X94+GqBeXEeDtGRGA+GSKpExytvHA+RlczxBeT9X8Hx950+S8GTjpj1cZxuBiDXXMpCMQ3GZW2lIUA1i1RCOv9w0HvunSHng0AM2Ai0hBfIUOYkkSCkxGmQLYvj2zXiK6v7RCIydA0yEMdsDOhGy/ossRyky/k1oSUCQm2WMm1YaPcqU0rqGAhTTh08qcAqd0Uhef2QJJoYnGDKiWVCdvZ8KzIO0Cmp5vyTC8JE/nBxChwANwXiBxCOpayhAMSMgkVHbOqORAkciWcjNo42HA2f8MI2HPGf9DBl/sOJzCfPF7RLVlh33n5DAUVuR2yVSQMZ9SdOSrStKQAJCsmVFCUhASLYmKIHxWZGxw5GdGcdsY+yGMMPA7d/OyktSqoxv6iWRaUfb/t187HYepTAa44CPJ5DjqEmM7+gfwOl4huJuGfPr87dSAOR+GYTzU4H1cx0I5P7xmTLw4wTgjfyOJ1FxtWTGD3YUQevHw9QkxtejZMWsREVKKUhjDG/K52YZsQW/CRQDWRZKYfw4hovarIMRaNjjGLTE+Da4b3qpwNLKVtu7vF9yKIW9Z4pzTGXk9qiBPtt4oLqIij6bLAvRUNVnU4BT6ChCQo//EcTOo/xj6xJUMlI2GqwhIvHaHIyxx/G+FA+iN/TmNh0vlCj33Vqq0KSrpX49qSG+cgvr0NE7XIN8TSVJLNni11RR04Maj9NQGT816gWJwFx3k6O8XWIUFofEGk9Q3S+DIFcFUgLjIcKYFWaUzVHTkEIZDunKRTIihGsHCO53iCxZ6SKpNKRQkghYElVITWJ8XwHYbmAJrJZpdRUqAZkBMflXUENEenROBkS6+BbDjBIQpYB0P1LFw+mSGg0W4fPH3cQ8QFdsgWoTq0No/FBR7Jo23KZ7eaxOKSkwy3WkOuJ1DSkUz4kFNkx0gRQKUhhI9PRMQUuuW0sB2mBcGAEs8egvDaTn85Pvxg8lFXdLmTct9M6VmbZpiMjCSAyt0QqyGAKrEHsw5FYi5iKxxPocWkEKQ3JaryYhDyL/bGoyKoBkn1JNRqpJkZ/JWrxOpMaoW1IKwFQQqUqjwfNqRFJI/FSagQcnuSavU0oFGAnvXuw0Mv3AzKK59B8cJcI6qK4CP3aDhOfgTBHoDk0lqOTEFyWIlZYKNKkVkm0dFUi7nd0fmFmEqRBSATUYLVoESjw6dD/U0CFvIkzCR7n1I+GT5JUwFUIqoCKZVWRtHSVVgqLaQC6NSPBF8nYZDpbIntToFlP2YpcaTWkIKXyxq8AaE5pxAExqhrpDSBWU9BB7v56GBpESzA5NvW03DdB1dVWtDhWgREdZq0MFUyGkrNWhAko8Lmk/lPwgYI+YEjiZ+dS2jqpWmgok4XO4GK00FUyFkJJWGvDtwJNc+NGvp6ohqQRNcs683gJUQRQre4zNPrQSuramyn65EkSxU11lIkKKB+OS2rg8kJZAJBpPkXhlmBvyGSgJwQMiZ0TZbLEQFVmY2D9VAENUFMCMnB7vIhoxUd6JRbY7SzNVOrJA+bZOeaBSRxYodVwbtZB2AvEue6FqWpJgFvrLdVWUN1pJFspS8OyIiCzKAaD/1icKeCglJVBh4PYf1SCIVWhJg3EcMSKApvQ8kbGDPC0sVYdvWKO6Ey0cNYf64nj7IDler/rj9PMj1bSkwfDzN4H9axonpgv3wHopJhsVkA6K60DfRagnM2qlLhc8La8UHzeQM/HckGr8Dnnl+HGKx8BgotGFDhNK3YjjET3qYWwiqRQzW/ukmLPQVAOqsgQqK27UPlUVbHU5Wbxig7c8GaUkCZWtFZUnKmWkcRR0om0lnWj7oKANTUQkUaA1Zjy+yVKoyMOoKPmljDTOr+NGcNtAv4qP4PYgjZjRaeMITud0ozAOpOPHUXb63Mj9PC0g8T09nTh7FV3lvZKu8uHB3smzFCqyMGUYEHkiWkoSy/UUvCCIiCQKUVPWW2/ryQKOWCfSghJcItIDcq6C5FwFCvSC6IVEjjWB6wYKRhB6RCVRfdQJigPrAY6Zxm0iNsRk0RzUnXgYEd+ghVUJSSLh6HLSOEREEgXHmpNGISKyKCO2Z7ZIVIQyxwHwTgVO0OuHKXQUACmolUoZBTjfqMH5RgVOEd1InohSUgSlqH/fklOFl4U/UodXyMniBe7L6dmJijxPKclCZccsQxNYFowVvObaerKARTgreTRKSRIqctDbwT59q2BSrSYli6ViXEB4OVAnShZAUJqlUJGHwcEEVeAQHXmgMyU4Z2pgzlW0DCodWSAVMwRq5gSyvfPAOih429WkVGBlk7hx6iQqhmy7FFVABsGDoyrxSi0FYImDu2JqwCotSbAqtKY0V01KFsvx1DCVOpJAjyiXOmO2bjSJKCFJJDXThYomCMs4BUqACiU1UArKHK2kBCpWMBxOKwksB5Y+DBe1amUXzsouRUEIhroVJ2RvXD5jDlK8scbH5zxKjC5VgH26SqHJnPoDfEE8TmQKHhTKpu81oMON+MUP/BeZUf9eB2jpBSxPxZxql6bmTmPNxPHxBsEwiOXaa1RadsuqRUbdec9JnEfFyHVZtci4VKAaEg9DSLUROrDb0mrQ89WGSlArKVVocnNrNTRVy2BrG0PHbuPtIGwpKgb1E/icxKrrgWF5PS5oKGRsE3pcUVzFDcurcQEJRxIjfRRtqaQGTHZVKkWmbvUp2RwqPaFCwSmcUym3PJKco4SvpqYI0PlNUQkplRSBJVFqqXl5VlJq0NQ1/BW38B+Bmyoiq6S09Ho1npcbw/0efR51XG78EifQe3Tgk8zG183lp0+Xt7Ld91zFvL2744/ik/tuVG4YuYpRF5PMbbkYfzZjUCnI/5R7qqgKMdlBadeMkqRYwuT4NhTYxtSL2KO62KLa+3PHD11fNTYbh/V1wPjXd8YvgZt6MDZuYRykkYX+FScgPhgeSBKUiPsIQt8Io+DRwWPDxh76MAJJEBlEzhg2aIWhWpOZ4IBRDzi+WquV4oBZuIvO1mrtUpIDht8jlSwCUOD/Gb6MfcDwGXihC6tlHkbsuGAbU2BtQ9xUXzfvxyeNMFppbYDva3HvxQH4PnQ1pluXKQGy7N2jMe167fEwXvpW0DyEQhMeZUqEbJKkqxnjobvO4qVMkm6UKRGySdKtZoyHDv0jCaxgkuJK2xJh++V0msRr2hNilHhVjWJkv8fKezYdkX804W26AwMxyD7hN3QjnJ9eQMqiSApO8ohrxgToLtI4CbxJGWmTAqQf4A6kbjIpas3mAOuP7Ug9AmBxZOF4WUachmEQJcaPnfF6uk2OTo0eo0xPX1Ab7y74qdERlDFcU+Qzrc7rhuaA+Yufrr5+Dvb75qojCetuLmc0pAcg7uBzcuO7L8XVyhKiQOk0MAC0yYrQRXtCTpClWSaburwIUgkyCMFKCSWPpEnA+xhwDrrIxj6/vv8s1c/DFPkoqtEtyqiTzr7Nm+EymSGGSRqaIXhxA2AbTVVeAKkkGEBgpcJNAu7cR3QxTjq58YCuLOGhF5JzHCTA6DEkiKY0vw7DsVLu9vL9h+vLlWerG72hJGuGyaTBV5AcFJlSa6BorOhRbT43tVZQxlAuWMzyqBX+7bffTPIAoY3HNY/zZRZqrdCD4r4L4hiiF24Ew0CPU3VzTiBqih7UL/PJNggSXBVCnnxeUyB9T2PrpjBBKgcS3mcsyQf46FgQv5sdJPQZ1zqXH2/P1tef1m+NKzkv86eP02qswsX15mpjXAQRlGXJlW7vbjZrWSmU4bI0s7OkMx3fSWR8hJ4dPSpIK+jhFqi4QGumaYfyfZQEOGhf7MQjU6tf9QFGPnRHliCmLG5+4yW/xqeLC+P97bV5cX12Zn65+6vhB74ZQyuNpB98dkhqlIZFiOhI5rENihog8qSFgziJIPDkIFG6OXgW0s3XnvnQT/CHIp5G0fGRq4wEzaDaEKKWpXZrCspUY3WFKjkSF1w2i5DYGgpzc0ORrw0zUD36j96ZlgyMdwzn66g0yEM1ScrQFk9c7sUFkm9+1EBxrQNwpN5rRZbK4TqUPGBFwQe4wy9i1Ie4r3XjzYubLx+vPpmbn96vz9/iT3eX/3Nnbq7+epl1i7K1Teha9KOY7O1fvt7dmF8/v7/7eHN7XdM6FVL6fPPJ/Hj1+e7y9urLJwmdAqXw+OrLxeefP9S9/D9u8p/NTia++Sv5rhgh+qOQ5c1fNneXpd2fN5fm5ubiz5d3m3He3Ny9Ny+/ZAl8dfMF/fP9j58vx0ltrj6//3Fjfr29+eVqg8XQv+5uLm4+m7+c1hRPuBU/U2oXP73/8uXyM0H8MJKRVvx0+eXy9v3dze04rbLp/uOb05OPZ+uTk6vrN98KkLz/+hXTfL28vbu63PDemL+Ov/x8bW4+/Nm8+wkPE6B8ffH+s7lBvrz/dGl+vblCJe+2niXWAmQXN9dfb75cfrkzL97fvceF5uvt5QZ95s6quAdgfvnl6sL85er27uf3n8ffaf6EPLy8xeW2UcD+kQbJf2YNZ9NH1Zb56ERJCtzVIf+F1+T1j5cf7j5vijLVtoMKMtVSsUTLLUrQ68vrm9u/oAeDSsPnq08/cSdkwfZ1876oBocwa2eoCWLe3t1l9cn7zfXI4lqu3zM3lxe4Pul4XNVFYg8py5UfLumseXNbTwB8alxDjrTZPtaXBia29Yc/DF7J10bCfUD0f/zvvOuzt6wV4EFAF/JcxnVRs9PSeZEfoFd640LcYrgJSTLjD1c2urL6dpVaK9wIQkJRltBB9vXAVSt8hef8li2kqj0bvEhdv3nr+RkfZufbILLrWeMPfzj9ZoT9slE1DFBetrLCtJknE/h87J2dTWF917C+Cx/Pj+PmyLUe024AEhNsnRrAIXsQuh876pqWfb32Sld802cnTkqjZZ50cYE1q7tbUxBGZVDUBTxW6m2ZPpSXLdIJ1/EfWB7k15C/NlbkhEktC/xbGAW/Qisx8B7xPfSN/Eo8KrxyJ8gcu9S38Jd4PAr/HdfokiidoF6yQQKU2hd4MD7wUWPARG+FOTwPPCcxdxF6CZlhkA27zQDh4415FgznevzIfpQkzsQPvpgdugZh1haY3m+r52V82uwlabD9BCLf8ffxCrjuDK6X5rMdoXMChNAGfuJY9YYBcOMpIUAEzSzAeTwSwwMPMHtlgMhb4WZ2AqI9TJocPZe1mmXHHvrmB8HGmSRDcki9bYOCfKffeLNleOyhb34g7cNj+7Q5IKcHorONiFDw98fo+x+424stE1Wlw6SpLu2roY5RF/EH3mpqQJ+sT+GDwVuT+vovORB3J0YxUtf763jnB8f5t7MA9bzQMyz6t+nyUlHZmc03zvF/Z99Mm0x6aUalS/tVePzf5LuZ0kYbkUj69I6ZHN9I51/RlNHJIpIm/R2m4x3+7bj6bdoEmgxMJLWGu7jHu+L32VJtckCh8jfcRT3e4QuOswuOywsmLpbTI4qk4DKGrhSm90Id6h1T7L9yqa50j2P0XNY/uDh+TFGSKBtVa42pHaPOFLTiH/Cvq+yfU7AUAz1m/tn0QFin+h+id//q+BqEP/zbv9/8fPf15zvzw9Xtfxj/9u9fb2/+6/Li7sv768v/WGU3y1QdLWontoSy3vF/oyZ86qcxtI9DgOu0VnXGlPAsrzmwwLyH8eyY9zdX4o0rIIcgTpaXnqx8LeQr8myVr4dZOahiiZ2zde6xnazydVZ2FjY0m11a7f10RVXPWxDDZpJQgo2r84tWOM1WQXKAkYvc+/8iN3ZGGxq4fufBOEZJf+xCf58cfmjO+ut+wrhnL/KM6ev/9ynP8pTz5RHZEyZzfM2HRlbtB2G9M5nFpfH267fbN6cnO7xyyvFaK6e6bTogWsGnMHvr9NWQV5e4C39TjAAJPY/2MxRLE8yH2fAXZEVAkUsfz1dvVqdN2IEbSLYGtp2thQHuzzGM5nGLt4Ui/m5yXx8fP0WoVWLi3QVm1kihvvSywwdbX1vdX0ew+F6sWGQSe6un+8l3O6pA8LjScfT0jHT2HvQTqbdku0XwL5Xm+psEpPXL1SDA1xblybV3LtgLlqAF5VPVGW3cy1og9cnVRfr/b+oP1qz9nXzhgv6MPpRyx09Ocjhu72NeSDkVlbOcyEpdENkwhL4Nfetl3CT7cjzyUT1vt4YU+KfIZcqxAjeqOkHg0XxvkJZj9unV93969lx8aX6OELr4dHWS3QxxAAPH36Ovfr77eIwai3/KBYqWZ7nSNbVWXmCnqERlgRBWF9n2mK/5ZV9RGv+YgZeb31fZWlx0P1IKYZS8bCz09w/4KEfSpqWTPkQCmeebBIZ/RPi1zxO5ZOexfTYwSbLVFQK+GPqoZJJYI1ZqEbCxj7wZZZiMOXZVxfWYECsrsopl+FaUWyRHX5TFAH1V7uLvrrboqKz1vHX0+mhzdf3189XF1d1fzM3dzx+ubqgNJUfvjv55f0QFeXh3j764R/028AhRfg2sh19A5OANvDH++h3+A1+A/4dqgNBBV9kPnwMrnw4kP7wr/rGH1kNgxvaD+QZ1bM6Kr18X/8C73W7C9n09vT/y6+/5H0jmiISwUg4eO17oOpaTvGT065P1m9VblM/UOvA7ejw5C159F6On8bfqcUAb6eGH/brMdNnmPOwq2W+Ld5zUNnZSB36gu4LI2TuoT0hu81PXfV2e5Ia+OH2dKSWofYI+Ha/X5+uzb749/+b316IUrc3SZryWYfnmfH3y5tvz9bk4Ct7hIZcMp+v12zffnr09EzfeeBoR3OMZTQmaU8Tx3Zvz0/M3vDDFdMft3aV5UWxPjcclBUqJ9Zuz0/U3wtbpvbGojZ0ANxj5OE6/Ozv95ruT777jzpYUA3zE9g/At8mE5Qj7J6gEr0/OT78Vtd+YcBI2jfI/evinb9a///3o9/8HR8d/fQ===END_SIMPLICITY_STUDIO_METADATA
