// Generated by write_buildconfig_header.py
// From "//third_party/connectedhomeip/src/data-model-providers/codegen:gen_processing-buildconfig"

#ifndef CODEGEN_CODEGENPROCESSINGBUILDCONFIG_H_
#define CODEGEN_CODEGENPROCESSINGBUILDCONFIG_H_

#define CHIP_CODEGEN_CONFIG_ENABLE_CODEGEN_INTEGRATION_LOOKUP_ERRORS 0

#endif  // CODEGEN_CODEGENPROCESSINGBUILDCONFIG_H_
