/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <clusters/shared/GlobalIds.h>
#include <lib/core/DataModelTypes.h>

namespace chip {
namespace app {
namespace Clusters {
namespace Pm25ConcentrationMeasurement {
namespace Attributes {
namespace MeasuredValue {
inline constexpr AttributeId Id = 0x00000000;
} // namespace MeasuredValue

namespace MinMeasuredValue {
inline constexpr AttributeId Id = 0x00000001;
} // namespace MinMeasuredValue

namespace MaxMeasuredValue {
inline constexpr AttributeId Id = 0x00000002;
} // namespace MaxMeasuredValue

namespace PeakMeasuredValue {
inline constexpr AttributeId Id = 0x00000003;
} // namespace PeakMeasuredValue

namespace PeakMeasuredValueWindow {
inline constexpr AttributeId Id = 0x00000004;
} // namespace PeakMeasuredValueWindow

namespace AverageMeasuredValue {
inline constexpr AttributeId Id = 0x00000005;
} // namespace AverageMeasuredValue

namespace AverageMeasuredValueWindow {
inline constexpr AttributeId Id = 0x00000006;
} // namespace AverageMeasuredValueWindow

namespace Uncertainty {
inline constexpr AttributeId Id = 0x00000007;
} // namespace Uncertainty

namespace MeasurementUnit {
inline constexpr AttributeId Id = 0x00000008;
} // namespace MeasurementUnit

namespace MeasurementMedium {
inline constexpr AttributeId Id = 0x00000009;
} // namespace MeasurementMedium

namespace LevelValue {
inline constexpr AttributeId Id = 0x0000000A;
} // namespace LevelValue

namespace GeneratedCommandList {
inline constexpr AttributeId Id = Globals::Attributes::GeneratedCommandList::Id;
} // namespace GeneratedCommandList

namespace AcceptedCommandList {
inline constexpr AttributeId Id = Globals::Attributes::AcceptedCommandList::Id;
} // namespace AcceptedCommandList

namespace AttributeList {
inline constexpr AttributeId Id = Globals::Attributes::AttributeList::Id;
} // namespace AttributeList

namespace FeatureMap {
inline constexpr AttributeId Id = Globals::Attributes::FeatureMap::Id;
} // namespace FeatureMap

namespace ClusterRevision {
inline constexpr AttributeId Id = Globals::Attributes::ClusterRevision::Id;
} // namespace ClusterRevision

} // namespace Attributes
} // namespace Pm25ConcentrationMeasurement
} // namespace Clusters
} // namespace app
} // namespace chip
