// Generated by write_buildconfig_header.py
// From "//src/lib/dnssd/minimal_mdns:gen_minmdns_buildconfig"

#ifndef MINMDNS_MINMDNSBUILDCONFIG_H_
#define MINMDNS_MINMDNSBUILDCONFIG_H_

#define CHIP_MINMDNS_USE_EPHEMERAL_UNICAST_PORT 0
#define CHIP_MINMDNS_HIGH_VERBOSITY 0
#define CHIP_MINMDNS_DEFAULT_POLICY 1

#endif  // MINMDNS_MINMDNSBUILDCONFIG_H_
