unsigned char login_content[] =
  "<!DOCTYPE html>"
  "<html lang=\"en\">"
  "<head>"
  "<meta charset=\"UTF-8\">"
  "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
  "<title>Login Page</title>"
  "<style>"
  "body {"
  "font-family: Arial, sans-serif;"
  "margin: 0;"
  "padding: 0;"
  "display: flex;"
  "justify-content: center;"
  "align-items: center;"
  "height: 100vh;"
  "background-color: #f0f0f0;"
  "}"
  "#connect-form {"
  "text-align: center;"
  "padding: 20px;"
  "border: 1px solid #ccc;"
  "border-radius: 8px;"
  "background-color: #fff;"
  "}"
  "input[type=\"text\"],"
  "input[type=\"password\"] {"
  "width: 100%;"
  "padding: 10px;"
  "margin: 10px 0;"
  "border-radius: 5px;"
  "border: 1px solid #ccc;"
  "box-sizing: border-box;"
  "}"
  "input[type=\"submit\"] {"
  "width: 100%;"
  "padding: 10px;"
  "margin: 10px 0;"
  "border: none;"
  "border-radius: 5px;"
  "background-color: #007bff;"
  "color: #fff;"
  "cursor: pointer;"
  "}"
  "input[type=\"submit\"]:hover {"
  "background-color: #0056b3;"
  "}"
  "#heading {"
  "margin-bottom: 20px;"
  "width: 100%;"
  "}"
  "select[name=\"security-type\"] {"
  "width: 100%;"
  "padding: 10px;"
  "margin: 10px 0;"
  "border-radius: 5px;"
  "border: 1px solid #ccc;"
  "box-sizing: border-box;"
  "}"
  ".form-row {"
  "display: flex;"
  "justify-content: space-between;"
  "align-items: center;"
  "margin: 10px 0;"
  "}"
  ".form-row label {"
  "width: 100px;"
  "text-align: right;"
  "margin-right: 10px;"
  "white-space: nowrap;"
  "}"
  ".form-row input,"
  ".form-row select {"
  "flex: 2;"
  "}"
  "</style>"
  "</head>"
  "<body>"
  "<div id=\"connect-form\">"
  "<h3 id=\"heading\">Silicon Labs</h3>"
  "<form id=\"connect-form\" action=\"/connect\" method=\"post\">"
  "<div class=\"form-row\">"
  "<label for=\"ssid\">SSID:</label>"
  "<input type=\"text\" id=\"ssid\" name=\"ssid\" placeholder=\"SSID\" required>"
  "</div>"
  "<div class=\"form-row\">"
  "<label for=\"password\">Password:</label>"
  "<input type=\"text\" id=\"password\" name=\"password\" placeholder=\"Password\" required>"
  "</div>"
  "<div class=\"form-row\">"
  "<label for=\"security-type\">Security Type:</label>"
  "<select id=\"security-type\" name=\"security-type\">"
  "<option value=\"WPA\">WPA</option>"
  "<option value=\"WPA2\">WPA2</option>"
  "<option value=\"WPA3\">WPA3</option>"
  "<option value=\"Mixed Mode\">Mixed Mode</option>"
  "</select>"
  "</div>"
  "<input type=\"submit\" value=\"Connect\">"
  "</form>"
  "</div>"
  "<script>"
  "document.getElementById('connect-form').addEventListener('submit', function (event) {"
  "event.preventDefault();"
  "var xhr = new XMLHttpRequest();"
  "xhr.open('POST', '/connect', true);"
  "xhr.setRequestHeader('Content-Type', 'application/json');"
  "var id = document.getElementsByName('ssid')[0].value;"
  "var password = document.getElementsByName('password')[0].value;"
  "var securityType = document.getElementById('security-type').value;"
  "console.log('SSID: ' + id);"
  "console.log('Password: ' + password);"
  "console.log('Security Type: ' + securityType);"
  "var data = {"
  "id: id,"
  "password: password,"
  "securityType: securityType"
  "};"
  "xhr.send(JSON.stringify(data));"
  "});"
  "</script>"
  "</body>"
  "</html>";
