unsigned char provisioning_content[] =
  "<html><head><style "
  "type='text/css'>body{font-family:Arial;background:#EFF4F3;margin:0;color:#32403f;}#wp{width:600px;margin:0 "
  "auto;}p{display:inline-block;font-weight:bold;text-align:right;margin:9px 30px 9px "
  "0;}p,input{width:200px;}h1{text-align:center;font-size:3em;margin:0;padding:20px 0;color:#d6e4e1;border:1px solid "
  "#7F8D8C;text-shadow:1px 1px 0 #333;}input{height:24px;border:1px solid #ccc;border-radius:4px;padding:2px "
  "5px;margin:0 6px 0 20px;}input:focus{border-color:#32403f;}form{padding-top:20px;border-top:1px solid "
  "#2B3736;}.btn{width:100px;margin:15px 0 15px 250px;font-weight:700;color:#fff;border:1px solid "
  "#000;}h1,.btn{background:#485c5a;background:linear-gradient(#485c5a,#32403f);}.btn:active{background:#32403f;}input["
  "type=checkbox],input[type=radio]{width:16px;height:14px;}#msg{margin:0 0 10px 0;}div.menu3{text-align:center;	"
  "font-size:0;	height: 25px;*position:relative;*top:1px;background-color: #C9E71A;}div.menu3 a{display: "
  "inline-block;padding: 0 20px;margin-right:1px;background:#F7F7F7;color:Black;text-decoration:none;font: normal 12px "
  "Arial;line-height: 24px;border:1px solid "
  "#CAD0DB;border-bottom:0;color:#666;vertical-align:top;text-decoration:none;}div.menu3 "
  "a:hover{background:#E9ECF0;line-height: 25px;color:#000;}div.menu3 a.active{background:#E9ECF0;line-height: "
  "25px;color:#000;}a.active{background:#E9ECF0;line-height: 25px;color:#000;}div.menu3sub{	height:3px;	border:1px "
  "solid #CAD0DB;	background:#E9ECF0;}.table {	margin:0px;	padding:0px;	width:80%;	border:1px solid #485c5a;	"
  "border-bottom-left-radius:10px;	border-bottom-right-radius:10px;	border-top-right-radius:10px;	"
  "border-top-left-radius:10px;	margin-left: 50px;}.table tr:nth-child(odd){ background-color:#ffffff; }.table "
  "tr:nth-child(even){ background-color:#ffffff; }.table td{	vertical-align:middle;	border:1px solid #485c5a;	"
  "border-width:0px 1px 1px 0px;	text-align:center;	padding:5px;	font-size:14px;	font-family:Helvetica;	"
  "font-weight:normal;	color:#000000;}.table tr:last-child td{	border-width:0px 1px 0px 0px;}.table tr "
  "td:last-child{	border-width:0px 0px 1px 0px;}.table tr:last-child td:last-child{	border-width:0px 0px 0px "
  "0px;}.table tr:first-child td{background:-o-linear-gradient(bottom, #485c5a 5%, #485c5a 100%);	"
  "background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #485c5a), color-stop(1, #485c5a) );	"
  "background:-moz-linear-gradient( center top, #485c5a 5%, #485c5a 100% );	"
  "filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#000000', endColorstr='#000000');	background: "
  "-o-linear-gradient(top,#485c5a,485c5a);	background-color:#485c5a;	border:0px solid #485c5a;	text-align:center;	"
  "border-width:0px 0px 1px 1px;	font-size:14px;	font-family:Arial;	font-weight:bold;	color:#ffffff;}.table "
  "tr:first-child td:first-child{	border-width:0px 0px 1px 0px;}.table tr:first-child td:last-child{	border-width:0px "
  "0px 1px 1px;}</style></head><body><h1>Silabs Provisioning</h1><form id='fm' method='post' action='#' "
  "onsubmit='return pt()'><div id='wp'><p id=141><input class='btn' type='button' name='refresh' value='REFRESH' "
  "onclick='up()'></p><br></br><b><div id='msg' align='center'></div></b></br><b id=1><p id=1>SSID</p><input id='ssid' "
  "name='ssid'></b><b id=2><p>Channel:</p><input id='channel' name='channel'></b><b id=5><p>Security Enable</p><input "
  "id='secenable' name='secenable' type='checkbox'></b><br><b id=3><p>Accelerometer Y:</p><input id='accy' "
  "name='accy'></b><b id=4><p>PSK</p><input id='psk' name='psk'></b><b id=6><p>Checkbox 2:</p><input id='cbox2' "
  "name='cbox2' type='checkbox'></b><br><b id=7><p>Security Type</p><input id='rv0' name='sectype' value='1' "
  "type='radio'>WPA<input id='rv1' name='sectype' value='2' type='radio'>WPA2<input id='rv2' name='sectype' value='6' "
  "type='radio'>MIXED MODE</b></br></br><div id='sidebar1'><p id=139><table align='center' cellpadding='0' "
  "cellspacing='0' "
  "class='table'><tr><td><strong>S.No.</strong></td><td><strong>SSID</strong></td><td><strong>Channel</strong></"
  "td><td><strong>Security Mode</strong></td><td><strong>Select</strong></td></tr><tr><td>1.</td><td "
  "id=150>SSID1</td><td id=151>SSID2</td><td id=152>SSID3</td><td><input id=290 type=radio name=li "
  "value=0/></td></tr><tr><td>2.</td><td id=153>SSID5</td><td id=154>SSID6</td><td id=155>SSID7</td><td><input id=291 "
  "type=radio name=li value=1/></td></tr><tr><td>3.</td><td id=156>SSID9</td><td id=157>SSID10</td><td "
  "id=158>SSID11</td><td><input id=292 type=radio name=li value=2/></td></tr><tr><td>4.</td><td id=159>SSID</td><td "
  "id=160>SSID</td><td id=161>SSID</td><td><input id=293 type=radio name=li value=3/></td></tr><tr><td>5.</td><td "
  "id=162>SSID</td><td id=163>SSID</td><td id=164>SSID</td><td><input id=294 type=radio name=li "
  "value=4/></td></tr><tr><td>6.</td><td id=165>SSID</td><td id=166>SSID</td><td id=167>SSID</td><td><input id=295 "
  "type=radio name=li value=5/></td></tr><tr><td>7.</td><td id=168>SSID</td><td id=169>SSID</td><td "
  "id=170>SSID</td><td><input id=296 type=radio name=li value=6/></td></tr><tr><td>8.</td><td id=171>SSID</td><td "
  "id=172>SSID</td><td id=173>SSID</td><td><input id=297 type=radio name=li value=7/></td></tr><tr><td>9.</td><td "
  "id=174>SSID</td><td id=175>SSID</td><td id=176>SSID</td><td><input id=298 type=radio name=li "
  "value=8/></td></tr><tr><td>10.</td><td id=177>SSID</td><td id=178>SSID</td><td id=179>SSID</td><td><input id=299 "
  "type=radio name=li value=9/></td></tr><tr><td>11.</td><td id=180>SSID</td><td id=181>SSID</td><td "
  "id=182>SSID</td><td><input id=300 type=radio name=li value=10/></td></tr></table></p><p id=138 "
  "align='center'><button type='button' class='btn' align='center'style='height:30px; width:70px' "
  "onclick='scanSubmit()'>SCAN</button></p><p id=140><br><input class='btn' type='submit' value='SUBMIT'></br></p><b "
  "id=9><input id='conec' name='conec' value=0></b></div></form><script type='text/javascript'> var m;function ram(){m "
  "= $('secenable').checked ? 1 : 0;ds([4],m);ds([7],m);};function scanSubmit() {var "
  "xmlhttp;setTimeout('window.location=window.location.href', 10000);if (window.XMLHttpRequest){xmlhttp=new "
  "XMLHttpRequest();}else{xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');}xmlhttp.onreadystatechange=function() {if "
  "(xmlhttp.readyState==4 && "
  "xmlhttp.status==200){}};xmlhttp.open('POST','/scan_request',true);xmlhttp.send('band=0');};function check(){m = "
  "$('secenable').checked ? 1 : 0;ds([4],m);ds([7],m);}function $(x){return document.getElementById(x);}function "
  "oc(e,f){for(i=0;i<e.length;i++) $(e[i]).onchange=f;}function map(a,f){for(var i=0;i<a.length;i++) "
  "f($(a[i]));}function dsa(a,v) {for(i=0;i<a.length;i++) {$(a[i]).style.display=v?'block':'none';}}function "
  "reado(a,v) {for(i=0;i<a.length;i++) {$(a[i]).readOnly=v?1:0;}}function disb(a,v) {for(i=0;i<a.length;i++) "
  "{$(a[i]).disabled=v?1:0;}}function scan_save() {var key=290;var "
  "keybox=150;for(key;(!$(key).checked)&&(key<(301));key++){keybox+=3;}var m5=2;var m1 "
  "=document.getElementById(keybox).innerHTML;var m2 =document.getElementById(++keybox).innerHTML;var m3 "
  "=document.getElementById(++keybox).innerHTML;document.getElementById('ssid').value = "
  "m1;document.getElementById('channel').value = m2;if(m3==0){$('secenable').checked = "
  "0;ds(['4'],0);ds(['7'],0);}else{$('secenable').checked = "
  "1;ds(['4'],1);ds(['7'],1);if(m3==1){document.getElementById('rv0').checked = "
  "1;}if(m3==2){document.getElementById('rv1').checked = 1;}else if(m3==6){document.getElementById('rv2').checked = "
  "1;}}}oc(['secenable'],ram);oc([290,291,292,293,294,295,296,297,298,299,300],scan_save);ds([9],0);ds([3],0);ds([6],0)"
  ";function u(b){$(150).innerHTML = json['ssid1'];var val;var x=1;var i=1;var indd=150;for(i=1; i<=11; "
  "i++){$(indd++).innerHTML = json['ssid'+i];$(indd++).innerHTML = json['ch'+i];$(indd++).innerHTML = "
  "json['sec'+i];}map(['ssid','channel','accy','psk','conec'],function(x){if(b)json[x.id]=parseInt(x.value);else "
  "x.value=json[x.id];});if($('conec').value == "
  "3){dsa((['138','139','140','141']),0);reado((['ssid','channel','ssid','psk']),1);ds('msg',1);disb((['secenable','"
  "rv0','rv1','rv2']),1);$('msg').innerHTML='Provisioning Completed Successfully!!!';}if($('conec').value == "
  "2){ds('msg',1);$('msg').innerHTML='Scanning Done "
  "Successfully!!!';setTimeout(function(){ds('msg',0)},999);}map(['ssid','psk'],function(x){if(b){json[x.id]=(x.value);"
  "}else {x.value =json[x.id];}});map(['secenable','cbox2'],function(x){if(b)json[x.id]=x.checked;else "
  "x.checked=json[x.id];});if(b){json['sectype']=$('rv0').checked?1:$('rv1').checked?2:6;}else{$('rv'+(json['sectype']="
  "=1?0:json['sectype']==2?1:2)).checked=true;}}function ds(e,b){$(e).style.display=b?'block':'none';}function "
  "req(m,f,p,d) {x=new "
  "XMLHttpRequest();x.open(m,'/provisioning_update',true);if(p)x.setRequestHeader('Content-type','application/"
  "x-www-form-urlencoded');x.send(d);x.onreadystatechange=function(){if(x.readyState==4 && "
  "x.status==200)f(x.responseText);}}function "
  "up(){req('GET',function(r){json=JSON.parse(r);window.onload();},false);}function "
  "pt(){u(true);req('POST',function(x){ds('msg',1);$('msg').innerHTML=x;setTimeout(function(){ds('msg',0)},999)},true,'"
  "json='+JSON.stringify(json));return false;}window.onload=function(){$('fm').reset();(JSON.stringify(json)!='{}')&& "
  "u(false);check();}</script></body></html><!--";
