set(SDK_PATH "/Volumes/Resources/stash/matter/green/third_party/silabs/simplicity_sdk")
set(COPIED_SDK_PATH "simplicity_sdk_2024.6.0")

add_library(slc_generator OBJECT
    "${SDK_PATH}/../../../examples/platform/silabs/provision/AttestationKeyPSA.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionChannelRTT.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionEncoder.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionManager.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionProtocolV1.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionProtocolV2.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionStorage.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionStorageCustom.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionStorageDefault.cpp"
    "${SDK_PATH}/../../../src/crypto/CHIPCryptoPALPSA.cpp"
    "${SDK_PATH}/../../../src/lib/support/Base64.cpp"
    "${SDK_PATH}/../../../src/lib/support/BytesToHex.cpp"
    "${SDK_PATH}/../../../src/lib/support/logging/TextOnlyLogging.cpp"
    "${SDK_PATH}/../../../src/platform/silabs/Logging.cpp"
    "${SDK_PATH}/../../../src/platform/silabs/multi-ota/OtaTlvEncryptionKey.cpp"
    "${SDK_PATH}/../../../src/platform/silabs/SilabsConfig.cpp"
    "${SDK_PATH}/../../../src/setup_payload/Base38Encode.cpp"
    "${SDK_PATH}/platform/bootloader/app_properties/app_properties.c"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Source/os_systick.c"
    "${SDK_PATH}/platform/common/src/sl_assert.c"
    "${SDK_PATH}/platform/common/src/sl_core_cortexm.c"
    "${SDK_PATH}/platform/common/src/sl_syscalls.c"
    "${SDK_PATH}/platform/common/src/sli_cmsis_os2_ext_task_register.c"
    "${SDK_PATH}/platform/Device/SiliconLabs/EFR32MG24/Source/startup_efr32mg24.c"
    "${SDK_PATH}/platform/Device/SiliconLabs/EFR32MG24/Source/system_efr32mg24.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_default_common_linker.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_hal_flash.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_lock.c"
    "${SDK_PATH}/platform/emlib/src/em_cmu.c"
    "${SDK_PATH}/platform/emlib/src/em_core.c"
    "${SDK_PATH}/platform/emlib/src/em_emu.c"
    "${SDK_PATH}/platform/emlib/src/em_gpio.c"
    "${SDK_PATH}/platform/emlib/src/em_msc.c"
    "${SDK_PATH}/platform/emlib/src/em_se.c"
    "${SDK_PATH}/platform/emlib/src/em_system.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_attestation.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_cipher.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_entropy.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_hash.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_key_derivation.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_key_handling.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_signature.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_util.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sli_se_manager_mailbox.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/error.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/mbedtls_ecdsa_ecdh.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/mbedtls_sha.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/se_aes.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sl_entropy_hardware.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sl_mbedtls.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sl_psa_crypto.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sli_psa_crypto.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sl_psa_its_nvm3.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_psa_driver_common.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_psa_driver_init.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_psa_trng.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_aead.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_builtin_keys.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_cipher.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_key_derivation.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_key_management.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_mac.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_signature.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_opaque_driver_aead.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_opaque_driver_cipher.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_opaque_driver_mac.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_opaque_key_derivation.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_driver_aead.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_driver_cipher.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_driver_hash.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_driver_mac.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_key_derivation.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_version_dependencies.c"
    "${SDK_PATH}/platform/service/device_init/src/sl_device_init_dcdc_s2.c"
    "${SDK_PATH}/platform/service/device_init/src/sl_device_init_emu_s2.c"
    "${SDK_PATH}/platform/service/interrupt_manager/src/sl_interrupt_manager_cortexm.c"
    "${SDK_PATH}/platform/service/iostream/src/sl_iostream.c"
    "${SDK_PATH}/platform/service/iostream/src/sl_iostream_rtt.c"
    "${SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager.c"
    "${SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_cpp.cpp"
    "${SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_dynamic_reservation.c"
    "${SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_pool.c"
    "${SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_region.c"
    "${SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_retarget.c"
    "${SDK_PATH}/platform/service/memory_manager/src/sli_memory_manager_common.c"
    "${SDK_PATH}/platform/service/system/src/sl_system_init.c"
    "${SDK_PATH}/platform/service/system/src/sl_system_kernel.c"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Source/cmsis_os2.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/croutine.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/event_groups.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/list.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM33_NTZ/non_secure/port.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM33_NTZ/non_secure/portasm.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/MemMang/heap_3.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/queue.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/stream_buffer.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/tasks.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/timers.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/aes.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/asn1parse.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/asn1write.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/base64.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/bignum.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/bignum_core.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/bignum_mod.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/bignum_mod_raw.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/cipher.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/cipher_wrap.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/constant_time.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/ctr_drbg.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/ecdsa.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/ecp.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/ecp_curves.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/ecp_curves_new.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/entropy.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/entropy_poll.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/hmac_drbg.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/md.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/oid.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/pem.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/pk.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/pk_wrap.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/pkcs5.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/pkparse.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/pkwrite.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/platform.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/platform_util.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_aead.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_cipher.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_client.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_driver_wrappers_no_static.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_ecp.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_ffdh.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_hash.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_mac.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_pake.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_rsa.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_se.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_slot_management.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_storage.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_util.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/sha1.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/sha256.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/sha512.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/threading.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/x509.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/x509_create.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/x509_crl.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/x509_crt.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/x509_csr.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/x509write.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/x509write_crt.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/x509write_csr.c"
    "${SDK_PATH}/util/third_party/segger/systemview/SEGGER/SEGGER_RTT.c"
    "../../../generator/app.cpp"
    "../../../generator/efr32.cpp"
    "../../../generator/main.cpp"
    "../autogen/sl_device_init_clocks.c"
    "../autogen/sl_event_handler.c"
    "../autogen/sl_iostream_handles.c"
)

target_include_directories(slc_generator PUBLIC
   "../config"
   "../autogen"
   "../../../generator"
    "${SDK_PATH}/../../../examples"
    "${SDK_PATH}/../../../examples/platform/silabs"
    "${SDK_PATH}/../../../src"
    "${SDK_PATH}/../../../src/include"
    "${SDK_PATH}/../../../zzz_generated/app-common"
    "${SDK_PATH}/../../nlassert/repo/include"
    "${SDK_PATH}/../../nlio/repo/include"
    "${SDK_PATH}/platform/bootloader"
    "${SDK_PATH}/protocol/bluetooth/config"
    "${SDK_PATH}/platform/Device/SiliconLabs/EFR32MG24/Include"
    "${SDK_PATH}/platform/common/inc"
    "${SDK_PATH}/platform/CMSIS/Core/Include"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Include"
    "${SDK_PATH}/platform/service/device_init/inc"
    "${SDK_PATH}/platform/emdrv/common/inc"
    "${SDK_PATH}/platform/emlib/inc"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Include"
    "${SDK_PATH}/util/third_party/freertos/kernel/include"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM33_NTZ/non_secure"
    "${SDK_PATH}/platform/service/interrupt_manager/inc"
    "${SDK_PATH}/platform/service/interrupt_manager/inc/arm"
    "${SDK_PATH}/platform/service/iostream/inc"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/config"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/config/preset"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/inc"
    "${SDK_PATH}/util/third_party/mbedtls/include"
    "${SDK_PATH}/util/third_party/mbedtls/library"
    "${SDK_PATH}/platform/service/memory_manager/inc"
    "${SDK_PATH}/platform/service/memory_manager/src"
    "${SDK_PATH}/platform/emdrv/nvm3/inc"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/inc"
    "${SDK_PATH}/platform/security/sl_component/se_manager/inc"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src"
    "${SDK_PATH}/util/third_party/segger/systemview/SEGGER"
    "${SDK_PATH}/platform/common/toolchain/inc"
    "${SDK_PATH}/platform/service/system/inc"
)

target_compile_definitions(slc_generator PUBLIC
    CHIP_CONFIG_SHA256_CONTEXT_SIZE=256
    CHIP_CRYPTO_PLATFORM=1
    CHIP_LOG_FILTERING=1
    CHIP_PLATFORM_CONFIG_INCLUDE=<platform/silabs/CHIPPlatformConfig.h>
    CHIP_SYSTEM_CONFIG_USE_SOCKETS=1
    OTA_ENCRYPTION_ENABLE=1
    SILABS_PROVISION_PROTOCOL_V1=0
    SL_PROVISION_CHANNEL_ENABLED=1
    SL_PROVISION_GENERATOR=1
    EFR32MG24A010F1024IM48=1
    SL_APP_PROPERTIES=1
    configNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2
    SL_COMPONENT_CATALOG_PRESENT=1
    CMSIS_NVIC_VIRTUAL=1
    CMSIS_NVIC_VIRTUAL_HEADER_FILE="cmsis_nvic_virtual.h"
    MBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>
    SL_MEMORY_POOL_LIGHT=1
    MBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>
    RTT_USE_ASM=0
    SEGGER_RTT_SECTION="SEGGER_RTT"
    SL_CODE_COMPONENT_CORE=core
)

target_link_libraries(slc_generator PUBLIC
    "-Wl,--start-group"
    "stdc++"
    "gcc"
    "c"
    "m"
    "nosys"
   "${SDK_PATH}/platform/emdrv/nvm3/lib/libnvm3_CM33_gcc.a"
    "-Wl,--end-group"
)
target_compile_options(slc_generator PUBLIC
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:C>:-mthumb>
    $<$<COMPILE_LANGUAGE:C>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:C>:-mfloat-abi=hard>
    $<$<COMPILE_LANGUAGE:C>:-Wall>
    $<$<COMPILE_LANGUAGE:C>:-Wextra>
    $<$<COMPILE_LANGUAGE:C>:-Os>
    $<$<COMPILE_LANGUAGE:C>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:C>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:C>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:C>:-imacros sl_gcc_preinclude.h>
    $<$<COMPILE_LANGUAGE:C>:-Wno-unused-parameter>
    $<$<COMPILE_LANGUAGE:C>:-mcmse>
    $<$<COMPILE_LANGUAGE:C>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:C>:-g>
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:CXX>:-mthumb>
    $<$<COMPILE_LANGUAGE:CXX>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:CXX>:-mfloat-abi=hard>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-exceptions>
    $<$<COMPILE_LANGUAGE:CXX>:-Wall>
    $<$<COMPILE_LANGUAGE:CXX>:-Wextra>
    $<$<COMPILE_LANGUAGE:CXX>:-Os>
    $<$<COMPILE_LANGUAGE:CXX>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:CXX>:-imacros sl_gcc_preinclude.h>
    $<$<COMPILE_LANGUAGE:CXX>:-Wno-unused-parameter>
    $<$<COMPILE_LANGUAGE:CXX>:-mcmse>
    $<$<COMPILE_LANGUAGE:CXX>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:CXX>:-g>
    $<$<COMPILE_LANGUAGE:ASM>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:ASM>:-mthumb>
    $<$<COMPILE_LANGUAGE:ASM>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:ASM>:-mfloat-abi=hard>
    $<$<COMPILE_LANGUAGE:ASM>:-imacros sl_gcc_preinclude.h>
    $<$<COMPILE_LANGUAGE:ASM>:-x assembler-with-cpp>
)
set_property(TARGET slc_generator PROPERTY C_STANDARD 17)
set_property(TARGET slc_generator PROPERTY CXX_STANDARD 17)
set_property(TARGET slc_generator PROPERTY CXX_EXTENSIONS OFF)

target_link_options(slc_generator INTERFACE
    -mcpu=cortex-m33
    -mthumb
    -mfpu=fpv5-sp-d16
    -mfloat-abi=hard
    -T${CMAKE_CURRENT_LIST_DIR}/../autogen/linkerfile.ld
    --specs=nano.specs
    -Xlinker -Map=$<TARGET_FILE_DIR:generator>/generator.map
    -Wl,--wrap=_free_r -Wl,--wrap=_malloc_r -Wl,--wrap=_calloc_r -Wl,--wrap=_realloc_r
    -Wl,--gc-sections
    -Wl,--no-warn-rwx-segments
)

# BEGIN_SIMPLICITY_STUDIO_METADATA=eJztnQlz3LiZ97+KS7X11u4bqym1JF87k5RH1ni0sSyXWjO7SZRiQSS6myNe4aFjUvPdX4AESfAEQAAkU++mJra7m/w/vwf3jX8efLu5/q+L81vz5vr69uDDwT/vDm4uvny8vfzlwqR/ujv4cHewWt0d/H7wunxnc/3zzfnFBr323Z+ePffVI4xiJ/C/vzs4Xh3dHbyCvhXYjr9DX/x8++Phu7uDP/3xzv8ujIJfoZW8Qq/48QcvsKGLntgnSfjBMJ6enlax44L7eGUFnhHHxiZJbSdYQSuIIBJFb4cwSl42FvobvUfU7g6Q9KtX320D14bRKx94+Ecr8LfOjvyGf3VcWPwWu6YHvSB6MfOnVnuknkYO+gk/9sH4JXBTD8bGDYyDNLLQv+IExHvDA0kCI2MXQegbyPyjg7024jQMgygx4DY6WXu79amR6xpdhowuos3F588XN+bN7a15jp7UBtRhp5PHf/ROTBtuQeomugOpx1YnVxgD04pewiTQTdVpqZMJRbINHx0Lmo7vJKZt2dYE6WrAZB8lSYoe8MEORtOl/bbBTsIfkfLN7fXmXC9X20xfeDk+Eo7SMCk9iNcThBrDbB8tLiQnoGuY4UxrEdwh4emTXMtuJy8IQ5NULg6MdVP2WuMpXaCXTly41C12MkLPde7zlGHD+3Snm3DAXm96vId24mqP205LLCYS2tOhtQzmhN8ZeROqqzkF0iTYQb+3PYUStetYIMG5LXkJoXo3CIHRY6wzkG9uL1A7xwsDH/pJrI+pbae/lCZPmYgfuIGG+KYCqtMaTzFjuYH1gNrhGtm6zfXBwUfsxR74tgsjrWHWssSHpDOoWpZ6WyxBnEQQeORZjSm+xxg3mM7g6jLGBMvSoeMjq741VcC1bfZgOo1axSRqOjGHbPJiJhHw420QebMAd1rvRc86fBOGbre9Qbz71HETx58cs99uJ67r+A8wwt+sXFsXW8NIJ8jKisp+MfqnLpSWGXZzKnY83IRxkhczth/M9dH6dPUGj5yVbtQeD12Q4IRc/t564lNWm1K/t57YOMhg4H8B93HtsdaDFz/enKyvPq9PG4+1FbNgaz3VTLwvcQI9swy2cUV/snci2wxBlLwY+SChUQ9DowgjIw8Kg/LXKF0ycmajC8pg+JEg42m4NEe6qJqe1FJib3Re+pab2sz4LC2Bo+Oj7TFKuY53+m5cIaQqMAi60c/GiNzyRRNYXrgwZ0omfifGtmA0+lBv4DBduE8j4C3NiRJKxI3EWqAbORS3G5aXLs0JgsTtAh4kX5oPBRO/E0jf3waL86PC4nfFA+i92IqcMAlGduk1etSi43csdN3FuUOYuJ2Ay8vwUDDDwzRGFIvzoqTidmQbR9bisnwJxe3GLkSdo6W5UUIJuOEsLjIKJiEnTNydXaInJRi3O/vtAnNICSXgxvMCvXgWc8JZLy6TEyR+F8DymooFE78TFrD2I+fhNLpRUnE78gBfYguMHObU5wmFxe2Ki5qVS/OjYBJy4vkeLK7JTnMJO4MXoDn+8oZNuvj4nYOJ442dLtXoU4XF78oSa3hXuIZ3F1jDu6I1vAcc9z54XpofFBa/KyHY3y9woJHm4ncmXlyrhSDxu/C4uMF3gsTtQmj5i+tVFUz8TkSLqwkJkogLZuzsfOAu0RUajdul2IpAYu1DYC/NozoZv0NwoXVJDYzfneUNmsaCg6Yx6tRsRy5K1OhFSSXiyAJn3ioqbkcW2YQXb8Cni2zBp+JN+EXOKohPKjzaYHG5o2DiduLJHruAWp8TBRPLCY+sgF4IP43DWgnVXDy1CA+6qLgWQnV82fqq/UVzt6nnBf7Q8jvHt1rL7upLke8d/cVKzmkgGKOyaAxiWV7sxGaQ7UHDL0/M2GV+ENihXoHPiYlYHrJ9YCh56K9Ha/BMFEbIBzY0LRfEsbMl212mDvxuAlb4z83dizAc3tBP9Q8E1QO4MDkMhtyAE7Q56miVUVYqnaNU4CsLsj2Ck6NFHZVoEwxZTFL9AxN1tMqoMVTZtVerR4y6a7ig071OmjiJKJllbmtxdE9WmxSZMspOzfiPBD57EyM2TTNSN54add2R27xGQ9JmxVJ4EgSutQeOP7w1ot2I6935nu88nyqDl/xFVm9RtJrCndgz8/KA7izLDCPo5M3+2YDbGIbyXsV9ECRuANA3Qz2L+nkCQwV1/UntmbPCb5x5YLRBBrMrK5zOrzaXm6EgOs8OEBrK2X2bX2rhl9cseFO1M3oXskD4ZW4ZmL3s5LYJBrNL/jg5nGk+XgpgEDf5DW+jQ1WM/rZuB2vdOke4oiJgvjAlxocxs0rbOzmZBZM2PojphakJIu9R/yayDsyacfEivFWQ4KOF1srKGtSKnShQMu5GGiPWByMviM3EsR5moaRsM2OOd/dq0zk8rIht6K4saf/I3s66dfXNC9TpYG0apg7pkG8Zd5z4oTvVEBcNynTRgOumYbU+m8euLcWDvp1kjLOkloLfubeHJxe3hybYcWaiYk13du7ym/RSe3AEY25BTlQ0CurP1ul3w+UOR/w77RP1Jkv2LcvlKFUnEysNtI8GnGo0iOXQMJp4vu6uT+r93tp5GJ1BljdjfERuPjpRkgL9GzP7AwoXewCPKHRCcZ/ZwEgRMzvYh6SiZCDHJkkXCOUBTNPlGmKwzCwUADPPF6dFRYn+cWkWcAGhKkP3xMtkabhws0i6FIBQvMwNXEAoyGb1E1TlM1tdb7IUXDdbpOM2DN+4eFmp2S/oJ1RyRxAbyieWl+RSHyDDTad9VnM2wTqrawNQgrEWwQREOzhd+ckVVTSVYPxMVuBwRQz//FIVlWG4Qv9fUnSUSIKuhEHgLithFUTCuWS3uOKsYtLT5FhGtqpP2o7PVRNNOot40TsFPapxki/ylG+UkMWiePhisvSe26TWKtAErIgmjz/AyIfTlTadyBWDnixJh8xUKZk4WqyTqhOIxc2syBWD+ukC6NnR49BkQcciaPEEAPHSTe2BmPlCr44rzSoopPCFNpKhQN+JM1FgYJNZUDRtDyZ//PAcgFxg5g76MHL0T9J0hSBlmw26n2Bksgty3zP42AVobl1kfi7MyjobFs/mzcJZGNYwj9W4JQsXXGZ+Brb21gDlKW4JDJOIJKU5wGvWOZPSHJyFYfGk5Dr3w0kJPZCZOL86OcnWEYHp/EO2jS77OporzYAQ25GFWlPW3tF/HEXGmbdBKosDy6vxUxNM3NexOqfn21TZykQwRYulDkfZZexNmjz06kaHQ3CifT610OPa5oOeu59gt0oN7L69U6UjzU2z+aie3nj2HqHnIuBtU3+KxicFRxkdpptqUXCNrnchcDteJ9i31YhV5rYt8tSEvYoGX3+fosk5xdKuGl73Aq4G1SRH59awug/GbXJNcXBWDavzWKwOqlnq07rdYcZ44lwac+TRiY6wqXP1HFDTwZZA/esbmmzEJg/bPKVb27bSHaqkAaa/H4ddwl24yiBHPTctFrHIrj8mxYI8oZWV5pNiFRbZ9cekWMQgs2yeFCrmSFekLJqWq7QptckwhhZCTl6GhhToK1cZk5TVbbzkYjnWctf8gjnmbWvUNYjAsqALo2kO4CiCp3btrNF2s7qOuB+Udf4Q9Wrg+U6I1zpNcOimjIsNTg4P8cWLi4/BLkjulczMAfD2VCsiioLwxdyDyH4CE9Sd3IFC5si7AFkngUVRMMW6SAFHSiRmOi1eXxZ/nYvlBMwup1uWAyUTA754GVo2yoroT/2zKkKOdPNxOhXvwTK9IWDs3JFd8hu9hIn+dqtoBqmjcVZIy/SlyTauBupalNFf3i2mNi5W3VVcjLhEBYsJJlhWIuQBBcXAtyxvefgUFAvfA9YC+SkqdnWZL+30FtXmzrJBE43lyh4cLy8uaCq2A+uzN4t0geJiO3F2vF6kExQXw4ndEkulHXepBK1fQ/AAl+dCA4zhRrKPILAdf7c8R1poQo3HRbnSQhNrPC7MlyYbX7w8Ajed4LawMfFSoY09/rprtBIr25Hz2NoSOm4kJw/1JPJ383UmKpdq/YgCijNV5wpTbSURc6XBJubRZFtAR/nUvxe0wyvUMCRLT0wbhtC3oW9NcQKiiG8DjHwekoC5Tx03cfzsfsqlOdiDKOQfeolu5S/TwzaksI+oRHUm22A+1sc6pJCPADWHFupZgSbkD+pBL9QdQibkTXY9WZLOOcMy6FONT8gzywn3k5xDMcatCo7PpyQCfox4kPay/RsEHe3rfopdJPKeFpij/VxiWTmAOdrPBZah/ZTiXi67Wh8m5fM2CME/0iVXiZ2AQr4tOxJ7IcfE3zKrkj7GMR4usWDtJuQblnISfLKgd7Ign1pcamdnaw8hUx0PNYIqO5/QBy4q8NI4gbYZJ0GEemrzDeZRYYbH8dBHYwiynRQ6kvq/hJcsUKan+UKlJblUEnVk2O6EzjUKtxQXe+nExha3MOu8zTiAPuwXzScxvrgk7wYYxcdtFuZYA23MeMAyPargZMYPl+lbG1JmHHi5PootSWmN3C3TMY/rpuZ6ixZvTMZRvbhysYtPyLPkJVxead9kEx+vWGyE9UKK+7jIqOsEVDebXyyTUzOVb1Z6c3U7YfMU0ToSu+9cPW+miTPFAYuifpRcQs7MO4Iz5I7AuA39Gtlfs0SPKDQhl+acxBjyh3vWgn5pGaOjQ26NGBptvr4Hvu068y1dYrlH8wk5N/us75BnYlO+9JuYEeEuNUU28PjaMMXLHnDc++B5KX71sYk5FcST3NQj7lEBJu4OuZY8Sqa40nGsa01InRupqCba7MFRHKJcQxIqYmy4dfz5OhIDrtBoQi7N2jMacoi/R9tqPy/Qm4JLrEiZewC96VEvnFAclXNB2crQhbg2CCgWa8XrS3GtF06sk7mH1oOZnwqxFM+G+MScW65bIx2adb5j0CH+yY6ufvcCPaLQxIcEFuhPwSUzJLBAt0bMRPV2uRfqHs03ckhggZ7V4EYPCSzQsQbeuCGBhfjVxzZ2PoN1clvzY71zipvbVO+08Svl/dA5b1sUVLiTPHzGW9aZZk2xbLKo4LvIONB35zcOltpjhYv5dcVGjmnUOMaNDlz6lpvaTI8L+6bG8RKW0wTVaLIwsmP5uJddxLcU+JJG2URiftsUK4Xj/cng3u2O8dqTn8/Pe5Zv1h77eHOV3x3x9favnc+33vAD38xKqy6IjhjEyNPntDw4jSK8DBQcBu2rUblhFIRdKyQ73QGxtmM31XlEILmd8oAVaTtQQJ1bJaZQbC3eLQLZ7VTvYtehdbD9C2Rr2fkKelfA7zoLtRGUewhCU9tieP6QJMBGxcO9Oph7yJ2nUgVJ4Ok72psZHoTSqDBYh2VFARL1tfU9uIlpEAazDcMIWgCvZM9G3h2tK6i4PejHYh0N9IhXIe1QAITze9GEYbD/iGRubq83s3PTIAxm14m1rWbl5i0gWAd1wjhG3TrzPt1u9Y0pclO3cVj8YWqGUZAEWue6+PlbOBz8TxEIQxgtg56GYbAXlePs3DQIizkKfkWl5/xhTYMwmP+RwnT+QC4pmKdLeuF+/pKkwmDxJsB6MLMG/vypognDYN/gx6+Wgd5gYYZ6BIG3lGqnRcM6pRDE2q6n5YYuIFisjreEuqXC4B507OpGzNURpAFaDvQ2tueibUIMEmctxblIC+ODhHnVMxdiaX2QsV6EzMXaohhkxiXIfIm0tD7MmJcbs0GW5hvXInHMarXGeMiRn8NzTq5zH4HoZfgCaI3XXbSChFAbBMzoudaizhf7x+htfRdYsSlpAibrU+Qk87KWBIOs9yCGb05nA63MD1Lq3bPEpOzfmNRBmXV4Z0YtGYZbFtZ8nMQ2i8+00uhxxqKpjsBJa/rwaQHEBcYgtaftrCMmqdd5iFG9dHJ2fjrdJGWrdCrNc1BqvbiTE7XnKs9uXi+YL+7rCJy0ZgTmy1dtjEHqwJkvcIntQb5Q35WbTL6wffVmm+/Bis/mIyysM0p8O9Z2GxlHQU+sM8JxxkDkoJu3TU/ZZ3DO256n7DM45219UvaHc47eLfvsvNO/L7+L0wwDV9sBELywJcRwHySJTDu617YPnd0BoQAGSff4frFZUWsEw2Nxe3A8G2ZhnEW4PnszJyMxz6I8O55uwXIHJTE/nIcCH9nH5+w43nxlfotieFSzuEtqNt4awXAtRXYLzFdNUQBcpFpPAOLG7T3vp84cg5lxKYDhcVIX9al0ntTHHielCYZ7ob7ppdMt3G/1PkvzHKO52vcUcw7rDm4f7h1BmY25zsA7gjIzLkEQGUGZn7jAEKBGaekRxM7j7Omji4d7VmAu9gYDo/Wj83RpjmZP3/HR/W00E9uYkbgLRYR+7uK6H4c541GefqHxdlWuOY8mCAf5zAVKE4J/JGI24gbE8CogL0imWyXWRC2tM2a/8Gmrs0FW5lmUs9YelP1hzjDWfDcBG7WGwKTVelcEF2zv3RAtVty7nnBlaxdshcCkTSJgzVe01giGe8vAdgNrurW3rc5yZZ81sj97M6HBwDUTMSMrV5lVzKzMx1na5xrVWUAq6CIZZI/QG6hVZu6hO+mupCZ5B8fwaHXsmja8T3ezk3eSMNkt15lzcK2OwKT1nHi6bchdrAUAkxS9eHwyf/+hG4WTXudpigLkfWcm1qifz47ezzaaXRhnEpoWah7NuEagwcDDO98cAQ3AQzrdfpIeUvaekvzBeL5VyjQAk3Te9Sw1Aj7W2RNBjYKXeebkUKNgti+t6CVMgqLOnnP6sEXCyb4AaJGQ1nnVrEg4910o25tC5t2O0UnCy04uKytOJTD9wMxOVdR2LbWIO4NwvB7GbpDQN8wtwK8OJG5vyNWvS/CiQuGln3OLTRuDl3q7tbVdPySCXXDwcuu8NkmEu++apD5ucuf83NgEg5c6BA+LyJYFBy93NOOi/TYGdzm4iLDmWCtPjtYn9bPWo/LZE9vdLELtsznHWRscgu2zBZD3n9/fyz7nGrAODhHuuWc/+3FGto6X4EkHknxbf3l+1eFE2pcL8IVgCLUvF4BdcAi1LxfA3XfnRh/37FMVPSzc/DMuJGpjiLTqF0Ddcy37YKt+AdgFB3erHvh24M27ErQfR6RvsgR6jlVp9V7BAqBjofTSHJJaggNtJNFRsiV4UaEwT7hqnVXVd2g517lXrQACEx7gW4RIefQt+Qy4Tu0FkTN9xm+hEggWa+wfz89KIDhY51ng1QXcu9Sr+1CuuZErDBZvfk7O7LwlBos3dVwbtUS3010U0stcQ2FwW+gv111ASUGDsJit+RMGYWCR7gH6b300Py4FwsUcBq62uy4FqQsUJrf++2EFyIUug51pdLVFzXs1qjVHR7RF29MNbW8+DEFyuF5pu6qQn7iGwuTGiccE9q9pnJgu3AHrpVgQMr8jg2xjPNtGqG87x84pLt9oOiHvcC8mezkXWph3HXTC3sUpHmuGyXI97CAU8jKOpx//GfaKEAl5ka06XpYbBRKfHwsqHLhLAuq4nQWg12lY9MWpW7ODUyAM5mxDy+zAJQWTdv6xJJtrLMnez9/jIgwMUmjNMA/YRC0g2KwLKNJKCibtr7NM5LR5f+2byGkfybAA2s5p7J7DK2enrThYxLNsc2/x9m11b9DuFjBitOMaMdo/2NvZUQsIFmt52OXswDQJg9r15q91CQODlDy9lDGtNg6Lf/qVji3mzkWOLc6zBYCe8ZBCL4heyNVJJnDdYP5huB4mhic+6o7HgfUAZ1iH0/SgwcIid1DP9WH6M+9a1BUHgxgf3j83LWFgkOJj/OcmJQws0unPd2mB8tysiK8dOF4vgLXA4OCdvzQuKTho3y6C9i0PbXFG8ezAFAgn8zLG0Fo0vPTZ4cWLoS9oWPSB+3J8crSA7EiBsJgj5xEk0AQWwpq/adHGYfEXJ13PTk6BMJgjB9WZ9vGb+Zc51EhY1AsYe+tZFNs8Ygff1jA3agHBZsW3NiyAlmCweU+WQHvCx3q2gLZchcHiXcC8Kd9MaXauGLD287cwaiQ81NmSnTh1kgVMJnUB8fgQBA/OQoK+ROHgThw8ZrAI7gqFwV1dqTI3do2ERe14i0AuMRi8jygHODPs2m0CUxwM4kWsDuFcD1Ke9LYE3gKEj3n+0oIG4WKO55/mo0Fa25e6tgC1dveg3gxrZ8/MSysRocG/gpIc4pAvowIp3i/tg3sXzjfQW/H3YQn5RBZaPcAXZM+JzOQlnLGB03aul2+Ml/GLH/gvM85L9vpHky1/Bwx2Q2z3S+4zfidxfHy4RRjEszalqZjophLzKIxQkyVxHpflUZ1KzCOc41DBjofV5mxhdXjVJuPzLN8VsARPKhJe8lkXJtTIeXfa1E5KmelwnQ4HWkCCfvgJfE7ihZVgw3TjPFxe/mcTjvN0WWX3MB2fh+jFaL5Bd8qZEoSPe+adLRQ4/w4WcuTJ3FO+FLvArG95/AZJdkvAr8Fw8ju/LSPzliCc3EmUWotokVQkfOSL6SYK9gcfgZsuA7wi4Rpp6fiy66v6aEwMdzsYNQZkms+8xAn0Hh34xDq5ZXPx+fPFDWt4J3/KvLm9nezQ09xNo/LEyCGMOgsjheQPT5Y0GNAcSZrybiHQBQtrTsc1oyQpVrI6vg2n2zLe60EPlLLM2fii9rH+gQ4qEI7cWhNGwaOD5ySMHfRhBJIgMoiY0W3GCkOVhjK5DlMecHyVtiq9DmNwG52sVVqjBDvMfURvZweBBv6f4ch2LHwGKAXDahVZkbIrnLYZJsu3zcexwSAMVNrqoPpWvHO+B74PR04tcSB1GeLgyaoKbeHUa22I7MK3gtG3h4pAUYZ4eCYIppqpIaar7OS9CcKIMsTDM0EY1UwNMaF/JIEVTJDlaEs8RL8cTxFQTWtcZKMrj1Fk/TVL+exG5rRIEahN8yzIQZ7PuIYcezj3CCzKHk9oTRCJNVMcTOdpnATehGS0QQ6+T3ALUjeZELBmsYPwB4mjFePIwgeeGnEahkGUGD80zkfsMjTS8x5TvV69oLbTbfDT2D5Qy1xNb9igKg8bih1Gz3+6/PYl2O1Gry5r2nRzMaMh3GH6Fj4n1777UjylyOkCoFO+A2OTJf9ziZk8TNDMTU1VlmEJ5wdN93mtINCbdlkBjVPEeTbG9u3jF4l+D7adj9UZ3ZI9JcfJu7zZOj6SY5ikoRmCFzcAttHUZJmVcHfAcJ/H1wm4dR/RQzh4ZPq9XVHtoerAOQwSYPSY4QRSmPqGkfpC6ebi46eri5VnqxqHoASJuXxmPo2yXnhhl1SpyCqCh27tm/sARPZ5thLBuXdcJ3lBP6Pv8ThZ82vPSlcg8lb58Ie3W5/m/8T/AkfHR9vjo/Wp452+Q+8nQeBae+D4Hdqx/dD81kJtkjxsV+jXFfLfQn866N8f1kh09WZ1tDLfvDt9e3b8dn1ajj5/56FU6X6wYWxFThb+f/zOaH+Xj67VwgZ99x0O01+hlaB/H7w+2FxefftyeX55+xdzc/vzp8tr8+r6089fLjYHHw7+9s98xVXi+BfP2SB+fHfw4W9/f313EEEveIQoBj5sgRvD1+WDmzwu8XPFoWrGjygqb26vN1VR/br8rRo8NfHP9R9BiHJkFIQwShxIHwpRPQI9VDHl1wblN813PeQ/eifo5yz2Ox+o3UDU/jlbtJ9dTNT5mw0fHQuaju8kpm3ZFs9z0Ev7HnN8lP6jNCwO1Y/MeN33bPu8jM6fieW+p/LTFYZ/LVj4norgDiU36mGcaFASTV2IksbdwXckEX64usq+fPXsuX78gXz7/d3d3cE+ScIPhvH09FTkEZRdjDjGbWf80AriOMFPviJpL3stidL8S8fOPqfWKre7ykr4VWqRZFgWKKudZWVvhLZXk/jjXZaFsgksXAbFqHzAZVNuaPV/8Z8GfqjMU4U7f8xCh2Ahh7Hi769lsxNe7IqojZvbCxMXJYEP/fw4idfVj67jP8AIF7Er1679gmIJZSjXsbKiIJs9bLybpXOia6LHAGrotR+hk7HlBtZDjGeY6s/ARyyxB77t5vfcDv3csuAEcRJB4JEnOvRbT/RrZJxOdi6h1fGg08hDJvmJ/WASAT/O9jr3v4ILlmqNJUM/K4VaDy0o59xCD7cJ4L9g3mnPG7zunSd43dWqbH65L78qOriv6W7663Zn83Wzw/u6r8H+utVpfN3oTrweaOz1/JardM0NdHxdjs6/7hv97vqhoVUbnu36ofE8PXba9X0xetn527r9W21YquuHfefX9GBRx8+1oZqO36nhude11u/rrv5o88v8rc6O9WtqrvJ1OT36ujbT95qeZEQf6lPCZtGqrJr251eby41xjsoD45Is1LA81ATNKgKnKp3HC6ESQlqD2mM2Vidrv3knJxIaXpiaqCfw+E5CI/mtWN4oJoLbz+tGqATxWkYkiLMtnWMk8qIVK+DFBFjE4hP5lLUd8PiJg4LhC+5VXvx4c7K++rw+LcHK7pUJLC/k5ROVLtsCqpXvUWfL06edcGcnQW3LSzUp406RLmn0ONmHo0PdA2bRpQ64i0JRI6HrapKG2qIUpjGIuMswQfFtHFm6onQXWpGuxLgLHX3YTmDiwXdN+vutviDfb591STtrXXHpAG1lllMevqFB/AG+xBbgbioJqruoRNQo/XwPdJWyhTweB3R8bZW/C/Gxbdqc0JhLXX25FHVJ3PvgWZd6CPb3+ppcXqyrHPAedTVuQ8vXVVGEka6sg5TN2Nn5wNVlATXkQGLtQ2DrMgD1JvVYW3sO9eOs7U6fuL5ui87yNtVZ4OpsQT/aQFd4P9mBpnRSm01Va8IjsxZKVfONFGbJr0ScDK3ECUocaUiJqxhhKcSb4Jza90GQ4OURMGpMzTY+8urlO9HxDrFsciqOIX+GqL9774x8sRxJo7bFj1AJbGhaLvLA2ZL5tbFCMhARd/quvwnJ/cPib+LZk5S7uq6961BhD58TMwHxQzZvjNImd3neVJSOh2wpUJkWxdIxeZcsFYgS+OyNU8CVMXBd0XyUvz0crmKK5XqWIr53loXyOSR7OgXDtqWWLxpQo0KWHPCKQc+OHunkA6lZPc638bKS7F38D4lXi6UpMhK72qzTKIk94B6G7Hnd3KKst5cRwcsJRryPF6ei/2cS51cnJ9mkExCWwRmosVYIpw8zX1PBm3e6BKvAkRDJAof7fRwmWcL2BGvW2qv3/KV77T1r73B3busv8ndxmu9RZwuJvy5U8TZe5a93Wy+KZ1xKQGB4v/aeyDh17UWBsZDmezKREwFvm/rjTMfj4kasP9x8NYHc7amOV6XShOBUefUubjmMyX+4eCLvCZVNxXs494x5EY40mCX+MS/ixD/mvXicfyQZcb4aQyuNHLzJn1rDh74tVmSWDfbyG95YFlc2QbWuSqMVaw+th/p6VC1mssPGdRrQ7YHgjMcIC9Sdnpos7AUaliPkszXXPmqk4ekzjXba57ZpNJStja0WEOowk43XJyl/A2iEjfKYI036xQ00CuUdWn8LsxBS7YLTlX512hCc2mCaKAY7qhpJVV3XUq7VSPqskKpCn4GinNVnYS/QRx0h3yj/9Boqyz99ZqryT5+NrHxSK9+ZrzWaCGKFRVOPPhn2jBKBZbE9tqqNU8WO53KjU7ULBF+35sJIRUXOZS/wfCdE1Qjkn9ofYw5vQtHqGq5ZAEThxz/gKaRtWZ4+bXwHuC5xaP0aggeoTX+nMWDKvOjpSJ6ZhT041oefXeWmU/7seK1Pvvxal3y1P1anhepYUA0WHN1OlHdNaYnnbFAoigLZ1mW3cvEdtGwUSOhP2TbgsBmUH7Too1II8K8+EJN2i8Y3alZG9hOQbvL12inysiZ5KhvoseCoNIGl8iOxs0yGDxHOs4FsBusQLgeBkiiNE2ibcW2foFJbOJimsldESev+B41GFA16dJopT0lHuZ1/Kec4C0pGfxk2lA4KcthS2FIbtOXxr0EUNBCE4B8pNPGkIA4yXamMmFExANlnIjtEIES1iZ9od4e2pdMnMgWJ0nQIfRv6lqPWFFWROUlsZqtvFNYzdC1WLzL1GsEHVegykUTSw2Cd2o2iWKsF6g4s+cbRoCUl47gMG0pHQjlsUYW+Vlu40NdqQNWQa58ZUujrT9Z1Q1rTXN2UvigidiZJ23Rtpj+yOqxpjbEOewqmZgSs6UsktLFJUkpne4TbVJTtp6AOvSqGrDrOweJu5HCJihybwCkpsGKwS5G0vFoH3sVrmfDsUMXH44mLtk7Oyycb0BP53JCPnjIfnShJRaajhrTjjuP65JVJgLQPAhTcVcCy4CiAJ8eslaFBPqvSwRfTjNYqwrFgEg22Hp2MSVCrfj5iY+vCyLDn0RTcFtEjXYxM1nHlgqBT07SoE67UKtsvPvBQ/sdTqJFofSNgJwwCgel6AWESk3qkExDtoGyqLkoVpcm6W1S4S55r54tqy0Vg+XLrrOMtCNkp9ACj6kg9Ualq71fJNM65uhBhGpZqXRW2jSDEKynyirPc8Vp8bXpZKh92VFiUvXCDJUn2t1bHo411Ow81w4oC9IzP6moydfLzTndILWS1PJlaZO9deary6CBr6G3w6dNXALnMasdyS4Ik8JjbGLjVyshQpIe6AxG0AJ54yVZIOzxjr9zqtShXpOk6Maug4tbyYByjgpRc+qdMNUzxPvAk4BlfFlJ9ikAYQubhI9yaeMIS3LvKUhM+xRYlI2V8/0hhqgwuhl64VxbJ2Tn1eIBAYVFBWtZqUyPe+qxMCx8zIu1uloMlK4Ai5Rqfz8+NjzdX+Y7Xr7d/NfzAN7OxkTx5T2YIxKy+lVpbkpHAbStL4sqsXUHvCvg7Yw9BaLJmrJiyefkgKVLPdZJiOLdJt25INhNUad41XXxmH/LKLxU5rJPv+LVi/1il1lPkJMJ1RZ/gPX2Gubyas2MfLsKvljqubXIc+MqtaAEPuq66qLUsZc5ae4D+Wx+p1QsDl7VPT0CRewcmvybPght+NfYaFH6tbAP74XrF2gIloJhf9mD/msaJ6cIdsF74lqjKmdhGgYfnSvQYwZMwmYXcmj4jcYo7BDDRaiiOhcc5+ISfz47eK1ZWG6X4xpQkO15PmWgSmXZ0r6ysyG58UiemrK1g75VVAtlabHVa6hII2a2iTo51XAy/FNdmdH45juXG3GI7dc2D/YO9VaaF9zWpzJmupywzdV5xJq/KWjcsoHSmTCqf4si7YyZw3UBZ48VH1WQcWA8wURYxvoNqsYcnVXKBoyxKQubxO/xSwgNI/UpWfCw8wTGkpizdYbG3ysTItJRqPaUtkVKU4/AHflHUtTo+OVIXLdm6KJhtx42VZVvcclbpdeSg7GYfv1HWT43UNVLwplGFWuuzNwrVWEdGimidqStZFHZ4Yrw+j+OuCzHBbIAgTp1EXYM90w2CB0cpKb4YCwpP2PUplvtLlQk6nkI1vnPnuOVU9o6xlmlFypI10VMWs7leLN3JwPsK1Y2QYjU1Y1GVUjH2ga83NaGPp0WkG31tdTIagtcWh8DhO0BqvJn4xQ/8F/n+DmWgujHWC4NYRUHXIS6063CMAdR88ZzEeVRKz3WKqJigim4lJSiyy3aUbnZ7ZKwncTSNaEskTUNaEgtSjqTbkpSemnFmSlBVX4mSLDdKqdR0flMaL3ESpZbKTKy6hOc6iaRX0HXuIxC9GOyzKNgSrrPzOXZqs4Vi/xj9wjyLlkson2+WFCLzzEpUeM8/ZMvl09WyUJkKz9HGQlJKfDO9gLVHTkRJGZMZgSd1XJmaUjaUxB5BjApWaVnf9FLphEqm3lW0YUpJnv2MnCrZck2VUrK+SbXGKhV6UlTWO1rMxCpK8ZQVieWkraS/+eyjtIh0qkISppVGj/KVc6Vk+lC68MJq5YlA7CPEOPXUlFl8587yyphh4ArvSBnUknSvmv6UhHK9YPz8WiHiSdfPni2zFIRSUVH0emEs2RmmlaRm42khPJg6vpNEK6E+JvNiQaYQnv2UjPUQ2BzXJ7FlmJdOsCUe5BWU1V9ISkVjpJCRpsHzttIsSrpy4YOSjlwhIxsyxViILE5taldWjPckQwElnmNKhOVkA7+SU9MNaAsqJHQd9jFGQoIKetcNOUVVHqVKRkzH7oPjVzb9ILvX02EdAKPGhjo/FHQOGmrq2LZb5pm6wnLq6DiOFhKWU0enqhdDS8o30yk19llJomrq2LJFuurgZNb8dshFwLcDT8noB60qP9DQUFPHpqDZVhNTSOYGxTFAHMcEyigrZCYnJitk5TqDmUtRVQMUP6SsOxTh+z3cxNxDV0UzIlthJ+kjWVknr4JXwcmq4JVgeftSNmSyI83u052yoMbn9jjMG1i5dNDn4xNlFWulyHF9HlOtWugmGZfZGjIFGqhogEC+n1wuQ1OjI11Al8vOFOgoGUgohVR5R8TEXYzhLjt6KjtC6dGBT8bm4vPnixvyl2gKZ8iZN7e3igkzSVWUKHdHSVJsS3F8G2Y7YP+OxL3ATl14d/Dh7uA7fAIKtJIPV1fZl6+ePdePP5Bvv7+7uzvYJ0n4wTCenp5WseOC+3iFesmo9DC+5Q+tIO464ydfkUVk2WtJlOZfOnb2ObVWud1VDJM0XJVHgG6yj9ntyQBV46udZWXvhbZXE/rj3Z3/6tV32cIPvGg1fhXiCwKj3Nzq/+I/DfzQd0bDqT9mQUrgkNtY8ffX/yy/unjO1pLE6Ke/4fCJoBc8Qht93AI3htW7+UlV5XOLCMfzbMiCaHwL4uQHvJj0f8NzbHjacAtSF6dK9MYu/t+AHBuQ//JJ8u4Ar3hG1MbKiqxivQb654JK0dQq3p88dP9+8Ppgc3n17cvl+eXtX8zN7c+fLq/Nb5+uNgcfDr77EwqCu7tXZIPB93cHx6ujuwP0DfStALcT0Vc/3/54+O7u4E/IJjJKbKJHfODB77t8Pc+joO4qFkXvosZ68rKx0N/o1ULrIJNGD6D/vtsGrg2jSj+P0NozxZMOitjyuerkzWrJDvqVUEAUMXkQ4y9dx3/IvsmSVR6eg+JVzW9i75Rq4zs2TFKe6WCvjZ4rV+86slqPmdYhpcqNFMc+nmvhbx85Ha81BRWZJZkgFvKDc3XYAmFokgLDgfEESRefi67BCvRQtymPkXzIQlO85H00zeokvOSMfGfkZTz9FVko/g0ke/QxjRxsN0ltJ/hQVHNGURPkWmX1l316pacqu4UenvOGqioz0lThqs1QBkB9y2xzSLYInwR32e6oArsdA8w4vbm9QDUZ6dvFSqXpiyNMxA/cYKfaQMf9EJZaC/kZs9k15/kEuz5xxeTlUfq5vvLIbenr4s9i18nW3VrK3XAaJaZJsqZuM9kNLdkaGl0Gs/aeXp+wiWojpTZTWSUS4e9Wrj1Od2xdUxbUk1U2gyNtoyucnhHKzgqo8Wqx2Kvj2Z43PmWlcu/zPW9tHAQY+F9Qb5vxao/AxY83J+urz+tTrtf7KLIRBQGF7syRXwwAt9HJ2tutT0nZWE9jKCKqCwbyMDOoQDBKf4oz97tU25lHDDQBEUpmykm7ZPlRO3KrYDSSiw9k47HkB0fHR9tjlGsc7/QdKdzGhlFxKUO/uGSklsImsLxQNW0pqo6yrNUVQuaayhjv0yi/cUkpZamqkjOxdHDmqso4rfyWNKWURFMZY3E5nFLIQlQdJbJPziJRC1rpqmP1ANKNrcgJkyBSj9ySV0ce5nug1PISUWWUUEOugopzFUxjkB/soxazlFVGuo0jS32+KlWVce5CK1JfUJWqCjkd9cFZiCqlNLO7PXSglsrKePdbHam0VFXI+awD81ktpbNWn5OIpjpGoKFdUoiqoyyPJVTLWcoqI8UrKi3gK0eldJWxuqiNoxy0EFVK+XwP1LfwaGHltPkddRo6o10G1NHD7EIf9dCVrjpWLXWVq7yucnXUVa7qusoDjnsfPCsHpXTVsYZgf69jCIUWVkcbq69giaY6xkf1Q3tEUxljaPnqm9GFqDrKSH2RTzRVMpqxs/OBq4WV1lbGHFsRSKx9mO+dV4pcl1ZHDHWVqTVldbwaxntixeM9MWoEb3fqMUtZlaQ6Bs8rWWWkelp86tt7qZ4GX6q+xadnUFL9mOSjDdSn0EJUGeWTHajP8YWoLKVHlo2pAqT1ZKfjmzP8ahC7ZLXMxnM9yniI9XN7YwDeUiW62sTxLc5VJs11afcORzmRQ+Fzj43qFZ4g71hE6cVObAbZIvHivBsR413vjyJxKCn4nJj4MuJs4TdKXByVUY2KqTUyrAIbmpYL4tjZkjWzwsHVLTE2xKSBejXGhRAkVwWLBEnxzjiLiBvyVK11m9VbY1PCqLwil0PKU67EbEbcVUfbIj7hKeXoEtZtVm8NW+Urz1uLDaORZetwqcBcmUZ8ROaZJQzncrTe1CzGQr01Pl3hPxL47Inabr47Mp3hqQzXjUWt0+/pSGtJELjWHjisBkDP67zNgL5gIdug8u1P3LmwhC7yY0tGoHXWwyQLI0uxsywzjCBZZD2epq3DlYBnaIjeB0HiBvjIW9HGaH2P25iys67AzqQVq1F/1WgrSWVb0UA8v9pcbkTD7xxvxh6V/8XXCTcCPq9k8KJ9x+VpBWf+GRi47J21JUbnu1yKuiduJAylMJol+a24emgUSP11yRBBhYhEaJC3xzNkNbB3cjKOgX57NIMXpiaIvEeOxesdDLW3pyp/e7Is3pm9njW3oyYlbyhmsI3kRF4fHZVBnF17OQ6BellZPPaEtvBWmrafeOAK0zLrM9pVsgel/vpSGw2oXzBmsxS18XWehm/HzltmeiS+GtS7RSuvW06m/dk8jUIZnvgCfuZ5A8rYBNZqy+Rs3g4+b9yY8ZqdxbuCgHQye/QUxpBKwkpu5pq0dRLJuKJEMjU47RNR+PND69Vy9KdTVCZFtM9t4R6QYdEOa+vOzaJVQbPzOrA1mDN083aRj8LIfHSiJAUcW236wxSXiwCPKHSqat2Fykwzsn71ac5dkpCzGmYpQMqTIgQyInmjzH+UglQZUZxZESUcY8QsmkJlaQVAb/jzJ+7C4yJNUwrKwl+aplCZOXPVj9qaJ4vVGfiTdv29IoG31eTHu8ua035BP6EyP4IYIp8uVcrbZ0HCB6d9ql02ESnHPaCqMLwjmIBoBwXKO65ApmUVhix/qcAVpGrmaqoICsMV+r/SgCw1FXKGQeAqju9CUmnK3KnP/JXo0qtlRQm/PkWpJ93zzp+KIArOpmqswPPld/NU3GTpHx544M8I+UvUFD4tIRPtROoBRj4UKEA6eSqRpWdEOgC5kzjxuViwU5dQFwdyPJXIUsfXoWdHj6Kj61xLSnUkFojX+rHjJHOKXtJVvjdzSYfPsJ4h2Oijs3lDD7+ThV3z5dF5CwuNsi5t1cxOCXQ45ji6fKdelqPY84zbdRHshYfmuq2bW5dciziKoXpdjqS4Iloconhz0RM4jYPqcSFk5kd0smt0ymlcmw9LqUoPo6hqrytID6Mgijd1pwfXuR+fHtDLGez51clJtlYGCLiKXja6BJbbnmCHlarNJqiBZe0djl3eGVTeEKheGbHOF7/NMxtdtycw59xlLlv5Brjq7bpV6sWRuzPE/a2/Nc5n3g0RNX+l9kOg9+95NgnULN7zbBDojVfO7Rf1OJXZfYHej4C3TX2uVhBllXprnFnu5ZY1s4JLLLuCmGevSSOAR281IW+LtDQbhkXbmW0ArpUyNbsi62Fa5viOq6vZEzmMrm2Q69SRmj2BM0U6zY0re+svjjMei6bdWCLl8h5BUDcodMBAp9EEcsyJNo2Sl2SMjsyl7ZcXtDuM1LoczWjsEW5BV29IFLCC9sgr48s3MXtQxr+ssBKzV7wyvnwTs0feGF3EiFmLJeKOZFxBg+VLk+6xiaGFCJMX0W4MfaPPyNmM6gqpOA3xUagyK896rwQUijz6chZgWdDF921wzkbl4WjQAWO0fSQ3VhlDlmQPjqCkA893Qrw2gefsLRkfGoYUuIAvlNEfB11WtC4LlBp96wksE/kZBeGLuQeR/QR4qirusCITbV0WZA9fiaKAa/mQAGmpKZ0AC3n1QUkJy1LC7G4LxYSlqCRdIQ4tG2Uy9CfH6KsQabcBRdTxHmjCJcryKbS6xVV9Iq1rKyrONcE2xacsv8XmKllljboqrlgGUwlLxiEqE0zAM6UqhEipSvJZlqeBj1KV5fOApQOQkpWvTfLlUp7a1mKWFJvasqx7cKwhNGlZecL12Rs9jJSwPOXZ8VoPJSUsSbnTkrd3yvI2tH4NwQPUwNhQluRM9hEE+CpKDaQtbaXtG+UVY11bbftGNWxTXE3IPgI35bnfYEzIVtrzHS1Z+N4edsKEduQ8cm6g6RNS0XPPozaJ/J1Eq7jyp9YgLlQVJe7cAvfqYTHWhrhaZP4NNKOgx+yk6cVGDSUyG2zaMIS+DX2L6xQnEfgBI2pcICFT3AeNL79R7kGPDaUOIFG63arJhbYV5U6gksvh3/821om6FaVOANS40IVeaCsFRv0yXbxEWilududDkkoNHQ9C1wwoRbeccM+3D3UMd6WuBjqJgB+HIEK2NTswaEmbM3uuVbbyruyFl+MKOqKlxBmwo80RHSVRvxn1bmiuv4ZNqXEnCME/Uq1VQ6cFpfCao6HXio4Y0FTi9hnR4YKW4qnbhJrxBifBB/B4JyqhW8LLn/ppiCAHhEU6Qzk7CsgHLirP0jiBthknQYS6FBIDPFRw47Ed9NEYsiKaTHrT+jSusCwpcSdfj6CUu5QUzpaiKb43gtqDH8o87JVXOyS0hVlfRGb4cxicNqBxWEgp/oAR9X151eQNbR09TE3IlbrOYR9N8G0rOgfgNDqhdnq6NV6jidxTcllbvfWHd0DhyFRfunQZUIqevIQaCsWmuPourr4g77Wi3gk9gd9pYXmzisX6lvmnFM2KZXRXCzYPvqpryncIKz0zTRyu439EQUthpbSSIwdDvArHC2hZsnJbCzKlrZRZahB5CFjZqDEtqmhkbIhbw7BYU34PfNt1JBYisPhpA0rp5eeuhtDVTlzRyiBJIL59T1eiaeirqfEL8eIKc1XgfeJqqYOY7zxxceRCWT0vubwwSrjumhnL3rSy/JHUgXaPfCgVZ9vVNJXmfhtuHV+iwTzASmsrZZZr4g8Rq+tctZqAOnALYbW5XXpUsoncq640lMtR9GwNlo7gbllQG+6FvJ5wp9XV9kX20How882sWoK9aUAtvUZuTcRyw8CDxOrGgLv6ZzqQKW31fT8dwHvhAx05aBWNsg9xaxhi7+2a6eKnDWjq++lAr6lr6/vpIG/o6+n7aakuKfH5hnnHnrLS/0Ozz4NbkL2dnvbV5nsnss0QROIntWwjCHGvbtwpLVmvUGZMW/jmz84EWN2W2jfegMPToILJKPzO7/4qbgKtCU3ZxxW/b7YzIAqvBi+eZYVFcQFsU0yylCjlvOwCD2V0pdzipn3yM+9lsgfeOQfu3THpoqH0+fx89EqyhtTHm6v8AN6vt38dqdmj7Ae+mVUK4g4zkx8OyhHFQx6HRhERBgpHgw4Ao2I2ChPj1oYx2EHcf2aYOnxiRYsHHrCi/u2v6nwo7WiLB/0+ECsyHoxc0Cf18uhFhI2C4Ap6V8AXP7CtM9b2EIRm/8Ji/kgjVEYlqH2RpZLRcxUtC5AE3sAxocxAJBhGpSN7YkoUIKN+f8+OG4lWkoSyYRhBC+C1wtkguzO8bIcbsV9X9myKR7xyZodCIFSA2VSThPsRmbm5vd7Ig9FKklCuE/evNOQGKlRkjyODcYy6xeZ9ut0OjD1yY7X1ZAHD1AyjIAmG54b4AVt6CgCfIhCGMFKER6tJwhU1jzwYrSQLFQW/okJIQWjRSpJQ/0hhqiCYShnpw7K8cK8gP1Y6skAJsB7MrGWsIOKaapJwGyx3pYitISYdbtn1zqrK15ac7JFNIO6/P4qbqlCRhXE8JYVopaN1BK67NTm6l0ArCHAPNMdGozRVRuNkrZTRGMXbo83npfFo++XrowHq2XU0SEtmNBDOqRIJo3x9PECeN8cTlO9zHZ6v7/5JcjzZuGkP17mPQMSaaxkIxqFzmVthSFANYtUQPn+5aTz2j5HywKUHbARaQgrkKXISSZBSYjTIPYjhm9PxFNX7oxEYOweYCGO2B3QiZP0XWY5SZHxNaElAkJdljJtWGj3K5NK6hgIU04dPKnAKndFIXv/JEkwMT/DIiGZGdXZ+KjAP0sqo5fuSCMNX/nByCF0CNATjBRJRUtdQgGJGQCKhtnVGIwWORLCQl0cbDwfu+GEaD3nu+hky/mDFZxLmi9clii077r8hgaO0Iq9LhICM+5KmJVtXlIAEhGTLihKQgJBsTVAC45MiY4cjOzGO2cbYDWGGgdu/nZWXpFQZ39RLItOO7vt387HbeZTCaIw9vp5AjqMmMb6jvwfH4xmKt2XMr8/eSAGQ92UQzo4F1s91IJD3xyfKwI8TgDfyO55EwdWSGT/YURxaPx6mJjG+HCUrZiUKUkpBGmN4Uz43y4gt+E2gGMiyUArjxzFc1GYdPIGGPY5BS4xvg/umlwosrWy1vcv3JYdS2HumOMdURm6PGuizjQeqi6jos8myEA1VfTYFOIWOIiQU/Y8gdh7lo61LUMlI2WiwhohEtTl4xh5HfSl+iN5QzW06XiiR77u1VKFJF0v9elJDfOUW1qGrd7gG+ZpKkliy2a+poqYHNR6noTJ+atQLEoG57iZH+brEKCw+Ems8QfW+DIJcEUgJjIcIY9Yxo2yOmoYUyvCRrlwkI45w7QDB/Q6RJStdJJWGFEoSAUuiCKlJjO8rANsNLIHVMq2uQiUgMyAmXwU1RKRH52RApLNvMcwoAVEKSPcjVUROl9RosAjfP+4m5h66YgtUm1gdQuOHimLXtOF9upPH6pSSArNcR6ojXteQQvGcWGDDRBdIoSCFgUSPTxS05Lq1FKANngsjgCV++ksD6fns6P34oaTibSnzpoXqXJlpm4aILIzE0BqtIIshsAqxB0NuJWIuEkusz6EVpDAkp/VqEvIg8nFTk1EBJBtLNRmpJkV+J2tRnUiNUbekFICpIFIVRoP31YiEkPitNAMRJ7kmr1NKBRg53r3YaWT6gZmd5tJ/cZQI66C6CvzYDRKeizNFoDs0laCSG1+UIFZaKtCkVki2dVQgbbd2/8HMIkyFkAqowdOiRaDET4fuhxq65E2ESfgqt34kfJO8EqZCSAVUJLOKrK2jpEhQVBrIhRE5fJHULsOHJbInNbrFlFXsUqMpDSGFFbsKrDFHMw6ASc1QdwipgpIeYu/X09AgUoLZoam37aYBuq6uqtWhApToKGt1qGAqhJS1OlRAiZ9L2g8lPwjYI6YETmY+ta2jqpWmAkn4Hi5GK00FUyGkpJUGfDvwJBd+9OupakgqQZOcM6+3AFUQxcqisdmHVkLX1lTZL1eCKHarq8yJkOKHcUltXB4ISyByGk8ReOUxN+QzUHIED4icEXmzxUJUZGFi/1gBDFFRADNyeryLaMREeScW2e4szVTpyALl2zrlgUodWaDUcW3UQtoKnHfZC1XTkgSz0F+uqyK/0UqyUJaCuCMisih7gP5bHyngoZSUQIWB239VgyBWoSUNxnHFiACa0vtExg7ytLBUXb5hjepOtHDUXOqLz9sHyeF61X9OPz9STUsaDMe/Cexf0zgxXbgD1ksx2aiAdFBcB/o2Qj2ZUSt1ueBpeaX4uIGcieeGVON3yCvHj1M8BgYTjS50mFDqRhyP6FEPYxNJpZjZ2ifFnIWmGlCVOVBZdqP2qapgq8vJ4hUbvOXJKCVJqGytqDxRKSONo6ATbSvpRNt7BW1oIiKJAq0x4/FNlkJFHkZFzi9lpHF+HTeC2wb6VXwEtwdpxIxOG0dwOqcbhXEhHT+OstvnRu7naQGJ7+npxNmp6CrvlHSV9w/2Vp6lUJGFKY8BkSeipSSxXE9BBUFEJFGImrLeeltPFnDEOpEWlOASkR6QMxUkZypQoBdEL+TkWBO4bqBgBKFHVBLVR52gOLAe4Jhp3CZiQ0wWzUHdiYcR5xu0sCohSSR8upw0DhGRRMFnzUmjEBFZlBHbM1skKo4yxwfgHQvcoNcPU+goAFJQKpUyCnDeqsF5qwKnON1InohSUgSlqH/fklOFlx1/pA6vkJPFC9yX45MjFWmeUpKFyq5ZhiawLBgrqObaerKAxXFW8miUkiRU5KDawT5+o2BSrSYli6ViXEB4OVAnSnaAoDRLoSIPgw8TVIFDdOSBTpTgnKiBOVPRMqh0ZIFUzBComRPI9s4Da6+gtqtJqcDKJnHj1ElUDNl2KaqADIIHR1XglVoKwBIHd8XUgFVakmDV0ZrSXDUpWSzHU8NU6kgCPaJU6ozZutEkooQkkdRMFyqaICzPKVACVCipgVKQ52glJVCxguFwWklgObD0ZbioVSu7cFZ2KQpCMNStOCF74/IZc5DijTU+vudRYnSpAuzTVQpN5tQf4AvicSJT8KJQNn2vAR1uxC9+4L/IjPr3OkBLL2B5KuZUuzQ1dxprJo6PNwiGQSzXXqPCsltWLTLqzntO4jwqRq7LqkXGuQKVkHgYQqqN0IHdllaDnq82VIJaSalCk5tbq6GpWgZb2xg6dhtvB2FLUTGon8DnJFZdDgzL63FBQyZjm9DjiuIiblhejQtIOJIY6aNoSyU1YLKrUikydatPyeZQ6QkVCk7hnEq55ZGkHCV8NTVFgM5vinJIqaQILIlSS03lWUmpQVPX8Ffcwn8EbqqIrJLS0uvVeF9uDHc79HnUdbnxS5xA79GBTzIbXzcXnz9f3Mh233MV8+b2lv8Un9x3o3LDyFWMuphkasvF+JMZg0pB+qfcU0VViMkOSrtmlCTFEibHt6HANqZexB7VxWbV3p87fuj6qrHZOKyvA8a/fjB+CdzUg7FxA+MgjSz0rzgB8d7wQJKgQNxFEPpGGAWPDh4bNnbQhxFIgsggcsawQSsM1ZrMBAeMesDx1VqtFAfMwm10slZrl5IcMPwRqWQnAAX+n+HL2AiGz8ALXVgt8zBixwX3MQXWNsRN9W3zcXzQCKOV1gb4vhXvnu+B70NXY7h1mRIgy+oejWHXa4+H8cK3guYlFJrwKFMiZJMEXc0YD91Vdl7KJOFGmRIhmyTcasZ46NA/ksAKJsmutC0Rtl+Opwm8pj0hRomqahQjux4r39l0nPyjCW/TfTAQg+wzrqEbx/npBaQsioTgJFFcMyZAd57GSeBNykibFCD9BLcgdZNJUWs2B1h/aJ/UIwAWRxY+L8uI0zAMosT4ofO8nm6To0OjxyjT0xfUxrsNfmp0BGUM1xT5TKvzuqE5YP78p8tvX4LdrrnqSMK6m8sZDekBiFv4nFz77kvxtLKAKFA6DQwAbbIsdN6ekBNkaebJpi4vglSADEKwQkJJlDQJeKMBp6DzbOzz28cvUv08TJGPohrdoowy6eRd3gyXSQwxTNLQDMGLGwDbaKryAkgFwQACKxSuE3DrPqKHcdDJjQd0JQkPVUjOYZAAo8eQIJrS9DoMxwq5m4uPn64uVp6tbvSGkqwZJpMG30CyV2RKrYGisaJHtRlvaq2ghKFcsJjlUSv822+/mSQCoY3HNQ/zZRZqrdCD4r4L4hiiCjeCYaDHqbo5JxA1RQ/ql+nkPggSXBRCnnReUyB9T+PeTWGCVPbkeJ+xJJ/go2NBXDc7SOgLLnUufrw5WV99Xp8al3Je5rGPw2qswvnV5nJjnAcRlGXJlW5urzdrWSmU4LIws7OgMx3fSWR8hJ4dPSoIK+jhFqi4QGumaYvSfZQE+NC+2IlHhla/6gOMfOiOzEFMWdz8xkt+jc/n58bHmyvz/OrkxPx6+1fDD3wzhlYaSUd8dklqlIbFEdGRTLQNihog8qSFgziJIPDkIFG4OXgW0s3XnvnQT/CH4jyNouMjVxgJmkGlIUQtS+3WFOSpxuoKVXLkXHDZJELO1lCYmhuKfG2YgeLRf/ROtCRgvGM4X0elQR6qCVKGtnjgci8ukKz5UQPFtfbAkarXiiSVw3UoecCKgk9wiyti1Ie4q3XjzfPrrz9efjY3P31cn73Bn24v/ufW3Fz+9SLrFmVrm9Cz6Ecx2Zu/fLu9Nr99+Xj74/XNVU3rWEjpy/Vn88fLL7cXN5dfP0voFCiFx5dfz7/8/Knu5f9xk/9sdjLxy9/Id8UI0R+FLG/+srm9KO3+vLkwN9fnf7643Yzz5vr2o3nxNQvgy+uv6J8ff/hyMU5qc/nl4w8b89vN9S+XGyyG/nV7fX79xfzluKZ4xK34hVI7/+nj168XXwjip5GMtOLni68XNx9vr2/GaZVN949Hx0c/Hh+tTy+vTt8JkHz89g3TfLu4ub282PC+mFfHX3++Mjef/mze/oSHCVC6Pv/4xdwgXz5+vjC/XV+inHdTTxJrAbLz66tv118vvt6a5x9vP+JM8+3mYoM+cydV3AMwv/5yeW7+cnlz+/PHL+PfNH9CHl7c4HzbyGD/SIPkP7OGs+mjYst8dKIkBe5qn//Ca/Lqh4tPt182RZ5q20EZmWqpWKL5FgXo1cXV9c1fUMSg3PDl8vNP3AFZsH3bfCyKwSHM2h1qgpg3t7dZefJxczUyu5br98zNxTkuTzqiq3pILJKyVPnpgk6a1zf1AMC3xjXkSJvtx/rSwMS2/vCHwSf52ki4D4j+j/+dd312lrUCPAjoQZ7HuB5qdlo6H/IDVKU3HsQthuuQBDP+cGmjJ6tvV6m1wo0gJBRlAR1kXw88tcJPeM5v2UKqWtzgRer6zVvPz/gyO98GkV1PGn/4w/HbEfbLRtUwQPnYygrTZppM4POhd3IyhfVtw/o2fDw7jJsj13pMuwFITHDv1AD2WUTojnbUNS37eu2VrvilL06clEbLNOniDGtWb7emIIzKoKgLeKzUu2f6UD62SCdcx39geZA/Q/7aWJETJrUk8G9hFPwKrcTAe8R30DfyJ/Go8MqdIHFsU9/CX+LxKPx3XKNLonSCcskGCVBqXyBifOCjxoCJaoU5PA88JzG3EaqEzDDIht1mgPDxxjwLhnNFP7IfJYkzccQXs0NXIMzaAtP7bfVUxsfNXpIG208g8h1/F6+A687gemk+2xE6J0AIbeAnjlVvGAA3nhICRNDMDjiPR2J44AFmVQaIvBVuZicg2sGkydHzWKtZduihb74XbJxJMiT71LtvUJDv9BtvtgwPPfTN96R9eGgfNwfk9EB0thERCv7+EH3/PXd7sWWiKnSYNNWjfSXUIeoifs9bTA3ok/UpfDB4a1Jf/yUH4u7EKEbqqr8Ot35wmH87C1BPhZ5h0b9Nl5aKws5s1jiH/519M20w6aUZFS7tqvDwv8l3M4WNNiKR8OkdMzm8lk6/oiGjk0UkTPo7TIdb/Nth9du0ATQZmEhoDXdxD7fF77OF2uSAQvlvuIt6uMUPHGYPHJYPTJwtp0cUCcFlDF0pDO+FOtQ7ptj/5FJd6R7H6Hmsf3Bx/JiiJFE2qtYaUztEnSloxd/jX1fZP6dgKQZ6zPyz6YGwTvU/RO/u1eEVCL//t3+//vn228+35qfLm/8w/u3fv91c/9fF+e3Xj1cX/7HKXpYpOlrUTmwJJb3D/0ZN+NRPY2gfhgCXaa3ijCnhWV5zYIH5DiPumO83V+KNyyD7IE6WF56sdC3kK/Jsla+HWTmoYImdk3XusZ2s8nVWdnZsaDa7tNr56Yoqnu9BDJtBQgk2ns4fWuEwWwXJHkYucu//i9TYedrQwPNbD8YxCvpDF/q7ZP99c9Zfdwzjnr1IHNPP/28szxLL+fKILIbJHF8z0siq/SCsdyazc2m83foUHB0fbfHKKcdrrZzqtumAaAWfwqzW6SshLy9wF/66GAESio92HIqFCebDbPgLsiKgSKWPZ6vT1XETduAFkqyBbWdrYYD7cwyjedzibaGI103u68PDpwi1Sky8u8DMGinUl152+WDra6v76wgW34tli0xiZ/V0P/leRwUIHlc6jJ6ekc7Og34iVUu2WwT/UmGuv0lAWr9cDQL8bJGfXHvrgp1gDlpQOlWd0MZV1gKhT54uwv9/Q3+wZO3v5Atn9Gf0oZQ7fHKS/WF7H/NC8qmonOVEVuqCyIYh9G3oWy/jJtmX45GPynm7NaTAP0Uuk48VuFGVCQJR851BWo7Zp1ff/enZc/Gj+T1C6OHj1VH2MsQHGDj+Dn318+2Ph6ix+KdcoGh5litdU2vlBXaKclR2EMLqPNse8y1/7BsK4x8y8HLz+ypbi4veR0ohjJKXjYX+/h5f5UjatHTQh0gg83yTwPCPCL/2eSKX7Pxsnw1Mkmx1hYAvhj4qmSDWiJVaBGxslDdPGSZjjl1Fcf1MiJUVWcUyfCvKLZKrL8psgL4qd/F3F1v0qaz1tHXw+mBzefXty+X55e1fzM3tz58ur6kNJQcfDv55d0Ad8vDhDn1xh/pt4BGi9BpYD7+AyMEbeGP89Qf8B34A/w+VAKGDnrIfvgRWPh1IfvhQ/GMHrYfAjO0H8xR1bI6Kr18X/8C73a7D9ns9vT/y6+/5H0jmgBxhpRw8drzQdSwnecno14hg9Ua5A7+j6MlZ8Oq7GMXG36rogDbSw5H9ukx02eY87CrZb4t3nOQbO6uLPtDTQeTsHNQXJI/7qeu+Lm9wQ18cv84UEtQuQZ/ev3v/7uT92dGb31+LGqd23Ju2ZVsyGIdnZ2cnb96/fS/KAcLQJJnUgbEMwumb0zdnb9+vT8RDornxZ0wAHL85efv27O3bN+vx9kmMSGEcn6D08FYgIooZlkaKsFAD+iHG04QjIE7Xb85Oj8+OxoRFba+zVFis12frk7fvzt6KU7TODzDjtQzL27P10em7s/WZOAre9CQXDMfr9ZvTdydvxuSMemxEcIcn+SVojhHH+9Oz47NT0fR5c3thnhc7tuORuWO9Xp+eHK/fClunt4ujbmcC3GBsDn1/cvz2/dH799zJsmJwGkWVSX4aR4KKCVS/veVOFjRHtg9RnuHs/Zs3pydH70czVHe6SbO8f392cvwOZVNRlsbctHieeHtydPrm+P07YcutBqi47eOz98dnb06ORsSACR9xbtgD3yYrSkbkhqNT1L46Ojt+9/vfD37/f5LOJj8==END_SIMPLICITY_STUDIO_METADATA
