set(SDK_PATH "/Volumes/Resources/stash/matter/green/third_party/silabs/simplicity_sdk")
set(COPIED_SDK_PATH "simplicity_sdk_2024.6.0")

add_library(slc_generator OBJECT
    "${SDK_PATH}/../../../examples/platform/silabs/provision/AttestationKeyMbed.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionChannelRTT.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionEncoder.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionManager.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionProtocolV1.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionProtocolV2.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionStorage.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionStorageCustom.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionStorageFlash.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/syscalls_stubs.cpp"
    "${SDK_PATH}/../../../src/lib/support/Base64.cpp"
    "${SDK_PATH}/../../../src/lib/support/BytesToHex.cpp"
    "${SDK_PATH}/../../../src/lib/support/logging/TextOnlyLogging.cpp"
    "${SDK_PATH}/../../../src/platform/silabs/Logging.cpp"
    "${SDK_PATH}/../../../src/platform/silabs/SilabsConfig.cpp"
    "${SDK_PATH}/../../../src/platform/silabs/SiWx917/CHIPCryptoPALTinyCrypt.cpp"
    "${SDK_PATH}/../../../src/setup_payload/Base38Encode.cpp"
    "${SDK_PATH}/../../mbedtls/repo/library/aes.c"
    "${SDK_PATH}/../../mbedtls/repo/library/asn1parse.c"
    "${SDK_PATH}/../../mbedtls/repo/library/asn1write.c"
    "${SDK_PATH}/../../mbedtls/repo/library/base64.c"
    "${SDK_PATH}/../../mbedtls/repo/library/bignum.c"
    "${SDK_PATH}/../../mbedtls/repo/library/ccm.c"
    "${SDK_PATH}/../../mbedtls/repo/library/cipher.c"
    "${SDK_PATH}/../../mbedtls/repo/library/cipher_wrap.c"
    "${SDK_PATH}/../../mbedtls/repo/library/constant_time.c"
    "${SDK_PATH}/../../mbedtls/repo/library/ctr_drbg.c"
    "${SDK_PATH}/../../mbedtls/repo/library/ecdh.c"
    "${SDK_PATH}/../../mbedtls/repo/library/ecdsa.c"
    "${SDK_PATH}/../../mbedtls/repo/library/ecp.c"
    "${SDK_PATH}/../../mbedtls/repo/library/ecp_curves.c"
    "${SDK_PATH}/../../mbedtls/repo/library/entropy.c"
    "${SDK_PATH}/../../mbedtls/repo/library/hkdf.c"
    "${SDK_PATH}/../../mbedtls/repo/library/hmac_drbg.c"
    "${SDK_PATH}/../../mbedtls/repo/library/md.c"
    "${SDK_PATH}/../../mbedtls/repo/library/pem.c"
    "${SDK_PATH}/../../mbedtls/repo/library/pkcs5.c"
    "${SDK_PATH}/../../mbedtls/repo/library/platform.c"
    "${SDK_PATH}/../../mbedtls/repo/library/sha256.c"
    "${SDK_PATH}/../../mbedtls/repo/library/sha512.c"
    "${SDK_PATH}/../../mbedtls/repo/library/x509.c"
    "${SDK_PATH}/../../mbedtls/repo/library/x509_create.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/ecc.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/ecc_dh.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/ecc_dsa.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/error.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/oid.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/pk.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/pk_wrap.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/pkparse.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/pkwrite.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/platform_util.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/x509_crt.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/x509write_csr.c"
    "${SDK_PATH}/../matter_support/matter/si91x/siwx917/BRD4338A/support/src/startup_common_RS1xxxx.c"
    "${SDK_PATH}/../wifi_sdk/components/board/silabs/src/rsi_board.c"
    "${SDK_PATH}/../wifi_sdk/components/common/src/sl_utility.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/iPMU_prog/iPMU_dotc/ipmu_apis.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/iPMU_prog/iPMU_dotc/rsi_system_config_917.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/rsi_deepsleep_soc.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/rsi_ps_ram_func.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/startup_si91x.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/system_si91x.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/common/src/rsi_debug.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/common/src/sl_si91x_stack_object_declare.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/config/src/rsi_nvic_priorities_config.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver/UDMA.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver/USART.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/clock_update.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_crc.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_egpio.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_udma.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_udma_wrapper.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_usart.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/service/nvm3/src/sl_si91x_common_flash_intf.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/service/nvm3/src/sl_si91x_nvm3_hal_flash.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_ipmu.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_pll.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_temp_sensor.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_ulpss_clk.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/rsi_hal_mcu_m4_ram.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/rsi_hal_mcu_m4_rom.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sl_platform.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sl_platform_wireless.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sl_si91x_bus.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sl_si91x_timer.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sli_siwx917_soc.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/errno/src/sl_si91x_errno.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/firmware_upgrade/firmware_upgradation.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/host_mcu/si91x/siwx917_soc_ncp_host.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/icmp/sl_net_ping.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/memory/malloc_buffers.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/sl_net/src/sl_net_rsi_utility.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/sl_net/src/sl_net_si91x_integration_handler.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/sl_net/src/sl_si91x_net_credentials.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/sl_net/src/sl_si91x_net_internal_stack.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/src/sl_rsi_utility.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/src/sl_si91x_callback_framework.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/src/sl_si91x_driver.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/threading/sli_si91x_multithreaded.c"
    "${SDK_PATH}/../wifi_sdk/components/protocol/wifi/si91x/sl_wifi.c"
    "${SDK_PATH}/../wifi_sdk/components/protocol/wifi/src/sl_wifi_callback_framework.c"
    "${SDK_PATH}/../wifi_sdk/components/service/network_manager/si91x/sl_net_si91x.c"
    "${SDK_PATH}/../wifi_sdk/components/service/network_manager/src/sl_net.c"
    "${SDK_PATH}/../wifi_sdk/components/service/network_manager/src/sl_net_basic_certificate_store.c"
    "${SDK_PATH}/../wifi_sdk/components/service/network_manager/src/sl_net_basic_credentials.c"
    "${SDK_PATH}/../wifi_sdk/components/service/network_manager/src/sl_net_basic_profiles.c"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Source/os_systick.c"
    "${SDK_PATH}/platform/common/src/sl_assert.c"
    "${SDK_PATH}/platform/common/src/sl_core_cortexm.c"
    "${SDK_PATH}/platform/common/src/sl_slist.c"
    "${SDK_PATH}/platform/common/src/sl_string.c"
    "${SDK_PATH}/platform/common/src/sli_cmsis_os2_ext_task_register.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_default_common_linker.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_lock.c"
    "${SDK_PATH}/platform/emlib/src/em_core.c"
    "${SDK_PATH}/platform/service/device_init/src/sl_device_init_nvic.c"
    "${SDK_PATH}/platform/service/iostream/src/sl_iostream.c"
    "${SDK_PATH}/platform/service/iostream/src/sl_iostream_rtt.c"
    "${SDK_PATH}/platform/service/system/src/sl_system_init.c"
    "${SDK_PATH}/platform/service/system/src/sl_system_kernel.c"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Source/cmsis_os2.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/croutine.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/event_groups.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/list.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM4F/port.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/MemMang/heap_3.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/queue.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/stream_buffer.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/tasks.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/timers.c"
    "${SDK_PATH}/util/third_party/segger/systemview/SEGGER/SEGGER_RTT.c"
    "../../../generator/app.cpp"
    "../../../generator/main.cpp"
    "../../../generator/si917.cpp"
    "../autogen/sl_event_handler.c"
    "../autogen/sl_iostream_handles.c"
)

target_include_directories(slc_generator PUBLIC
   "../config"
   "../autogen"
   "../../../generator"
    "${SDK_PATH}/../../../examples"
    "${SDK_PATH}/../../../examples/platform/silabs"
    "${SDK_PATH}/../../../src"
    "${SDK_PATH}/../../../src/platform/silabs/SiWx917"
    "${SDK_PATH}/../../../src/include"
    "${SDK_PATH}/../../../zzz_generated/app-common"
    "${SDK_PATH}/../../nlassert/repo/include"
    "${SDK_PATH}/../../nlio/repo/include"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/inc"
    "${SDK_PATH}/../../mbedtls/repo/library"
    "${SDK_PATH}/../../mbedtls/repo/include"
    "${SDK_PATH}/../../../src/lib/support"
    "${SDK_PATH}/../../../src/platform/silabs"
    "${SDK_PATH}/../matter_support/matter/si91x/siwx917/BRD4338A/support/inc"
    "${SDK_PATH}/../wifi_sdk/components/service/bsd_socket/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver/CMSIS/Driver/Include"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver"
    "${SDK_PATH}/../wifi_sdk/components/service/network_manager/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/rom_driver/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/inc"
    "${SDK_PATH}/../wifi_sdk/components/board/silabs/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/config"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/common/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/service/nvm3/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/errno/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/icmp"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/firmware_upgrade"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/sl_net/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/inc"
    "${SDK_PATH}/../wifi_sdk/components/protocol/wifi/inc"
    "${SDK_PATH}/../wifi_sdk/resources/certificates"
    "${SDK_PATH}/../wifi_sdk/resources/html"
    "${SDK_PATH}/../wifi_sdk/resources/other"
    "${SDK_PATH}/../wifi_sdk/components/common/inc"
    "${SDK_PATH}/platform/common/inc"
    "${SDK_PATH}/platform/CMSIS/Core/Include"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Include"
    "${SDK_PATH}/platform/service/device_init/inc"
    "${SDK_PATH}/platform/emdrv/common/inc"
    "${SDK_PATH}/platform/emlib/inc"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Include"
    "${SDK_PATH}/util/third_party/freertos/kernel/include"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM4F"
    "${SDK_PATH}/platform/service/iostream/inc"
    "${SDK_PATH}/platform/emdrv/nvm3/inc"
    "${SDK_PATH}/util/third_party/segger/systemview/SEGGER"
    "${SDK_PATH}/platform/service/system/inc"
)

target_compile_definitions(slc_generator PUBLIC
    CHIP_SYSTEM_CONFIG_USE_SOCKETS=1
    DEBUG_EFM=1
    MBEDTLS_CONFIG_FILE="siwx917-chip-tinycrypt-config.h"
    NVM3_LOCK_OVERRIDE=1
    OPTIMIZE_TINYCRYPT_ASM=1
    SILABS_PROVISION_PROTOCOL_V1=0
    SL_MBEDTLS_USE_TINYCRYPT=1
    SL_PROVISION_CHANNEL_ENABLED=1
    SL_PROVISION_GENERATOR=1
    TINYCRYPT_PRIMITIVES=1
    SIWG917M111MGTBA=1
    SLI_SI917=1
    SLI_SI917B0=1
    SLI_SI91X_MCU_ENABLE_FLASH_BASED_EXECUTION=1
    SLI_SI91X_MCU_EXTERNAL_LDO_FOR_PSRAM=1
    SLI_SI91X_MCU_COMMON_FLASH_MODE=1
    SLI_SI91X_MCU_CONFIG_RADIO_BOARD_BASE_VER=1
    SLI_SI91X_MCU_CONFIG_RADIO_BOARD_VER2=1
    SL_BOARD_NAME="BRD4002A"
    SL_BOARD_REV="A07"
    SL_NET_COMPONENT_INCLUDED=1
    __STATIC_INLINE=static inline
    CLOCK_ROMDRIVER_PRESENT=1
    ULPSS_CLOCK_ROMDRIVER_PRESENT=1
    SL_SI91X_BOARD_INIT=1
    SRAM_BASE=0x0cUL
    SRAM_SIZE=0x2fc00UL
    SLI_SI91X_MCU_ENABLE_IPMU_APIS=1
    CRC_ROMDRIVER_PRESENT=1
    SL_SI91X_SI917_RAM_MEM_CONFIG=1
    DEBUG_ENABLE=1
    DEBUG_UART=1
    ENABLE_DEBUG_MODULE=1
    FLASH_PAGE_SIZE=4096
    SLI_SI91X_OFFLOAD_NETWORK_STACK=1
    SI917=1
    SLI_SI91X_ENABLE_OS=1
    SLI_SI91X_MCU_INTERFACE=1
    TA_DEEP_SLEEP_COMMON_FLASH=1
    PLL_ROMDRIVER_PRESENT=1
    SL_WIFI_COMPONENT_INCLUDED=1
    configNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2
    SL_COMPONENT_CATALOG_PRESENT=1
    RTT_USE_ASM=0
    SEGGER_RTT_SECTION="SEGGER_RTT"
    SL_CODE_COMPONENT_CORE=core
)

target_link_libraries(slc_generator PUBLIC
    "-Wl,--start-group"
    "gcc"
    "nosys"
    "stdc++"
    "c"
    "m"
   "${SDK_PATH}/platform/emdrv/nvm3/lib/libnvm3_CM4_gcc.a"
    "-Wl,--end-group"
)
target_compile_options(slc_generator PUBLIC
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:C>:-mthumb>
    $<$<COMPILE_LANGUAGE:C>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:C>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:C>:-Wall>
    $<$<COMPILE_LANGUAGE:C>:-Wextra>
    $<$<COMPILE_LANGUAGE:C>:-Og>
    $<$<COMPILE_LANGUAGE:C>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:C>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:C>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:C>:-Wno-unused-parameter>
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:C>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:C>:-g>
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:CXX>:-mthumb>
    $<$<COMPILE_LANGUAGE:CXX>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:CXX>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-exceptions>
    $<$<COMPILE_LANGUAGE:CXX>:-Wall>
    $<$<COMPILE_LANGUAGE:CXX>:-Wextra>
    $<$<COMPILE_LANGUAGE:CXX>:-Og>
    $<$<COMPILE_LANGUAGE:CXX>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:CXX>:-Wno-unused-parameter>
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:CXX>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:CXX>:-g>
    $<$<COMPILE_LANGUAGE:ASM>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:ASM>:-mthumb>
    $<$<COMPILE_LANGUAGE:ASM>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:ASM>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:ASM>:-x assembler-with-cpp>
)
set_property(TARGET slc_generator PROPERTY C_STANDARD 17)
set_property(TARGET slc_generator PROPERTY CXX_STANDARD 17)
set_property(TARGET slc_generator PROPERTY CXX_EXTENSIONS OFF)

target_link_options(slc_generator INTERFACE
    -mcpu=cortex-m4
    -mthumb
    -mfpu=fpv4-sp-d16
    -mfloat-abi=softfp
    -T${CMAKE_CURRENT_LIST_DIR}/../autogen/linkerfile_SoC.ld
    --specs=nano.specs
    -Xlinker -Map=$<TARGET_FILE_DIR:generator>/generator.map
    -u _printf_float
    -Wl,--gc-sections
    -Wl,--no-warn-rwx-segments
)

# BEGIN_SIMPLICITY_STUDIO_METADATA=eJztfQtz3DaW7l9Jqba2du+0mpbs2I5vMlNyq+1oR7JU6nYyuestFptEd3PFV/hQS5ma/34B8NEkCJIgCRDQ7GZ2ZYkkzvm+gzdwcPD3k7v72/9YLtb6/e3t+uTDyd+/ndwvry/WV78s9fKrbycfvp3M599O/nEyK9Ksbr/eL5YrmOzHvzy5znePIIxs3/vp28nZ/NW3k++AZ/qW7e3gg6/rT6fvv5385c/fvB+D0P9vYMbfwSRe9MH1LeDAL/ZxHHzQtMPhMI9sx9hEc9N3tSjSVnFi2f4cmH4IoFCYOgBh/Lwy4b8wXSbt2wkU/d13P259xwLhd57hopem723tXfYOvbUdkL9bLT9/Xt7r9+u1voCfzfdQeBLa8A366oP2i+8kLoi0exD5SWjC36LYiPaaa8QxCLVdCICnQe2PNiKtRUkQ+GGsRfYPZ++0VLFG0aHRsESO7oFYt8DWSJxYfzScBERCEDVqouL6BEXer29XC5xYCKC6CiqS+/VSvwSPtgl0mFgIkrqKprza+EZo6WmyJDRiKFJUZjWo6kQWh74jHFOuhIomsL0MtxAcVfFN9kCNhkgUdRVUJN6j+7qocwLhNOhpsg5K+6RDNeYD/P0P0ZZqUUdFCFzH3qT2tcAm2YmE16IrxfajlnYttG7GSGJ/Bzx6P+PY3gMI0RN95S/mjsUTfaZZoyhpbEYXvhv4HvBizj1MjqWuo7l2Zl/pphEbjs85a3NATZqaYIFH9OHe8CwHhMIg1bSwwTEngWM2w7H9KA6B4WbfCipEDYqYQYkyE01RJyjbs2P4A2r0zCkMVtdHhTg3QzNv5+CvIlDVVHQ3pgc7gmN9z4OD+td6ZD3or+ev0XSiYECM8POGpvii9o2FB3Wl97Uv0hlH5QvKN7D3Ij6pfeSaSe0TCuYQUL6qf7e3A+p3dWzItNQPa5/adzdfdZhtu8YE9CSWHzfrSBOVihacCOrRcxQDN8t9PKQeVMTivQ1Hm4EB53xamk/awd7aqGhox9zX0kzOv8CZpcHc0JCxNWRJDRpJK9hrBSmtEavGytYO3EQ3AntgsyOcYQVfM6tKrez/utL6pfbEIBUwCgmnyQZVDjFUngTqkCDxMLFApTuI9BB2C9vEMxXgQUHEzMQCIIgc+EOPfFW41DDR2bRWH7LF9drac8ImIAz9gcNUbraAgLUKFqYc3RgR0OPnYOiYiCv8Khgm/BacSyiDvwqGCf/96uwJ/qcA+BIS5rbANAM0r3OHLr5xL/xVQINaZzWIEIiYmVRGUYpwqWFiYgNTpCoUYFHBwopemYpRwcKK3ogiEMZqoD9i6VOjlaoDFTxsY9/ygFk+CRIOGwe83KxMNSbh9ODgPgbKEMiw9B7jtr1q3bRt/bZ94YOolh5kCafGth/asQ2KOiFvFpHtjGTziGZ4gyYUlNFSAlsy+S1TyroBUwNVxqxUgVQzNBq3PtUC9aICqgXe75JZCxCv0mw6Q8PWPlZ3Ff0N8gWBMkzHCIESnDoRTrxakNpXYkXBlslHJgUafv1J8wtiVyC0kcMS00K8G9mRniZgq4CLm9XVinVJ/rJNMOX7K890Eou+hXBMUsr3VAHalJU1J8iMrZUtqWEjaSk4LSOl1bAyr8LnKS++vBCKKdC+/Jbrn18GvwzoAH76zcXixXDMwQ7heffzby+HZwa2L89PDkT/MlgWUPtyvDp/IeU1A9qX383i6mXwy4D25ffl4svlyyCYI+3LcHXxQnIwA9qb391L4Xc3iN/X1cX9+mUwLKD25/jxpTD8OJDfC2llcqQDGL6QwWmOVIw3DPvSnKJTM8ZZWIXKUqlR+7J1WF4B/lmpzuNzaw9RAa7UsLN1aFmBrdRosnXEWIEN5z/69cWX9+/enF+og59ExUBEqbFg63ivClulWspeSb9e3ihUXHI0LMDVGnJ2DCsJ6AqNJFtHi/WiImPTormoNG9Q1IuKOshzOON23ELf7bXo32sfBgk3nQc5noO51Y4Mix2ZMi5mhxecKJTjvtbFJeznw4bSgF1g+yqSKYCxuyIZ5oPtydnwayFTgtWvkMlxCusqY/3cw3BObpNIjldSVxHLgfWis7VdFclksHpR2QWWa6hIpgDWi07gH+BEPjIelSxtVXT9iB2ULHIZrF5Ufo8CW0UuOa5eZEL1epsSrF5UYmPjAF3mKYkOUjWAA+jJ8/FlItfP57dIa7tDj+4LJpUD60UnUbRLSob0SCiRfgiNIFAzi0h8/cg5QRShCZSSzMrgBHpwQ8PZwR6EhpOhoHvZDXdbNR3ffNCTwDJiOV6euaHrTLHTJ4mP/UxbKOdUawefEjRmKulcVVEyBThmOripU5RNjq0XmaKJU5hUGSM7uQiiUpZVDm5Ct+9KaySzW6LYBXVPJL5eraWCfErQeraWipLpt+xoJE96CLYgBJ4J9Ed/ZMg7sfRawTLnnmEpWxAzaD1O1ctdimirU2a/1Qik1QiNWFJ0DBZGFYTsxOSugrcR6rcSbg6NQTgFk35bYJahbBOQQWPvi6TvTbT1Rb33J4C3R3HwLOmbFG2sCIzM5BTm1JeK/I2XFjL9N192shf129j0Xdi3z5Vt3TJoPago2+dk0NipKDuwsfsNaPzAcOWEuGDgUoBjd7qQvDXZQqbv9uTvQNlGLIPGTkXhBrn3TitKgMJ8xsouGlQRsm+iSN4+bmHUewtZ5QFN2HtAE1m2L/cgbwudAlwPOi5QtpkuwLHTUXf5MOrpsxi5trrlLMPGTkbdTqdvnxOpzKU3mecojJWd1BzR9SSk74FhQUlqEyujZCaIXWeUJXZE129LWVE6vT17lPHq6SA1yLMn3bVVlVUOjpnOo2GpSiaDxkzlkIRynRdbuOTY+kWyc9/ogZKtXB2hQBeyCIS1S1saP0bXnrEGW2vzMWvKkjRonb5F4YF024u3Ur1LMtPgy96qIQapOFsiHFDJ4jvk9jDvsRhFmdZBNlayrltLmH1q2EuHzMpbsVml2lJxDjIbnxqOYzo74BE4Ao5Xbny5XVyJXdEfZJjYt5QjBfzYaUTKwNg3KwI3UY5JDop9ad8ZeK2qQBIZJnYOCmZE73xQ41gblcqwM21B6EOskQ+TAi+S7LNE5UUByL4WDnbSl8JopEq4enCJob7Blz4LZVNCxs5H8joYlUnP1S8oIFC14hDYei146WgypuBYhsDGvpKixPkoGiOGw1G09YeDJXdhiEYlBzX+jEGviwTwYErqfLFki/zARQ6q1whPNRIZpkGtoWpcCGwDWg7VGFWQCb/IoOkxeYtyCBw4Wuu+jdgFrh8+N1yDUMoD13Ac39Q3yXaLNjqmzoSckJbi1epw6pZnvQoChKHns1wE0dwc0peGsGB5psLqqwtnBaJxobGa12KqV7lhbVN3jwR/fI9bDqQXbdbyA63rgVhEAYJi0VIdCD3DSW+QkVeaUpbEOiwVH0PEuFSYjpvP2Hbs+FkVYhRY7HxSqyCL7EIDTcT0veFZjoRTti3sWkGycT3mvhkCC805DUdin9BUNAlwk7R5lCIkrQHM7JJtA1Bg8SjZCrFrBdmTq3K8hHVftukG3eO/DEqAwvZJq+gIqkYgodqkCbm0TK0hp+Yma5Zt7dA9GCHQkwCW9Ia7wCpGIFLg2iEvH0n85IMCXmfmUhNKy2U2XqOyvmkISe+i03mrxJ653CUfwbDUWTXGhil+hgFhg3MAnKZu0MWP2xC+OfihzAF8xVeECmx4sYz3ITAs2LCxFE479yRKnNhOUwJLnmEK7FoLtOGm2ftRrLtmwjRBRMqZhpn24emHs3d65Ju6ZwY6UiLPgjnF7HkTOCHDF2O/SeegW6PBYWzYJBzVeeRiBGkhlzdYTeTZt8KxWHiso2Mb4waOEW/9UCk+BKx+RPRcsKKMKvj6zLA3iWqUKriYqKAWtWgO1GJTg8ZAiKx4vlLViI6uT5FLPbsUolRHNsk6ThafR8a1XA3GKEUNYr+VKw0AExt6/ByA6f3KO6hUkbHSSacRqlEpUDHScN+oRiFFxAjfV64w+X0KUfAAB6w7d3rnjQ4SZVyMVJJIvdqQY2KkcLAjgLqsvRFaeLkkAnEyfUSQDlLNKFlpOoaX++FLionYRZGKsA89C2xtT72ehsQ2YOiqECMKtJ6E5JwsYKTUcbqAHLimmtQiUwIlZtOmYRTbtooqb/PDq62iNtml4YiVB5F5EqJFkhQoePrQQBsB2AC2zBaS4EKCYickeyReIdI+AKcTwOuWRdVVhEgdFDsh249Rh/AAJA5sK2SqgNiJ4MhRpu/InrdWyNRBsRNC4bBUa8dqmHrQiY04UYZHAYadgErlqldxwqpkD3ky+AQW5j0y6mPKw9qj+oPuuAFktAAQo+1O3TU8Y1e725Vhr4jmXLIxItuczBmuOORdpVJ28qMCIvOnmQls6dA7RWiU0bBzMEEYQ62mEcOZegyHOWqQocJiYCUZfR0lvRKz7Gc3O91J4ZjuWRMw+nOlTcloTKcZBTSxLbkVtnb9NOSWJx1zBoEFrR1M0MkzQC7jYMGtBOheiLEOJWBXkbC0qnIB11GyjIJqTc8msrJZVvtwprOJgpCszSQ2OULG5igUt+YZ/MpOz5xIwljSzgL0Lfz2rUSohf72mgDH9ILvlGmAedTcDlD8ikYTwMaliyrA52laPhLdc3czlwgODNwALaEF/eUxw9v4Rmi1ze9SrCOndWm8JqhJ6IgUayhm2GEeJipTK2AEepQvskhUaB2jX2VqW0tr8WW2+5iE4j36m+HWQXSNKNBNeTIsXFPdBdQ+NyXhrGjughkcXEkwK5q7YEbScj3qk+lZ9GVJSAnl/LuGfHm+rXdAaMcv+WHOE5/tyNnhl/nCTAsQUYs1SOWURPPVmVyvmIWZJkOKrCVVouUldTqQruqdJp1kdakFep9FJZxiwk3YZtjdm65U7OIXPZohMy9z4JojBaOYdj71T2udA9TacNImU5wsTHHmTXXD+cHuxZ1680WSMSzLRiPUNAiH6H3ZjFaWzVTdWitc043saBKvpCrUmt4OmJO0pATE5tazNoIHALx/dT5BE1SFWNPbAXOKVXgCYeOCe1MrMB22htLX1QaSf1ZbiDCHWWonyDbzuOsYES1nySTGAQUysyHu8jblPADu3BRxA0YBXCvj07phaAwMgtB+RJusD+AZJ0X/SmDQAKOVAQQRbm3gWHAkiBNNiZumvBntH0kI9I3hxLaLPAmnxtuovhGxaSAJk6KsqmxGhgvM9OhqajsQ5iV5WoAlrY340GI0CCe3YF1tB8KpLVjT2ogPScKHd6aERyptth6WV+4bpjVjo3pGxJPne5P2RrzuswUeH+yY7HenQtyivxPz1Nal6O0qB9YOSZi6l2xS3ogWGMGkAEv6tKYhcG1Iu49dcqm3RMHxdyK8BI4EkHqt0NJoyj1wHP/gh46AFXcCTFVVI6Ig9B/tCE7ZhQREIzCRytiz14/3hHduhYXtWeBpjnSI5IBBaFVdjRQqf1b/IBfa3cCxTTgPROr081fnb+Zv568KsuS+RhZGpGV217kixrCIFPuuze+UY5WjlnMgV48Kpe0T9Y3Nb/bJhizTyLKS5UfnvENFsGGkqW8FbJeSgKdYh1ge0B0odhRzPMfFBL4TStfinAVne44RRWknwtNJgNH4dARd9peNuxFCu72Bl/AbDrAZOFfZDgzSAByXphibrUJpVymV0SqwtQX45Ofk0ELK3lrNTSEOeQ5N2KAdlXaAc2ALNTW2XGeX3bju/bDajbbp072r1blF195B8Nq36yCZxwnrgMLURE0KuaS0uxVAP2LwxC+SGRtEUjVTqzAtxKNSllZhYmy5zj4bSbV6uLhZXa3aZg4LmEvtHlNXnukklCDU1aVjXIPQvpjNM2p8k6kwLQ1h1zJ4Wh1Bq+NE+jm69WeKMVoj3hKAVrjxH2jzGFYl8Z0TBWtVO4Ndd6b4qWajTTPl7TBx48QxSFsflCXdrSDdINGN0H18JwNlRTmHQ0z369vVObeWBvbVExkF4yZKWKa9NfN8dI2yyc/FsA/Kku7+/pQrDKs9E6ACdFeazfHGIhZ+KTStqp2/BxpDmIE0KoJue3bHmTwWf+OSMN2Dvwq3aX6qp6Q4H3bQsIjxya1pEl1TaKwr4byqWDi0ebYPR5jAcMcXkVzSZEUjV5iXizKAztMn2bd6GIsfNXcBzkGIKcSFWaYqvAXN3BuuBKBXvsgGnIPgUM3SazvHV7JUDm4FJiu2qc5i0ldFwHDiB33+AEIP8LvXdhDkIwYxFa1smamKbkb0eMKpjKBf3kiFfMTAf6wEXCt8bBspUTYv+xcAgHY1hBsRcykvgBZqOTRS3qP7emz4BigCRbk1Ekd8JUiNgVSmIQcI3e3xEeDHMgAyAdN3wAPhBONNmgVLuruB7g3xDQcNZKaXCaC+daB6WTCP2rvBOv4Es3EazlzxgCObXYOWcq3MA3s7tvcwwRZKiSkaCbQjYcwdGZhzxf1zx7E37bkDP8AqFjdv8KKkMR09qFqjqBfR/5Nm6LcTCIcnJs/gfc22QSZBuV7SyPWkXi5XfBODmODhicuy5Z59NWG3R+Br6vTGnYpCR62aXeZKeNsK5xaSC2O/I54MXvSlVHWWZdPG1WtBBR6ZpfJZTjFdus6XUCs4aq1zQ1hXttV6gnGuX+SSfRfpfF2cxEKJaEuF7ga+L2wo1ht8gYYp31h6snSC2FXCAz+MjY1Dz/HKl58XC5arGi/ub1Dn9Inlwi6kfPo6kxpGy5lrkJiWo9ZySAzXWKBPXcMM+QXr4kehwCXkJosb4N4YLPfG7oER6K/lZ3EGWDviGRf3mjaMYGk3xTpsd9ojQ6k1uXDX8MJClKCohNIRl4F0YLZAEAJ0RsVKLw/CoQ6EudgxM2iG1cEHPKKDYDtogEA+CxJMB/ZPUAza5ZWOuwykA7NIZ1FmvHTv0RpWCCkydkDfJNutOA8tZtR1OF34gyS9oYNvvInB+GtwGPAfQiMIQKgG+jKYDux55ygddxlIF+bQ/2/Yesq3dRlIB+bfE5DIN3KBogNtBNxgL78lOcLowhujmGt4uCu/VJBgOrCv0Oc3akAnsHRaHe/2K9Lt1NB0oEdnAaSDzkF0YUX3KsovHkcYzOtKtGmErIlgGUDrtkVlfCsLLQmiFbHIUwydSGnHGRo6QFkQC+3tvh2VJkQW1hqK9uMDsAWRV0gL7e0Y03ZDGshCPQ+PNLDrvnwMO+c82uDQubWw/Px5ed+1YJR+pd+v15PZMKWpHZloKQitiqVrbIM/nqzf6gDNMhg7slMEdI6layzmIK/LrNHQs7gXshk0gBq6udFrV5EI41Fefg2CuRkEQ4xTBEXR8ManEfuhVojT6qpcw/Z46jrKoyhDAbff8dRWEkhRdwFTozPEMM1fhwZoBE8GLFrw3dHbMS1yRzh1NZ1YbjbAGmqH3oiOyii47vJEi73hDXYWZcBEU8SAB7fiwgzVqK0N2dJDnpkDp5N9QJUUseCZwEwVVW2YbtLryMTbqKSIBc8ENqqoasN0l4U2F2+ksiYWRL+cTWEoUhsTsvNJkZ13I1vBfgjmt/hMLCliwPN5jMPVAFifSTerdmtNkIkVVQyYFkkU++6EyMoKGfB9wt7G08Er6aOg+2hE4O3AE+zIERI7RCYB2lPRjrKaFQ3k3aCqkdUzHDit/Z+HTk1q6iry2hXyYkhIpChd/Hx1d+3vdoMjIZE6nVSYRgimqF6Dp/jWc57zrziRzgFQxVNgrHDhX+Ar2IabgKxLpNQuxSPIt6puYs3B6KTeLkOj+vb6fTpsHG7oCMRJAKfyz45vWBops0vtCLotitsq111mpRvg+uHAiSdZxOlyaZPs5wjd8YSC7SebiHuHQRNPQWEADqupLpy5xk6khSDwkTFCI3zWMsk0nZF3BhNGHBbx6ZrL8hv0H0I7Fqm/kE/Rv8k6NyHKj8Jpmu0diqgoSHMhnKLZNEWpzSTTdNrBnsfuC11tIbxRM/aeEaq+0EDDkN0jpKNNC1EoSB00HHGoW+GGQ9g2OoSSeIp2YFp7QZpz0XStkSFObSqbqldUecsk03XqZhI+CutIqgpoCLw49AMOF7nR1R+lU3TvH6ytIMW5aJpW1zBFVqqKfNpuBIdLsamKXatBI774SYjKTDJN54MZfS9Kay6bpjcbyolSXRJPG5fujfPv3wrSfRRO1/z9GYdDb02aM+EUzU/fv/pBkN5cdINW3QyBIWwkSmigtt78Ioml7/V8JpR9ngOLbe/ZDJ+DNIpYppeOSOfRZw8Dpbf06fAlj159KLDmXj8MfX5ORr1w5ZopqHybQycxAFOml9qeSwEUPDTi4TRDGASqbe4QPHCanw9C1jZ3Dx44zdwHIWub1efdKr7fUw4+EkFzn8PPxbMPwLLyBmzYwroZyWnPaghoo5QYSk+CPH7J/ersCf4nGC5yoHmCPw9PP5y90z7eX755/fr9RbHoiNdAG3E1rH4uEG3/7uJ6DW2A/+C70v0rxtqmiQLsfnlxebOcuxYv16OSwEydiVffkxD73eR6L9OoNFArRA+cypONb4TWwncDmGKD7+5FS2mhhfLA+PBqjv538er8O/To1avz46O3MDHKXDKtayZzAw7AD1t3DvN0B+3knp2dubt4g8K/xL7vmHvD9sh08F1kPZBPYYbPU6PP4ds5PjQCH8DfP+TXSs31t+/fvPv+7N35m+MNU65vAeeDBSIztANkiz//qNWfpR5wFZvBZz/iE0vAjOHvJ7OT1dXN3fXV4mr9m75af728utVvbi+/Xi9XJx9O/vPv6HZi138EMAs+bA0nAjNovsR2YN1bPuHzABF885//dXycBqDAT/FCFtRdHLk87tvMinf366V+mYZnRY5mlXdH50cdJa2+xHFI0gAkFtgkO92kSCfCFtU/CGyP+hzdIYXKjl4xX/M3cZj6flTeZlckUKV7IC6APRpOkh4yrHyCWw49PUkU2X+URSGDwwxPULSGD99Ofsyy9MPNDX743ZPreNGH7OlP376h+/bi4IOmHQ6HvMTBwqdFEdqURh/NAUKLvvwuy0mcLA6T9KFt4b8Tc57qneONm3liZplaVNv5zjRxisByKyL+/A0XSHyOBNX0CFYw1AKkiub/B/3U0EdFCc3p/BkbJoMFCSOJ/5iNLZxGEvsQNS6Bi+LG7ywX8pdpjCvUkOkrfzF3rMrb9L6eNKVuGrHh+DtCALoKCR/i2Bue5aTLzm2va6mLgKrpF1FdQO2LZhk4ArKNV37N9EOFStIauKgrAi+wLNUdVGfNDqkz2u4p+XBfPMqdKWZll5BZ3bFhRjpXzNoHC7Oam8KsaW91Ruxsz+herZTHhbvnrMmdkvaCkFXx96O9IL4vO+PRnufucNR35/V3FT8n2os99XHZ+4jyuuT9Q3lb8vaaVcZWM5qLA/kwTUX11ZgVO8ezkhv8jNjbnRF7rbPy3uesvB05K3YIZ+V9u1ltK21G2diaVTeZZsWq1qy8mjSrLOHMjltDs9J+zazYQ5mROxuzykbDrLTsMjtuA8yItflZ2XN/li+cz4rVkVmxsj3L1ydmlYWBWWkZelaZmM8qk+FZddl4RpmPzspru7Pycuus4vI/a7ydtOfdOqMEZRe0jJJRujhnqJzSNSwDRVTuSBkoo3q3DruQlntJhgopXRvSV0QWVq56MweLkKabFwekLSIV9U+bXQfbPyHtjtYBUuh3dg4RNAZECIalzK/y7J+yuPpwQNLiZsIhacPjiKZf2s6LbYdIHJ39tVsB+6clr+vrL6G4sW5A0uIivt5pO29vZJHYHPmdPXUtEvnApOUo60NF7CqDw0EisiDgI5Ifg3MPFZJHzu6ZviH4cU8p3VGthwrMQ06zpadE+x2UsH+hoERMZknY856loSJbLqzqI7LtQh0ecvJ7bgbJoly+xENOfidSH1mtl6GMFnS8omSAKPrlOaMFHa+0aRE1PHovT6HdA/8hcaEHiaOE0RkjhwxwM0YWLcIjD3lEQCweIpkmM4NCovKQ1xyglId0MnAoD5kM84wRoSu5SK0FlOQltRzokYfMchBGLvJKARJ5yCviF/IQdowuyEUaEfWPj0wipB0PoXnIOS6yioBwY6QxTC5HxnEXI7kIr85FfD06+RixRcCzMUJqkcjGCCtChY0SUoTy6iOFIS4UR3F5bCzeInmhbIjKNGtzkprRTz7Cxwc7AqbvecCMX2NEr+evIZxibzzSsKNE7mCE5gZhZKfeE5naMSKoThoDBEKj7ALbH4sLzcTOTQ5SgoPLQUrEhRHM+TAeRQrNvo65bjKKIDYBLAsPRg1igbivnHQehKoLrENDZWSbmUMx2ACA96/O9fKAsLeMYFTygQbI5tF5atasTJdyjgHlkF+kayZ4p04z93aAYeUNDismNqlo87qnqdgEW0ZsCBEM3Op2GUe5lW0kjnLTDznLRU2GaQZiQCPhqTMAf7lBVPX94yw7hIOybeKZAqRnC2RC0KdOjUJKSirafQx4y03NgV9zFI1aUfvu5itaFtilv1l+DJ8FbqIbgR1xbFibdNVyGzvh8tWLdFgABJEDf+iRbwqQX64PfKXnw+E09znLLhcsPqKP3Xtq9k3CqwIfu/6jZJ6Y88X5ktOzv0Gem1CX6RjF/tRobdi9Ou9VEtjD8m3ojvLRdhWscLYfwjEr4NwbZF7iWXY0qBprMSu0kSNWtm2Q/pX5BV2mf+RbFemf+uLiy2h+/ZXyGRn01rtc/yxFqX5zsZCj+O7n36ZX/KnkZjCh2qtzCUa+WVxNr/TLxZfL6bWuLiRQXd1JUPp1dXG/lqH2oxSlEsoS1CqoKZ6gi1kKa84/CyvuwhpHYQ0g7Lr064sv79+9Ob8Qo0FYgyYsF79e3lyIGSNiyWIw48ZUDGhx7TTPtjgAIT5YYzh6/gjN94zkSQ/BFoTAM4H+6JMHXoUpNpG/o54EFjq6J1gXmusY1vg1LwY1pmlPogYdCU8PO06hLZzGduMXrZm0jF9zZ1BjGZPYDGyTaJL6A9Ae5ySKvD06ZmzpW9udQt9EanaB5RqTKIqCSZog+3ySAm6fT1Jd7UkaUj8w3PH7DAyKgsMkhfp3MElR+32iIo30pO6WU2gLPeGDLKxmqoYnsmyf34pbqyIXTFK8o2l6vMi1p7HbNLUomkoP9i2aTpO+B4Z19FkVqrHiHStUUzJR64D05E7nk+iLDA5OMAyKHg12z7YRag5JON6NoENPsZHqvtEDoaUP7UBWVgB4Lc006MpnsROoSSdKEyjCNXciPUXNnUIfrrm8FIW+my+nFYNjw3ywOQ6+KCrQI9N54FeHmnRwXJlpUsGvFW3QwHcNo0kJ1/WLBiU81xIaVPBdR2hQEvgHFJLUeBSeLTwnqg0quM4eG3TwnMs1qMBHfXRefs5Myvj4LnapQkNd0Uq4jnJbdHAf4TbpcoIoQj0MN0X5ofci1kYxGEw97dK4HbrtxVsxOiuefHWdvMYDzTqJCCXcFGJ3TQc8pocfs8Ms/OYMNPlWxLla0ZQgj2OhCgLHEStfNH7+vShVTeibIIp8qAp4EccdQZqyEOy4riPRdcQwbZ8zeYO0cFw7osmHD4IpcgRVdB1NpwS3KQK6HIqWw8HiN98oK8hnl7jVEtG2F4cKHEeo/HK5EqnnmN9jtBzsEDiwddKM/QZ15CDcGvCbkh/DWA+5Dg2cTtp1acGGFKmhCEkqRLov1DrBQ6y7O3dcxe7QgY5kiJSPhMIqAweIoXUwQjg5wvHHRWp0DC8fCHPwyWLRhuP2iKspRWA2cQrQph2+MwUfGZtAzfhxdoOivB1GMxJU8Nw36LCaiMaYpskXpglFKKgGrhapQs8/E6grnT5uEvE60sImTEu18nBRA8LQ89OT3ug3PhUlFVqxTCqdC+StHbq4hU+CXWiggHrVB2m4kAlVcbHZ3o9iVLuz56WM1j0z0NFrPpxs0w3yq2qCY/xe3lK5GCXrlPD4oWdQCxa5+VpW34gffWSjsoKh27z67YoCngPbimBcHosGSIAC249R6X4AnIadFeFBdu8Hz5lFRQHyRBNZcHrGwWEXzN8gB3trcx03uviGGs01HAe2fmkwK059d9pC5chRY8W9bamrGL9N0yUcV9RdGiiLuHOKj8KsLycNxjNPSiqaOQlQmG0uQLVmCCy0sGk4fEtbTRFuVrNoVyan9ZtMCf/cqWz7wCq5QTEctnCqAw5+yBd8pUvjIjjeh8Cw4HgkGz1j56nEie30BWCPWJb3KBpq7spNH3M9a5RAMysHob17p2ZZAwcDzQL79UJVOdkAObP+sPzLClyT9VmF5puVm8jKxjKYJazj1oaZXbMQG/7/W2j3t5xkQVFjJUWwXvXwOGqS0m/c1yTlmb0INYhIevgcFTvTIEaFRHfTa+pKnTFHUQOqL4NQy+MqrnecQgaZ3AUOaG+apBYtz3FU17elqIksRj0cRekbI7JN3QRhnN5NBOBIw+8Ra4ldxYAhE7Nw2GSjK1o7JIfFBdQlvpFmHNDmmA3QFa7H53N8uV+X43m3yACOUZBZH8AzFvkAOmYPLSJRLLKtDRwL9kRY2CBBfyQhgHaDQxsX3wk1XJRpoD+HJ8cW4iAit+0QCcAIBqd1n+GQ8sGOyWIzRtYYLqi+gHCUQVMRo0Dg4XW5RnESxQGUtUNPxxR51EfgDcoeAvax62h74Dg+bMWcDt8OIpnj77qGYkSKIL9ItnNt9ZjQj/e4K8RRwKGQLN3T969+yJpU9Ctqw48nPLIncelPfKWpbkZ4SqbMxdJFh7LCf760y6WVseMCb2BnMu7gPO8jTGz9rz2H2jO7dw6WSphiF/2vIYca8sUXyW8nRhL7ELUGR5xmEbwzVKkVTcw8/eTW/a+T2cnq6ubu+mpxtf5NX62/Xl7d6neXN6uTDyc//gWa4Nu375D3G1T107eTs/mrbyfwCUCXycOaBR99XX86ff/t5C9QJ1Sa6YSfeIYLfqJxXaRZUKWKhMK0ARwPPK9M+C9Mmss6waLhB/D/ftz6jgXCo/w0Qyvf5F/CWcvxu+M9HzoCgHph+DIDAWC+pBZGD/EtlegJLmypOVtl5/P67LLLR8NJ0nkuNw35tWuLwsOJm+j79VK/xKu3OD41Z7s03CEiREUc+g5X4YFd9injiTm7MZi7aOLSVRHQi51R8wH+/ocQGvj+1NRIOBj2SB0/ammrUX5kp1Eu74x4D/9MQhuxixPL9j/kDaeWty2prKJBxX99J6ZxXAMXOWUBXs1j1vl1t4/p1bzomb7yF3PHwjqLXuxo6Lr1mZqYRbH0lOUiH9Hpxe2pZDj3jA04qeOtIL1UsbShK064yVd4cWltKp+76WvyReHHVxTbeC3eHE5jaDtQVKLJGoLWefXgxoC+VkFtG2qjrLz2Ur5uSJNuCTd+35AqHVd3pGpMC7smpqQNAlwz6ZG80VZhF2t2WXs7GCiryUZo5jNCYIPY4gIUDsLbVKCbVbipyBVVmp3Ga1u+5c0D+v6D9ovvJC6ItPtipQ+2TtFec/F0TNvBEbtXvS8w9Y3AO2Gw8rGcPBpxyUy9eeVoo8o1OkrapYKQly0o/YdsQUSXSVx6Iz1rSEDjc4JkTF4hJJ8yiYg7Z8qlTNJZUzAJ4V277EoJ5jVUY7hzaBzqfafHp9ev5UdxwZ/UfCiiIudouJe96h2X0slW4XBnWz0OLJ1tFQ53tqVoQdKplrAIaT+rt31Kp1uHJLy3VIU2gUkI79plo0owr6Hizr1yX650zhU0IrgqVKEraERwPd7brALXIxpR7ZZidbeCiP9sjrgNWDplEhB/xulhG3UaKxKQIMbZTdKK0M3QSJu1jUvM7BIxQiavZeNaE9d8u660ssF6/a/0ST51dE/cuizZig2oRpmOuRCpQb8Z3DAr8G4s0GjthTQWxc3o8rKVflM7/16y67Z2BSzQiVF6AznVKmhaDqQ2NzhXikB7OZ6XNqIZmqzme5CGbOS2DV+6b5RvU4lvXhaxIX85Hmyr/KvUb0bsXnxKonRD9Lfp61ce/ZP5wuwFx/UPBttcfHkxhkmhTmGV5frnl2KVDOpEVtGzC9FfiGVyuFNZ5+7n316SdTK4U1jnEw73/0JsU4CdwjJX5y+mRmVQp7DKzeLqpVglgzqFVb5cfLl8KWbJsU5hl9XFiyktGdRJrHL3cqxyN5lVvq4u7tcvxS4F2Gks8/Hl2OXjhFZ5MW1ujnUiu7yYSVKO9Z/Rk5v/VpCyyyZcV0gI0kvFZrZLDlNXguJnxQYEnzn0+gRFxSZTHCZMBEHF5kUc5j4Ewbuff9OvL768f/fm/EIlpiQujpQVm71wmKGQBNVqd/g3O18vb5QqrDkenhRVmzZxmRrVSCo1A+Iwy6EVVDnb/80FdexWP62gqsQxB6SCv87xqmO+G9HCfCMQYNN5kHWSKM/Rhiuic2RC3LexglDWkZMu5qG4cydIPtgFaVhv9agX0MQ47RvmQxYfVC3qJWDiirusoxldpV3cIQ1corZJJMt/v6uw59CEkd/arprUM2DCiO8CyzXUpF5AE0a+em+7ehao4hNnhoOihT8DJoz479kF9+oxz5EJox6q2LuXgAkjHhsbB+hyz8t3mKAGUbAxZJ5VZDKFuLOLhZ78cmcFTZBDE0Y+UXYIkIgeASAF+iE0gkDV7CcRijOFE0ToMo0HRe1QhvfSzoTkhicWrGCW2sEehIaTMR562qNBvpBDbKbjmw96EljZXR8Si0rdfvhQF4lQTBSaUFbsrg72JXBCiKcrT8pSL+AJIY87JGW55+iEUS86IqVNUEYpxhSRkV5spKgNcnj/Iw6vVlp7uUMXSp6gIQyJUFh/pCT7EjiB/ZGy1MVt1BjJkx6CLQiBZwL90Sevy1DMGK1whZQMw1K4SmTgBEVIlL2s2dYWmOJWNhFCI71lQF3+FYxizCB7B7ONvrhdTDOW7aHRyluck4ZlKNzQZeDE9P0K7Fm39f1C962Bt0dXyVgKbF632YBAKcQUSltAJHEVtu9bqIvdwt/J375t4y5yC9c+V7jFz8AJIq5wH5+BE0Nc4SGtLW4o6weGKyvMKgPzAp4YN0zpjjkt1EU65/wOFG7YM3BiiCvdpQn1SkLC0RVYscKLeVWMYrbipTtmtfAX6pyl9lA2FDqUjSzblx2aqoV8AU8QeRco3NEV8MSQV3nzIhJ4xiRybZVLfIZODHWVO3mRfXykNnOh1J+jMFZ40n7EJ5C+vgeGBbWqboYyTiHmwE69CpvhiE+cG5Wy5IV6HSvkcdxhAuFex6mfkro2yOEJIf9oWOpSz8AJIX5IQtmHTVqY5+jE3YbhvtEDRVv+OsZ/Ekf7CITIIHy9671H97WIaw/4eO23F8L0sg19i4JM67YXbyV7s2YZpCGbVi9moSLlFkOxwTwIhr6HtQOrVdY2dZgcmi1uYSXFeP/2LddyG9pK3lWaWCpSJbJPpXYb313pgEfgvJBQQRtf9rCuZLNiVJOhEuN8FilxepZGuwxNzKZ84CYK8s5hidmUdhwFKWeoxDBWMpOF5rEqgVGoxMVHRQlCH/KKfKgGeJF0b3KqFSgQxezLgp0CGxY0E5SQCWIeQ2y29PjjdO4lbGLYS9+toPIWuEcBlQXqVngCnbBtCR0tDik5iiXQiVmTViQKBo0/txAYjewPB0v2gjyNeA5LtfPMwi6JxgN4yatOpXzID5bnsITNK9SjnKES3t+ox5xAJ7i1VY9/BdtL3QepWrwUd1uisUsBnvobtrc9+icgW/mDHQIHTrV6N/U1SS5w/fB58I3elcx0DcfxTX2TbLfIU2P6+pObRUtZaXVAwvO2wcwgDD2f173pY/v4pp0KDFJmtmEA1f2kApMKtwSMXaInDJ9ym35sS9gbDWkLKJOamVftgqXFA7Hq1QtCRLtqIPQM+Cg2TBlDjCLvU5sRm7dUhBwvIUmV6ngsE9uOHT+rYwIKMP7MUzsjG+9CA62V6XvDsxwp4cta7NAKk69VjiXPDIGFFhANR+rYoaliEPD+CfsjSiWQ2Dll+ZB5KFCATVk7lbJDK0xBVlHQAi92uGKbbsBnxpWZI0D3z0hsMhEhjcAyMGea+UksgDV+A0oer8KztUP3YIRATwJY+62hDqSEoQmpuFWRWaJIluSDAiCXYkYVLrG8sbGXWAiHT5GaBoDp6pvUcV95wHeEw6sdU2XOk7LkMtFp9Hg1HGcDJ4/6NoRvDn4od6Jbcd2mQpNVjeJ9CAwLdii8KpOdH5ZInNhOpQNLpvELhloLOFnm3/tRrLtmwm3hCNHjOiGzD08/nL3TI9/UPTPQEWCZuZkbLHveBO9FDsqN/SZd+9oag0/liF5KRK02OlsBswCdh4JNmMzSULFYsUdZx8d3Rho4Rrz1Q8WYE8DEUNZzAMpyryAUsU64SdQjX0HGlTTqMYsmVjXeNXAcqZMNia9YdafjE1Hg08MiSpGvY/snXAvPwqK7chcCqsYvhWt3x3tZU4N2x4YePwdAxmHwDtJVbLyJp9N99UgXuDgTdt+oRzbFxJmor2BR9kUU4eABTs12rgxf6Q66ZWScSSeRirU2R8WZ7MGOABpw7I3QwovBEYgTGYGIO+g34+RtEMfw8kPr0q4Z6jIGFaMIQ1hga3sq9twkOoFTJKW4U8AJoi7rsDsjeS4H3usTpBSRarRLsF7kOujweVT7npfM7Xuvtuc1PHcao7x4EL0n5bonkigFEW+yaCsam9KW2+MQjElYfGnLnyVW6I6dHDbRxLs8RbOmDN06LL60bT9G3fQDkDqFqlCuQuJLF18ZYPqO/PWeCuU6LL600W0J6rXVNVScScdGnCjEtoDDl6ZaJZl7AcZw5A96M5IEGpUOTTJ92vFR1+th4TzrATtBjJyQdNfwjB06BMtCb5yXAd3FdmNEtjnhEYwiCmHVAOVDKFRI7OWsjSfsZdBbZUiW8fBhaIIwhohMIwawvYUDY1WoUoGN5CydGyuHPo3YWO+ytsMckuyVeo0RQETbrd+CBt1qU40YmyxXOvoycJhI52V5CjDKQIzlYgeTDAAZCJWRjGWlCCVufLB+RUhVsYztg2TTYeXAY3Tc0NRuIitbrxg2kB3VVEMTWJuJcuFIFGdAoXpwGYIS7PT0vTQGJf1jabyFct5KJVIgGF6r4WzXnKpWEySOuofDn2Ilswn+gCVLEv7zVP0Dif15XGeQCL87sQF4wn4vooz1kY1vhFbf1ZHUChIWRdIA9RCx4JkS1lGss4V5ZPxMsdIzoyNSscW9YqLj5QGZ4sH1tJCSeeUk4RSnfpvJ1GGMGY/uAtuXkzs15WNo2OemNBYV3WNIBAdXGomK7jEkIonlKeJVnLKLNKXxINSr2lXnW7B9e2tkBzkbGDgHJj91ntsJv8wXg1ugqL9AjMBPa7R8RTjXrPSQpyV7xbYmVaOVN2DpUMY0kqnYida7W4jxWubG0iZ1aWomNcaFqYHZFEupzYS4LJ7iui+Jgcr9cHpqoPecmbEvrefDNNFpUlZ5d8kcg2bYgjRrc183hmFZNpqJpYFQxXtPZWbJiiZVO1M5rREx3ciOJvLCrpKoaR5IYKK+iADft/+hzF4BAO9fnU/SRFfB1zQPJDDNjiqBvefmaXM7NiVq5lI+tI9ofkG2eWFOrrHlq/c0R5+crtVWwtzGAd1HYUOLlB175gFw52YoZPuhoKeVUWvdQDrypZFXENqPyFnpATxjcehfKbwagPTmBYGFWxs4Fpw9YEHTsqGp78fhjyQE+sZwYttFJz6mZ9EIoBcP00BSJ8ZeVdoPLy6GMjDXFA/AndeaqWGX9PZCjbb5QCjB2nXFA3BPb+2a3l6okXR8bH9a0KTafpbGOsq93tQmbwQwgoeEktOkvxcL99kCjw92TI4+puPRgmAQk+lzgqJ5SEmydkjq9OOCJvW9OAAjmBh2SWMT0r5LV/vY7d4+qtB2/J0Y37cjaQRKK/T0ypQ9cBz/4IeOkH1DAmJVWS+cQeg/2pHte4IC5hNISXW8io8f7zvPQhHMbc8CT3OESixvDE2rautNm/KC9qi+wecGjm3a8TMCpZ+/On8zfzt/RTFUfU83C9DZY01g0OrziAXX2HftagSXKE4s2/+goRzICZALpUWqYWtFGzvuqzJLMmY11o/OacEFGZTT0g9CYpdEgadYh/XhAd1eb0cxEeKgG1WnrKELvxacWztGFKVdFemexWIuuoihFhsNqFHGMAsBL3H7miRPM0wjxA3C3lXmmGpoSRhUV8bVEBxOpL/OkHlfl+KgFIdkx82g85hqoFYHVtTeSvNEQ5nW9tSYmLLthQ3bLBy8c9re/pmMHPOoyh2yRtXbflhKqYbXIPQjBk9uX91k2lE1qqfuY6oxNaqv0jyRmA2khkK/uFldrfqO8hYwb4Z5+l15ppP0urSKXMzFtQPtw9nkvXxUG2N+GgKsZbq1uojB3iupKHSFONNYoBFMScJgLPEfaNMaVheGtpwCpJp8pEV2JsNIvtEaWerhGHDTQYQ4ZoZQSjwYgRskuhG6j+8GQaiklnyk8359uzqXWtdhT8hqRQyWKExZ8sFZ6Ud6bJsPwyCUEov2bF3hBYrhxoZQo+cIo+3suMpUU71aNbmqLnUDo/SkYY5027MHHmwe6+BeAqB78NfuLMpPCZZS5gMNmjDV/a5rmDurI80AlQitVWGSm1nbh2NOYDSvzwktXrl29mKVp8jLVFnCqBNfmRw9jBkG0F1ocimql+7CesylumCce82VJHCz/2g0uRTJlQt1TEBS1Up147aGvTyniYqJYVXEyBNwSNQDCD3gjMRzFKJ69SobkLlMZ5yPZ/fKIvjlwTg8RyGqjriAa4WPfcdbTHtPIgoLQMvz3XmCSZXXJot0kls679F9LSP0DlSLbngwEoehhqXWQ2nSiC1E4uHBZ6CgQdpHa9V3wAMhy6iUxr2UeByKvcHQntAQZAlHa9e3jhHtB2M4Jh+HxPFZ5us0EHlK4Ud1x4wqyhUmv1rGsb0Hlr2GEmnUm7eL4pALgwDlKUXngmNvhucCTIzBLm7e4AVLowdTmFajpFe3D++2FK/dNDioMclotQ3mRFZEZaaURKEzhDkqhnYIEcGjCHfM/nGWuk9fRChm74nEn2JCB6rYnZVKvlt9y+k2BCCM/YFRpvAac69GZOyyLTXvj0vdTfUG2bPi4pbzTpfJ82XciqAe7X/vaO7jNwuohshZte4adNkiX70nhfWOcd+AzQ18v3mk1htdIU5Ifo3pYNPp6ZjqEfhhbGycIeWCkPR5sRh8rxUh6uL+BnXbn3jeN4yIDqi8qYW13EwaZKnl8LRcJsdr15BI1zBDf0Dx7cRaCH6RF6fdAPfG8HZ8Lk/bAyPQX3MoEBkq7ShQpZs6Gkxp8+kMOlyKO42YwdD6ORm3AILFO0HhacdDKksaCcoCQQjQSRArvaQTB55ods1jhtgsdyRg8IjOae2gBQIOMElpI8F9gmrQxvh4YGVJI0G1OngyA+rj8dkCxgVRZOyAvkm22xYPLmZYdXljAQZJeg1ZPfjFMIA1eRwAHkIjCEDICV5Z2khwec8zHlhZ0lhQof/fsBHiYK2ypJGgfk9AwsFMhZiRcCLgBnsO9fEoZyygGAW2w4NCDhlHShsJboXE3XDCRggbbTe8986rfa2JGwkPebSPR5VLGQsGXU3NIQePcoQumtBHk4NnCWUJgxf7KwOowVBIKYPhtLred8Jg88FvUZ+2xoP1F8mHexhUqutgIDUxw/3SYU0dUTCK5MMBpHVzOIIivWw/JrAbfkckdhh5tMFh1Gr18vPn5f3YeXkqRb9fr9kzJeWuHWloqRStKmxsr46FsXcHHah4jDOO9HihyoWNHWY4yL0vayH07ET8aIgNUuUtbXPc6qKe8a+uWAXB3AyCYQEMimgMGt7HM2I/1AqBWrNS17A9vlqPElvUotjf7/jqLYlsUXwBpaCTpDDtX4fH8gNPhhs48N3RUy8NGnEEVlfEjOpmA6zhtumN7aiuBeFdnnixNzzSd5EvOpqqHshwZyDQeI36WDAuPeQsGE5hvZKqPsgmMV1FGQu6m/TGwynsVlLVB9kkdqsoY0F3l8U+n8JwZV19sP1yNo3xSH29MJ5PjPGcHeMK9n6wVEyRxSVVPZB9pjgliQX4me7L1GXBSbK4oqwHukUSxb47Kcayyh5IP2FP3imBljS24PxoRODtm6HFEHkbYq/DJECbE9pRWrfKwbZoUNrJ9BkO8Nb+z8SsbIziikQ21fxYEzJb1C9+vrq79ne7ETHwSO1OKk4jRLeAWIOn+NZznvOvuRkih0JV0AJohSvQAt8yOMYsZI0k5bJCGGWQVhBdluCSJSQC1mxAtff1+3TwOyYbIhAngR4Yz45vWBoplRXAKBO0QGCponeZBW+A64eDp+Fk9aBLbluGeI7QJVooLn2yiQR0WTQFLXgMUF2q7gGhvMDmwhl97ERaCAIfGSg0wmctk92mPfLOoIAIiMNQ1tCB5BDasVgkhYYWJJuswxUE4yi+DYO9Q3H7hGEoxLdgME1xADLZbdrtYE9saHEFUIjvxIC9ZQQDKXS0ocmuKNLRBpU4PKSWNkRxqFvhZicOTElBCw5gWnthGHLh7fojQySAVHorAnElNJPdrl03k/BRYFdWVdGGxYtDP+Byqx0dyFF+C4r9g7UVBiEX3qbfNUyxVbOioW23yRIGIRXdohvfBiVIeSa7TfuDGX0vTn8uvQ1BNjQVB6KkoG3MvTfOv38rDMVRfDuG78/ORWLIxLdgePr+1Q/CEOTCO/TrZggMgaNsQkdrr2HyQJFNu9L3ej4vzD7PIca292yGz0EaFC3T3I5N5zOmGAZPZxhzwI/4jDqGQuwelYShz2UIPwRhrrsFn29z6ZwGoMs0t/YekqAFtVgMNWTcZkSD4LHMlYIHbqsagzCyrHgED9zWOwZhZFkLyTt4fOGpLKQkhu4eLpYEtay+AyW2vm5GstrHGoa2sVMMtSRBHjHmfnX2BP8TDhy5dz3Bn4enH87eaR/vL9+8fv3+olj6xWvSjcg6VqMXyBD+3cX1GloF/8F7h+JXjLpNVwvE++XF5c1y7lr8nOVKIiuKsyMNd0a856SKr4J8oV2MVDLj+GrBQXE4C2wqavwVFceyeQr+448/9KykAAv5q57m0f94aim3MZ6T3muRzlOEkKqqs/2JVPVs9nFkI1FYaJPBibQJsTOx0Si8GksqJR19rNAiQ966h67o8D3gxVERBXUTWXrkmw9AHpQ0enixu4vt5ZqJZoU2usYjC6GU/pVFyr9M/7iaqP6PRS01hz0QH/wQndTFfq7KZnPou3kmqwYRxXLTzL0dSEO28Y3Qyj9QzTx5DgYgxHuthqPnj1SDmuYkdmtSEVce/1gpbHleFg1KFuFVGZAHOwRwphGhJUnPVxOabbrkhFQBVFs7dA9GCPQk2IWGQj3p0W4qZmbk6J5iA6YCm7Hf6LYHZW4NdJGEQhArbQk+p+qAxzTkgxSMQXYuBL+cFgX94ngZ+tOL5afXm91ILiHbe/WyHXeoDpVQv6NunKTKJWlDRTVc8DRUHHmnw3A5WVTlngIYw75yk1oNYMNbLDXI59icLl8zNC6be4wJB4UxGMv0eNkLIQnHr7oswil+q+xh6KvfVusltPXtl09Xn/Wvq6W+ul38dble4V2DR8NJ0KdnrDIvlx+/ftaXn25YE9x8XF6ur1c5gE9X18uK5m/f/vX3xI//b7a8dIrmqKfFeuSpmR8iyT5jVfvll5vX+jVkqt/+sry/v7pcDuN7e7e+urn6f0t9ffXlt8X9b3dr/WLFTH51dX3xcaXf3d/+crW6uv2CflvfLm6v9V/OKnheMUu81nOLorwsUA1jB6UdsS1+vvjyZXmtL79cfLxeXnKQ+Hn5ZXl/sb69HybraPK7e5gJ66tflit2y//6GRanm7Ozs5vP648X7Piv9NUV3ioZRj9L/vHVOAF/028WX7Os0D9dX6x+1j9erJaX+vJvy8XXNbQuF/l/Wy/vv1xc69eXt/qn23v9bnV/ccND8uL25gaWgBT5ze3Q6kcKxW3I/cXl1a3+8fbi/hIbRf9lObCEdYqHks8HV4RUxJeLmyr5tCHLl9H7NWuF1PvlLxShF6/Oe8v7slyj3Lq7/bL8stavviyuv16i2s8mQNdX64v11QImvL76UiWKY4mY8IHtObZHjieauy3cbN/f3lzewxoPy+T9cgWhsSb/en23gt3NOCHQLmm5SK199eWKPSmsQbhYVhv4p1fm1+teMlaw2yFknG/NV696iKE1Jld3N1/1i7sr5qZ0cb/gYEjcKuqI100xHBk1BMFsxkj4enE/sNvMLJmKgY3b16FA0ubx7uLzsp7bb1798LZ/Rt9++nR9e3GJavWvt/d/RbVz8Vf2TrPuI8CgMzPHLXvnXCmXV19gJ/TpYrFkHhdcQNMv4dD2Gv0s9zQDenm2BHfX16PqwK9Xn65GtLIsncmrV+e8O5N3/eSlY/UvX2HTdflXff0z8iZCY3A4vljBQSAq5Xe3OLerk4/zHoCPNlxcrC+ubz/3zYz79RqPnPEo/tuQEXgRME9fLRe1kVhqsuNHvbNkAQdLZZq399UcR/sshLjMleJTxT1sZ5ITRepnng8nliwfRrFl/ulPrV+yzbEZbjqjI2Di4xIfxb7v3AaZldEfVxb86vh0nphztLQGhYTYzj5+3PLVHH3h2n/gQGmVrLHAJiE35QToN5+edHT+0jJCq1o0/vSnWpPGoh/9Ze4N22sHUHw2N4OELJMxeDp130yhfEso3waPb04jcmtKjGrHN2Ld2NjVca6/jbdD9KfXKrYrz65eTP9ZmaEdxBXl/4KizwMz1owk9nfA09Iv0aKzvvIXc4f05RRQILeJZ6KHegTwv1EFYRwmZIMlAINlxAZX/T0yxzM8Xzd12B7JYO67dqxvQ9j86YGP980kgIAGAE8mCGRlP9QfxrE9ccbnTqo3RoB7oel5mw09wdl78boPRujZ3i6aG44jgXqhHjzFoSETQAAsw0NLHZVuyXCiKUEgHwh8oC0aCMM1HgDqNqAkd44GZbER7kBM4mj4rDYmOHXhk5/6jQxGQoj3ibshQGTPxCsnhyWnLnzyUzY4ObXOyMm8GBDUAQqEgp6fwuc/9Ris1JQcW51OPMdPm5qoUzih+Im1nWqRn53IYQODQl83jZ5TQMxDaM6QaB3Y6dbzT9OnUgA19OgYVvnddGUpb+10sss5/RU/mdZMYtEMsku9Lzz9NXsmyTbCEPWxT+OU/fSWbcLO0TIisfSxSfOM6XSL3p0e301roMmA9bFW+xz3dJu/l2a1yQH2qn/tc9TTLfrgFH9wWnwwcbWcCiJ9ftnwWfPCz7j1npGo8IpHbb3jFI50gRn9hN7O8a9TYMkn4Xr6t+4aQRXV3zJ53747hRP1n/7l326/ru++rvXLq/t/1/7l3+7ub/9juVijrZV/n+PEYwpeDbUdmZTLkbDYazuKC9HH3hGOrhIviYB1GhiouNVKWqeItqlXZ+KOTOxMT3Zi2tGCPey696P4f5Zh+xkKmmWeugjPbQvAX1+fp+ay4nl6Ts7aJLZj4dXr+c5L5qX2DsUXJe1ZEkh8nX40RwafY6dndCPeP5XpO9NTrxFr+X6b3UB86gBvF+9/IncXRWc1msP1yezy9/+b3XKzO90/xVmd7e2QuZe5t/tBdf4Q2YfdD2fv3LOzM3cXbwZOsBo6396tbQL/0IMQDpS2Ol5+6mnTX53Z6enObBiusiWHxRDNQ0/DwxOUs3PR6Qm+vdNE1hLfN2SDKaaeAX2bNxOOtXWMXSShbPDO3GHNbA+7ZV/nlvtnsVutBUGhVNwNlyHbE/yjEHd6sOP9aT0skiJ1o6840w7NxDFCCwTAs4BnPg/bw1KHkQdbRas2K2TfgRpTAznQONbmHlnzo5Z10viv7378y5ProE9BiAJewY/P5ulRAICuwbC9HXz0df3p9P23k7+kAvJOvnBhSsy561sJrFH4Oo35Ah9Au0s/u4M2/oiBF7G05tjVC6aHkgIQxs8rE/4LBRXDh7LpAygAM1/FIPgzhF/5eyJKFtgaiROvQBzjzcseXDRxqMaYWCCsxMyADc1y8srmbOmI1hRXQ8zNzdDUsyNYZphqRGUFZlpRDeCjIlYXvdkqX3FbLVsns5PV1c3d9dXiav2bvlp/RScv7u5v75b366vl6uTDyd+/nZRixn34Bh98gyNd4xHA8uqbD78YoY0OFUbo8Qf0A32A/oMtQGDDr6yHa99MF9uzFx/yX3bAfPDR4Vr9zfzN/HX+eJb/gg703Qb1dLWBdvb8H+kPKODkMi3g3CFHths4tmnHzxj3+avzN/O3sITxgv4PmCUpCuTQEsEc+M9jFgALSkIZPCsKGj6/iEimpQTFFUAOqnpxbg8Zww/tne0ZTvaxlzgOfJpVEfjgbIbTx3AkAv86PT87P3/75v3rt6//MeulHLuUZk3LGATv3746f/c9hMCqP1+LvV8v9UVxTnsYe0j+/M3rs/N3b/pqx7bPlOuw/BiOPzQHfnhz/ur79z+cDYAAHpH6veFZ2S5Bb/Vn79+evT5/f3b2rq/6Wns1wPxQ7Q+Q+6veyikL8QPUv3l3Bv/3/vX7f/zXyT/+P5jUgk8==END_SIMPLICITY_STUDIO_METADATA
