set(SDK_PATH "/home/matteruser/Developer/matter/third_party/silabs/gecko_sdk")
set(COPIED_SDK_PATH "gecko_sdk_4.4.0")

add_library(slc_generator OBJECT
    "${SDK_PATH}/../../../examples/platform/silabs/provision/AttestationKeyMbed.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionCommands.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionEncoder.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionManager.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionStorage.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionStorageDefault.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/RttStreamChannel.cpp"
    "${SDK_PATH}/../../../src/lib/support/Base64.cpp"
    "${SDK_PATH}/../../../src/lib/support/CHIPMem-Malloc.cpp"
    "${SDK_PATH}/../../../src/lib/support/CHIPMem.cpp"
    "${SDK_PATH}/../../../src/lib/support/CHIPPlatformMemory.cpp"
    "${SDK_PATH}/../../../src/lib/support/logging/TextOnlyLogging.cpp"
    "${SDK_PATH}/../../../src/platform/silabs/Logging.cpp"
    "${SDK_PATH}/../../../src/platform/silabs/SilabsConfig.cpp"
    "${SDK_PATH}/../../../src/platform/silabs/SiWx917/CHIPCryptoPALTinyCrypt.cpp"
    "${SDK_PATH}/../../../src/setup_payload/Base38Encode.cpp"
    "${SDK_PATH}/../../mbedtls/repo/library/aes.c"
    "${SDK_PATH}/../../mbedtls/repo/library/asn1parse.c"
    "${SDK_PATH}/../../mbedtls/repo/library/asn1write.c"
    "${SDK_PATH}/../../mbedtls/repo/library/base64.c"
    "${SDK_PATH}/../../mbedtls/repo/library/bignum.c"
    "${SDK_PATH}/../../mbedtls/repo/library/ccm.c"
    "${SDK_PATH}/../../mbedtls/repo/library/cipher.c"
    "${SDK_PATH}/../../mbedtls/repo/library/cipher_wrap.c"
    "${SDK_PATH}/../../mbedtls/repo/library/constant_time.c"
    "${SDK_PATH}/../../mbedtls/repo/library/ctr_drbg.c"
    "${SDK_PATH}/../../mbedtls/repo/library/ecdh.c"
    "${SDK_PATH}/../../mbedtls/repo/library/ecdsa.c"
    "${SDK_PATH}/../../mbedtls/repo/library/ecp.c"
    "${SDK_PATH}/../../mbedtls/repo/library/ecp_curves.c"
    "${SDK_PATH}/../../mbedtls/repo/library/entropy.c"
    "${SDK_PATH}/../../mbedtls/repo/library/hkdf.c"
    "${SDK_PATH}/../../mbedtls/repo/library/hmac_drbg.c"
    "${SDK_PATH}/../../mbedtls/repo/library/md.c"
    "${SDK_PATH}/../../mbedtls/repo/library/pem.c"
    "${SDK_PATH}/../../mbedtls/repo/library/pkcs5.c"
    "${SDK_PATH}/../../mbedtls/repo/library/platform.c"
    "${SDK_PATH}/../../mbedtls/repo/library/sha256.c"
    "${SDK_PATH}/../../mbedtls/repo/library/sha512.c"
    "${SDK_PATH}/../../mbedtls/repo/library/x509.c"
    "${SDK_PATH}/../../mbedtls/repo/library/x509_create.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/ecc.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/ecc_dh.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/ecc_dsa.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/error.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/oid.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/pk.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/pk_wrap.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/pkparse.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/pkwrite.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/platform_util.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/x509_crt.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/x509write_csr.c"
    "${SDK_PATH}/../matter_support/matter/si91x/siwx917/BRD4338A/support/src/startup_common_RS1xxxx.c"
    "${SDK_PATH}/../wifi_sdk/components/board/silabs/src/rsi_board.c"
    "${SDK_PATH}/../wifi_sdk/components/common/src/sl_utility.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/iPMU_prog/iPMU_dotc/ipmu_apis.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/iPMU_prog/iPMU_dotc/rsi_system_config_917.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/rsi_deepsleep_soc.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/rsi_ps_ram_func.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/system_si91x.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/config/src/rsi_nvic_priorities_config.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver/UDMA.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver/USART.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/clock_update.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_crc.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_egpio.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_timers.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_udma.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_udma_wrapper.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_usart.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/service/nvm3/src/sl_si91x_common_flash_intf.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/service/nvm3/src/sl_si91x_nvm3_hal_flash.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_ipmu.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_pll.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_power_save.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_rtc.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_temp_sensor.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_time_period.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_ulpss_clk.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_wwdt.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/rsi_hal_mcu_m4_ram.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/rsi_hal_mcu_m4_rom.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sl_platform.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sl_platform_wireless.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sl_si91x_bus.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sl_si91x_timer.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sli_siwx917_soc.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/errno/src/sl_si91x_errno.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/firmware_upgrade/firmware_upgradation.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/host_mcu/si91x/siwx917_soc_ncp_host.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/icmp/sl_net_ping.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/memory/malloc_buffers.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/sl_net/src/sl_net_rsi_utility.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/sl_net/src/sl_net_si91x_integration_handler.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/sl_net/src/sl_si91x_net_credentials.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/sl_net/src/sl_si91x_net_internal_stack.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/src/sl_rsi_utility.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/src/sl_si91x_callback_framework.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/src/sl_si91x_driver.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/threading/sli_si91x_multithreaded.c"
    "${SDK_PATH}/../wifi_sdk/components/protocol/wifi/si91x/sl_wifi.c"
    "${SDK_PATH}/../wifi_sdk/components/protocol/wifi/src/sl_wifi_callback_framework.c"
    "${SDK_PATH}/../wifi_sdk/components/service/network_manager/si91x/sl_net_si91x.c"
    "${SDK_PATH}/../wifi_sdk/components/service/network_manager/src/sl_net.c"
    "${SDK_PATH}/../wifi_sdk/components/service/network_manager/src/sl_net_basic_certificate_store.c"
    "${SDK_PATH}/../wifi_sdk/components/service/network_manager/src/sl_net_basic_credentials.c"
    "${SDK_PATH}/../wifi_sdk/components/service/network_manager/src/sl_net_basic_profiles.c"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Source/os_systick.c"
    "${SDK_PATH}/platform/common/src/sl_assert.c"
    "${SDK_PATH}/platform/common/src/sl_slist.c"
    "${SDK_PATH}/platform/common/src/sl_string.c"
    "${SDK_PATH}/platform/common/src/sl_syscalls.c"
    "${SDK_PATH}/platform/common/src/sli_cmsis_os2_ext_task_register.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_lock.c"
    "${SDK_PATH}/platform/emlib/src/em_core.c"
    "${SDK_PATH}/platform/service/device_init/src/sl_device_init_nvic.c"
    "${SDK_PATH}/platform/service/iostream/src/sl_iostream.c"
    "${SDK_PATH}/platform/service/iostream/src/sl_iostream_rtt.c"
    "${SDK_PATH}/platform/service/system/src/sl_system_init.c"
    "${SDK_PATH}/platform/service/system/src/sl_system_kernel.c"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Source/cmsis_os2.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/croutine.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/event_groups.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/list.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM4F/port.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/MemMang/heap_4.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/queue.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/stream_buffer.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/tasks.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/timers.c"
    "${SDK_PATH}/util/third_party/segger/systemview/SEGGER/SEGGER_RTT.c"
    "../../../generator/app.cpp"
    "../../../generator/main.cpp"
    "../../../generator/nvm3_si917.c"
    "../autogen/sl_event_handler.c"
    "../autogen/sl_iostream_handles.c"
)

target_include_directories(slc_generator PUBLIC
   "../config"
   "../autogen"
   "../../../generator"
    "${SDK_PATH}/../../../examples"
    "${SDK_PATH}/../../../examples/platform/silabs"
    "${SDK_PATH}/../../../src"
    "${SDK_PATH}/../../../src/platform/silabs/SiWx917"
    "${SDK_PATH}/../../../src/include"
    "${SDK_PATH}/../../../zzz_generated/app-common"
    "${SDK_PATH}/../../nlassert/repo/include"
    "${SDK_PATH}/../../nlio/repo/include"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/inc"
    "${SDK_PATH}/../../mbedtls/repo/library"
    "${SDK_PATH}/../../mbedtls/repo/include"
    "${SDK_PATH}/../../../src/lib/support"
    "${SDK_PATH}/../../../src/platform/silabs"
    "${SDK_PATH}/../matter_support/matter/si91x/siwx917/BRD4338A/support/inc"
    "${SDK_PATH}/../wifi_sdk/components/service/bsd_socket/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver/CMSIS/Driver/Include"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver/config"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver"
    "${SDK_PATH}/../wifi_sdk/components/service/network_manager/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/rom_driver/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/inc"
    "${SDK_PATH}/../wifi_sdk/components/board/silabs/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/config"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/service/nvm3/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/errno/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/icmp"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/firmware_upgrade"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/sl_net/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/inc"
    "${SDK_PATH}/../wifi_sdk/components/protocol/wifi/inc"
    "${SDK_PATH}/../wifi_sdk/resources/certificates"
    "${SDK_PATH}/../wifi_sdk/resources/other"
    "${SDK_PATH}/../wifi_sdk/components/common/inc"
    "${SDK_PATH}/platform/common/inc"
    "${SDK_PATH}/platform/CMSIS/Core/Include"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Include"
    "${SDK_PATH}/platform/service/device_init/inc"
    "${SDK_PATH}/platform/emdrv/common/inc"
    "${SDK_PATH}/platform/emlib/inc"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Include"
    "${SDK_PATH}/util/third_party/freertos/kernel/include"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM4F"
    "${SDK_PATH}/platform/service/iostream/inc"
    "${SDK_PATH}/platform/emdrv/nvm3/inc"
    "${SDK_PATH}/util/third_party/segger/systemview/SEGGER"
    "${SDK_PATH}/platform/service/system/inc"
)

target_compile_definitions(slc_generator PUBLIC
    CHIP_SYSTEM_CONFIG_USE_SOCKETS=1
    EXT_IRQ_COUNT=75
    FLASH_PAGE_SIZE=4096
    MBEDTLS_CONFIG_FILE="siwx917-chip-mbedtls-config.h"
    OPTIMIZE_TINYCRYPT_ASM=1
    PROVISION_CHANNEL_ENABLED=1
    SIWX_917=1
    SRAM_SIZE=0x2fc00UL
    TINYCRYPT_PRIMITIVES=1
    SIWG917M111MGTBA=1
    SLI_SI917=1
    SLI_SI917B0=1
    SLI_SI91X_MCU_ENABLE_FLASH_BASED_EXECUTION=1
    SLI_SI91X_MCU_COMMON_FLASH_MODE=1
    SLI_SI91X_MCU_CONFIG_RADIO_BOARD_BASE_VER=1
    SLI_SI91X_MCU_CONFIG_RADIO_BOARD_VER2=1
    SL_BOARD_NAME="BRD4338A"
    SL_BOARD_REV="A02"
    SL_NET_COMPONENT_INCLUDED=1
    __STATIC_INLINE=static inline
    SRAM_BASE=0x0cUL
    SLI_SI91X_MCU_ENABLE_IPMU_APIS=1
    SL_SI91X_SI917_RAM_MEM_CONFIG=1
    configUSE_POSIX_ERRNO=1
    SLI_SI91X_OFFLOAD_NETWORK_STACK=1
    SI917=1
    SLI_SI91X_ENABLE_OS=1
    SLI_SI91X_MCU_INTERFACE=1
    TA_DEEP_SLEEP_COMMON_FLASH=1
    SL_WIFI_COMPONENT_INCLUDED=1
    configNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2
    SL_COMPONENT_CATALOG_PRESENT=1
    RTT_USE_ASM=0
    SEGGER_RTT_SECTION="SEGGER_RTT"
)

target_link_libraries(slc_generator PUBLIC
    "-Wl,--start-group"
    "gcc"
    "nosys"
    "stdc++"
    "c"
    "m"
   "${SDK_PATH}/platform/emdrv/nvm3/lib/libnvm3_CM4_gcc.a"
    "-Wl,--end-group"
)
target_compile_options(slc_generator PUBLIC
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:C>:-mthumb>
    $<$<COMPILE_LANGUAGE:C>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:C>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:C>:-Wall>
    $<$<COMPILE_LANGUAGE:C>:-Wextra>
    $<$<COMPILE_LANGUAGE:C>:-Os>
    $<$<COMPILE_LANGUAGE:C>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:C>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:C>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:C>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:C>:-g>
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:CXX>:-mthumb>
    $<$<COMPILE_LANGUAGE:CXX>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:CXX>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-exceptions>
    $<$<COMPILE_LANGUAGE:CXX>:-Wall>
    $<$<COMPILE_LANGUAGE:CXX>:-Wextra>
    $<$<COMPILE_LANGUAGE:CXX>:-Os>
    $<$<COMPILE_LANGUAGE:CXX>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:CXX>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:CXX>:-g>
    $<$<COMPILE_LANGUAGE:ASM>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:ASM>:-mthumb>
    $<$<COMPILE_LANGUAGE:ASM>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:ASM>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:ASM>:-x assembler-with-cpp>
)
set_property(TARGET slc_generator PROPERTY C_STANDARD 99)
set_property(TARGET slc_generator PROPERTY CXX_STANDARD 17)
set_property(TARGET slc_generator PROPERTY CXX_EXTENSIONS ON)

target_link_options(slc_generator INTERFACE
    -mcpu=cortex-m4
    -mthumb
    -mfpu=fpv4-sp-d16
    -mfloat-abi=softfp
    -T${CMAKE_CURRENT_LIST_DIR}/../autogen/linkerfile_SoC.ld
    --specs=nano.specs
    -Xlinker -Map=$<TARGET_FILE_DIR:generator>/generator.map
    -u _printf_float
    -Wl,--gc-sections
    -Wl,--no-warn-rwx-segments
)

# BEGIN_SIMPLICITY_STUDIO_METADATA=eJztfQlz4ziW5l+pcExszGzLou10nlvVHU7bmeVpO+21lF1d255gUCQkccyreFh2ddR/XxwExQMkQRIg4Y6pmc5MkcR73/dwAw8P/zy4u7/9z8vzpX5/e7s8+HTwz4eD+8vrs+XV3y71/KuHg08PB/P5w8EfB7MszeL2+/355QIm+/Evz67zwxMII9v3fno4OJ4fPRz8ADzTt2xvAx98X345/PBw8Jc/P3g/BqH/38CMf4BJvOiT61vAgV9s4zj4pGm73W4e2Y6xiuam72pRpC3ixLL9OTD9EEChMHUAwvhlYcK/YbpU2sMBFP3DDz+ufccC4Q+e4aKXpu+t7U36Dr21HUDfLS6/fr281++XS/0cfjbfQuFJaMM36KtP2tZ3geYacQzCJAKhdgGegIN0pw81qPnJRoS1KAkCP4y1yP54/F4jSjWGfI2FI3J0D8S6BdZG4sT6k+EkIBKOplYLE9P98lKHGmwT6FCGcDBV8XWWWflGaOkkWRIaMRQpwzQ1alpRxaHvSMVDFTCRfAkBuF/eLs5xOuE4quKZKIDr2Csd1U5YulbJJjWjcDgNegiuHzVS+VkNgZHE/gZ47JbAsb1HEKIn+sI/nzuWKOSpVo2hoLbanftu4HvAiwW2ARRHVX5dCTfpV7ppxIbjC8xOCqZOSx0kKB9+uDU8ywGhFDgVDXxQTOlQzHooth/FITDc9FsJhaZGCTcgGeZhKWkFZHt2DP+IYsMzZRuqqosJb26GJm3H4D9FI6qIb28od3YER1qeB4dUb/TIetTfzI/nx7l2szS+oo1J9kXlGwt39Ln3lS/IeK/wBeObj8fPpU8qH7lmUvmEgTkEjK+q323tgPldFRsyLfPDyqf23c13HWbbpjYBO4nlx/U6SKJcsYLDcD16iWLgprmPh1mdi1e8teEoJDDgaFsjeaTt7LWNioW2z3mNZDD9AmeUBnNCQ4bWkBU1aCAtY65lhLRanBovUztwE90I7B7NjHR2BWz1jAq1sfvrQmtHbIlBTmyQMpQ6/pVyG0R6CBvQdeKZE1NgoOFmYQEQRA78Q498FXhU8LCZNBa2crvkNbV6JXuAMPR7DNqE2QGC1Qo4uHJyZURAj1+CPqMFodCLQLiwW3BErQT2IhAu7PeL42f438TAcyi4671pBmhW4/ZZphBe2Itg+DlAGSqgT2H06jmmh19Cw82iMB5SgEcFDxcTmIKomJhBAQcvciUqcAEHL3IjgsDi6ZHvcXSpvcqU+QIWLgaF4e60BMpQ+PCjr9WosmUoHfC7T1N3XAUcncfYTa8aN7Yav21enihVQw+yhBNZ2w/t2AZZPZhmBpPuh6RzmHpovSYzjJEbojJtK0QY1+CpocmZhVMTqofF4lWbefUvSsuOoY32o7lW+tzIjnSSgK9Knd8srha8a34XTYIZ3195ppNY7DVKZqYTBWhnZ4phS2poLW9FDRtII8C0lJBWwcm9zEdTnn17BfQIyK7cLpc/q88tBdmDm35zdv4q+FGgfTje/fzr6+CYAu3K8YtjRFv1GWYwu/K7OnkFZTQF2ZXbzfmV+txSkF25fTv7dqE+OYqyK7vF2SvIuRRkZ253r4HbXS9u3xdn90v12WUwu/P7/BrYfe7J7RW0KBRlD3avYLBJUcrZOu+y1dm42iLYh0+GlXNut2z3v1ZGQ5yBJTNiOxJ3ymy159Kc0+YCjUtlpluXjfOpAuivyowGvjZ2+QXQyswZGucFBcjKTAUah/sFyHDCql+fffvw/vTkTA3sZUQcJJQZyDcO1ouQVamR/BXy+8WNIkWEIuEBrc5coWU+UIKtyBSgcZhfLR5jb2fVF4/63atq8VADNYXSademMqQOfbfTjksnb0Mk3HQepxt979llPgV5TNxOESgR2AS2rxqTDBS/f4dhPtre+NuQDURykDrliBmO72DWVrLCbl5mOM34jkJtLLq5DOGCuIZAVeORgepEZW27qhFJIXWisQks11CNSAaqE5XA38GJd2Q8KVfCisi6kdopV8xSSJ1o/BYFtmo8KKZOREK1OsUcpE40YmPlAH0qz/0WQhVwPahN49vJRaybr2eW1nb7HKSWTIiC6kQlUbDLSfr0OCiRvguNIFAva8rYuhFzgihCEyDlWOWBSfTYhYTsYAtCw0lRsF0T+3vvmo5vPupJYBkxmGypoMoSu++WsfGfRQrHPz3ZwiUHi5sGmS4rSCQDxk0FN9DjH7fm4LJHxk0Gt9EKUqG4OhHJ2mZFCeXx8ROLIColGVFgI56kLjSjU/WjDJug/rSMrVMTrxiXHKyOTbyCRLot1RrJsx6CNQiBZwL9yXfiqc6PtFBrBMqda4alZOFLYXU4dj7dWkhTHTK7LYcgrUZoxBOEiuBhU0DHT2q6ZfYmMt2W2s0JXdkaWXTbT7MMJat7Cou/r5l006Opr+m88QG8LQqRZk26+9HEqISPm5iifLrSmHY3p4FI9x2dzZQ7Bk1Muu4a2CdKtmIprA40lOxTUlj8NJQcrNjdBil+YLjjx07g4JEB43c0mXB/s4FI1z3O34CSjVUKi5+Goo1u561alABFeIyVnOQX0fHvzEy499zApvP+s6qDlLDzICWybH+6I9YNVDJgHai4QMmmOAPGT0XNpb2oow9m5Npqlq0UFz8RNTuVrn1KpCqPzkReojBWclKyR9aRjL4FhoX2E5UllUfYdftWQVJ7ZN22bxWk0tn1Rwm3nxZCvVx/yC6piowoMG4qT4alIpEUFjeNXRJO58XYwIPi4gv36EwV6rSFSQEYL5WJ4s22U+kYgBamSONfnuqBcn1MFZ1Ebz/I76l860ntx96T+4Y3mGCTO2BddpBs1NcoLJZue/F6Mn+a1CwaYkyuiWjE2BD5g0kUidW3MN+xGAVZVgHWVqy2az+4PYhKxsIQ6DWAE7t2FAyF6mgNuK7loFqYlGHYjLFXaRDTYOGo0Q4yg4QDuSt/urFTjlk22Ejx8PsNRBOflmCRyIPi360K3EQpFhQQ//6O0+PKTYkEUjz8+BXLgM72n/5QJJNGvxORQeibIIp8mBR40YSOZ0xODHD8myJgM+k6KYtQDlMHHjHU1+viX6lMcqj4uUy4SMpk0XFpFAoIVKwoJVydVkN1NF9UbHxSwsW/3Db5KTsWG44jdqyFqp013fIOiwYFNPzAR6cbOfAAabKpbM4O9OQLBdRpxKYSgRRPnxGPUjQKsDr1QSrRSPH06oNU4lHC1asPUopPEVePPkglNgVU3foglWhQQOKWrmte1D0u3xYeAgfOUNpv3XaB64cvNbfx5KzuGo7jm/oqWa/HPmZMyWgEq1aFUrU6721EIAw9n+cuovqhAXupEwuexkxYdXF9O0MzLDhg/dpiwQhE25hDxBJ3fNshBSHlFitoWQ/EMgoOFIuWnUHoGfBRbJjjtteZJQnD0jYJExtHnEwiTMcNfmw7dvyiAikGJH4uxCLIGpvQQAsO+tbwLGfkY/4NzBoB8vHc57oZAgutqxjORG1/XXEsARulfWMUnUkau9Qm6fYVA5KI0qwIs0aAHXkqxUlaF2WbbtA+rkuhBCje6iQVG8HUSiiY9qhDPUlmVlAzc5E3q9Z26O6MEOhJAEt3zRWTBQOUUuAaMU3+lbGXH2TQWjOVmXCS3OXjNCjL64aF7C6YTD0n6nnzXe4eCE8dnX68R7BzDPJqHFbgVHMFh7n6OoRvdn441WC84JLFBNW/KMbbEBgWbMR4CqRNnfUSJ7ZJSjDu+lhmlAy31gCrv1m2fhTrrplwTfKQcq6ho717/nj8Xo98U/fMQEdKprEepZc+rwMmZWhibFdkHrk2anwx+02iUT1HXnyQFvImhdVjGtsW+GVrhFVkfOPWwDHitR8qw6UEqRsJnQpWkE0BW5cZ8ipRiU4BExcN1Hpm1V8dJhVYHGTKFc1XptqwkXUpZsSrUBE6VVSjrL2kAb/GPpdRY4hcCDL+OwBJZKnY0OOXAIx7HKOFRhEVLxUyJVCJRoaIk4J7qhJ8goYTuq9UAfK7FJzgEQ5AN+64zkQtBPKYOGkgiCpRoHg44e/sCKAuaWuEFl7iiECcjBtyqIVQPUJeio7h0XMdE5ysaaPHRNeFmgXWtqdWT1LG1WMYqggbBqyOZMY/ocJJp+WUSnkQSjSpQyQHSM4GSs2ItGmVc5rNCK+yyllnk5pjeV4UG97IoWTL8BlYulBAi/OYvD1VS1jiUQbET2bKEXWBRPNAmg0erytmVVUBElVA/GRsP0aN/iOYaJBaIFIEw08Ch58zfWfK+WaBSBUQPxkUT0+l9qqCpwOV2IgTJThkQPjBq1KWOhUhrGrKYUwKvYSDe4+K+ZjxsPKo+qA9LEY5GAaI0Vaj7hqesancDs2xX8Ny4FgZkW2O4lyWHfgv0sg7zDHBlPOmngVs1dA7BSjkkfDjN0EYQ62mEcMZdgyHL9MTYULiYDQh8ipCdqXl2T+ud2AbnR/ZIy5B6M6TNaVisZTfw9cxzbnnNXbrLNSWNyneVD0PUjuQ3IFzwM1j4ME8OeBOaLGOySEXUfC0nNOBrSLkGdlUmphVZKWzpOYhSmtTBCFZK+n22MMlgZao0sa8gl/Z5CzGBPhymnlAvoPfvpsIZqa7ueTDsbnEy6BqIO61NoOTu/pQB652maEI7kV+61ZG9tLelCUSo4LXwEpYEb9FzMxWvhFaTfMygnXgdIzE3oKapI0ssfRsVhzScF+pSgkjyb18WUWhQGkfwSxV2VhCsy/THb8klOvtXg+1CqBtlICurRzbshW1bSDtE3MCjAWtbRCDnTsBxILWNojRJDkddcnoNOT6BChLisU3/XSZvKn1R2iHL8VhziOedaDM8Eu6eNIAQtaCClI5Fkm6gkJ1ylk8qTOirJpRJJlf3maDaKvOJKn01Z8G2F0WfXCKkTY86yG3b3AycctdnKiHy70cgWvK6PjktOXEv6txHF9pp8v2kH2SjmCkzXHNebn2BZhqM1W5IsCybDTaJEEkZO6BppToDQAsvVojVNON7Ei6d08RZkVnC0TprWUJXn0LWRmFAwA+HJ1IbmqK8Co6WyDKXgkvoatd9K6r7ePgqiltbe1c+WexJQhB5CehCfKrE+V2cb/DF5Vax5w5jB0KEWZD3PktwXkA3Lkp+q6RDLSWx6a1Q9A40Aeh/YQ2Mx/BC06K/h4ZfQ2ERvSwvodrGzgWHNXhRGNhZimuR/p7EgJ9ZTix7SLvuzGx1qquRWsaSMJoCIvq6lHhQjIusorKFnS05I4HLqexFhtaGAbhqJarqmxBN6blKhprsSFJ+NDKWNDKCjXuYbwfb0uuTwUmtmeB5/k2dgXfhLDngQFoRT218As/iz+KtDbAfPSRJv10fjo/ygiWF6TSc9IN3XnrNIdjdhD7ri3m+EfGS6PQyzOCTFfzYGxlixlltAJKFfFMSvzoRORJ2FZoLK2NOO1cEvAc67ERPaKbBuwoFuTd3oa5FUGznYGXiGmQWm1LNTXjEXi1XnvNqLktrzr7HLEE8pU7OGoMRQUGa8W019WCyYGFbiRIVFWblYQtvXBYibXc0r6W1Loo1lzDRayU1XOjQSpaEHDV6TGQ5nRx1Z9RMO11tWB6idCOghjv6nZUOW089XocUFRVlxWaSpU6v1lcLZpGaOdwAtu8pXjlmU7CiFJYnKvhWoEWnGxRYUQZFsJsNARZS1FpVcWNGw3kcxTYXZQDRheYOb2NKOPf0bprDBuYESEWlXJYcWNKG7fXWjDV2YwOr8kIivLBCS6nshGbGyS6EbpP70cEV9ApwOf2fnm7OBHWZsCeVK4tMNxSMUqVNmaVjy52NMVspnOCy6ns7jCwwIsGzSaHCtB9FragMPMttAgirahU/G4rx3E2cvpOtz27xU+cx38mJ0z34D9lmZI6n+b00cEBC4IcF5OKJknVgUW2EPihCEFAM2b7cDQKDHd4gaCSZBcEqoeWgrzeVhfJ9Fs9jKUNYNtwUt1ySmpmDcklNGNHN3lzejvlwkQ4qW4BVYjcjTS8AhE5uIbLLptEVW7ml1fM4X6KPn8EoQfEXKbXFeletZxKlDeI5PKZ8ts72OYVd8uJKZDuVYsf0QDXCp+axjOMnZfu2Q1M3xLjwciwHaaQXxfMtAlod7wn983AVgeJ0B1f3kCYGACpwVW4oE9C3UXy5eYlpoKP26Wqms8DIr4b4IFQ3piRgSuvsh3f1pDWdrCwpeq4cOlrx4i2I6PbK23HiMvyiPCovu51x7FXzXUHfoBVnN+c4gUmQzorqFFjaJXRk5TZd9tzgR2dKSo4CNMkyBKofcwpEuqATOVKK6mIAO7f9ooa9hDSr+S3jCVYde3iMJdP5Eda7x6Sg9pUAtchAGHstxxqxet2jGrMswRWu+4otlQjaxS+oMzIoiNdDiuor7SzXBe+1i2vlohS/RLWWNu40hXNMgRG8CsmYjfwfdF9c2fMGQiuXOLpisikoa0YB34YGyuHnb+FL7+en/NcqHJ2f4O6mS88IfeR8tEqBrGHRglrkI9GwWoUCUe8WvSpa5ihmEgAQpBncKREq70B7o3Bc4fTFhiBfjpZhqY4tT2MYeHvWN0/T1Moxc2w1QwpOK3O8bACExaZBMUymQpoXn8LVAsEIUAethaJ/I3PWol2MOIGXo+mhQaE48X6BvIOJgNfxtAC+QsUgzbYpoKb198CVYIbHDdMtl9cBaILosjYgPSC+anAVlG0wQ4SEllX3Hm2PrArKDhg70IjgEgmBZ3H0AKZ9mVTwc3rb4Ma+v8Nm7/JLJvX3wL1twQkk5k0U94CMgJusJ2sTdhrb4MZo8gLeMA5WdaXMbRAXqDPbyZFXILQamO8dzptL1EB0QIaeSdPhZXqboOIbiWZrAzstXMvxLBG6yPPrvJ6GxfqCwPLkUGWdTcCleBW3QqQ5V9d002NjCxT2rwLXmgMRoZYUd7szwzbgtELYKa0GRppAcbGlmkV4YUDNu0h+rHTwpMNdq1r6Jdfv17et62nkK/0++VStukIO21PQCO6tSKEtvEG/lh2N9OClWdctCc1LVYKoe/Sd6eNpdJp5fy6XRDMzSDoago4EXmy0VELDe97GbEfapkorarGNWxPlJ69LIYivOOLosO9715vWMqK8hgKjaFXVLgrYMVOpIUg8NGedWiEL5qRv26iqC/yjmHCaGCnydaal12jexfasSzdmWyG7pURgXcD19mZiveCWVrtDTpLLEFrJpih1TRlqEylsvTZwXboEIetMhNcqxWvFElTnUln6U8jb+GLG2UgKMtnYYhD3QpXA0+HstXnRDM0A9PaStBKxbI1RoYclUQuU6eMspVKZevTzSR8ktIpFIWztHtx6AcDQxqyVe8lM/RuH621BKVULEuja5iyKk5BNmssMzCsO1Opa9VowyHRhKtLpbL0PZrRWxkaqVyWztStSobanGiG5mhrnLx9J0HvXjBb69vjgd5RdVpTwQytz2+PPkrQScXWaEQ3wBlSRowl6czWWMzZQfJGj5IA7RXRDymo2PZezPAlIIcHU51sNPrQPrcfIL2hT4Yvh/bKfUHV99ph6ItZceuEiWplIPJtMXd5dMGT6mS20aODCR5rsQgYwfcC1DS2Dx4FzJF7oWqaPwePAmbPvVA1zaxpF4mj1o6Pray9vh8Rs4PRBVxecQ0ubFndjMZvryraGQjPf766O0cp/Luz6yVMjn/0WYnL5xVFu7B/ef54/F5r0lID6gYNQPuhwCcaUgMVRNWouktRw+/88EWUVpbUeq6HN4bj+KZAygWJrDFmDMtVEqRR3vT7xfEz/E9iIU2v5LB3uEh8vr84ffPmw1kGGx+zrcXEWmwMgu5L9HXr0lumijv69Q25PrFP9oBnww0cEFUqxx4KWw0Pns78+6Bpsc351vB6nQHugiWnhIHlPo4XeD+UfiYnn9hqePDIsA1LSWM+wUpleFYkuxAX9XAhklt0clqa0Fx66IC09DpeUMODR6pxckqasCxgOwnbAtm2KajhwSPVNjklHFguwNpInF5Dpx6gCto6oBvDYDldDGRnUCyKTwq//2uf6xg4AFVVtOK4gSNoSVlXp4gPk3z7UDUMPJ/J1mdnDOUh6V5OvRIBI9+8pJqh9rW/2fQKVlzW5RBBWkkoQ+0SPMe3nvNCvxJAlCpnimZAWOAScI6vHu1HvTqzK0psUypsQlmWyVA80NBlnW3GRaXuzQfSkfYzbgTQpCcwXhzfsLSyvDaVPWk2KO0wWR5cj9gyWfNVEvWHuNqIcM3qNUtN78QuIEnBFm72pajTvhDChTqBU3iC7zKFo9MApljh+6Dg61VonR4dnRifjubo/86O3vyAHkEQ2aPjY5gYUSmndc1kboTufLd255DBBuJzj4+P3U28QhE1Yt93zK1he+V08F1kPZafwkn4nJhqDt/O8fmCObQDCD/hayvm+uHx8cc3xyen708+7O+wcGEJcj5ZIDJDO0Cm+POPWvUZcTormAw++xEfYAFmDP99MDtYXN3cXV+dXy1/1RfL7xdXt/rN7cX368vFwaeDf/wTXXjl+k/Aejj4tDacCMyg9RLbiW3v8hl7l0fwzT/+a/94Qa/H+vQP7N0BdWdn6fZN2Sx7d7+81C9I7MM0q/fv9k56OkpafImjP5CwDxZYJZv01ufiR+j6CfaV0Oxv4pCchS+89UCMzluiEqU/GU5CzoAhztDmCTrB/unh4MfUqp9ubvDDH55dx4s+pU9/enh4ONjGcfBJ03a7Hc1zmP1aFKHBHfpoDhAb9OUPqTFxsjhMyEPbwr8Tc070znHzMk/M1K7Zast8Y5o4RWC5BRF/fsBlAh8MQKOUCBZxVCOJovn/Rn9q6KOskFA6f8Y2SWFBwkjiH7Oh5cNIYh+ixoXgPLvHLc0A+tKxvUcQojZIX/jnc8cqvCV3KJCUumnEBuy3SwLQZRTYTx/O4S2HuEI1va6kzoIKki+iqoDKF/UycIRPG3slmcqVpCVwUdcMXmFZqk5IZvUTEPYrkqbaTZcf7r+jI+FZfhw/a17yn1VGyTP2EvWstEo/q19KZ78iogtjqxl7UXFWu4bFfFNKUVhuYb0ofV9YgmW9KH1fWLJgvWB/X5i/N7wnqdkLj6wX5PvqMLn8kHzHnD/MMp/lWc79e5YtuM9KPsazkt/vLO+LO8u7yM4yz9VZ3qd0VnH1nDGcL2dFZ8hZ5r0xy3tOzAouC7O9G+Ms5184y/z+ZmWPvFnBSW6WczWYVe7t6ngtQi8Babj9Xmlzlx10TZ+Lpt8xaSHWfce0xQsQ2hM3BJbvmjgX+J03KTO4elPiuhufOqTJwpjwp0mvOONPwLp4rEPqHmnodVz8KbI7lzokye5E6pIm3HeDfGla70DjkFS5P4g/TXZpTYck2ZVAHdLkLuzhTtV6dVOTpPpwtu2pKoFTOybJx+7rmjQNOdoj2T4WaNfENFInZ7qaWJicqSuxdZvTMaI1dkrAnxeMwJZNCaJu9x90FdVwbwSPqKaY90PS01j0nWQwbj8Ykp7eSsAjozFmeW8B+1DiHUSwI9j3FrAPLM8Q0T9yoghh9WOqPhE3O4lhBFzok74cC6GPDFb0rSFySuFPhohqHBf2ij03RE59KLghUssx2obIahg9DggYNkhaJY7XUGn5AFtDZOWjXw2SkwtNNUROFjpqiJB9ZKdBUkohl4bJKkUWGiKMhv4ZJCOLzNNHSsM0ZGAwWrESsyCxg8RWg6z2EZdFnemTuBIPpo+QLGJLr8RZSBWe1ByROgSIocFJRIkiqOi501npnOksH8diRg+CzspBJ2bZcaFZdnxzRg/tzAonZma585azwqmVWeG0yKx4RnLGOLQxyx9mnOXPGM6anMFn1Z13+GhnR3D+7XnAjN9gm76ZH8+PtWy3K9LwtiXdakej7TCyyV6mABHMLdMeAuHoexPY/lBcaC5zYgqQEuxcAVIiIYxgrofxIFJofrPPdZNTRGnF07Lw8NEoLeB1lUNmIKgu2PFLXxnplkRfDDYA4MPRiZ4f4nWWEQxK3tMA6UyVpubNSrLYkRUH7FnjmgneXtDMrR1gWLSx4cXEJxVtQXU0FZ9gy4gNKYJhE1vYExAot7AoL1Au+VCwXNRkmGYgBzQWDn9IEEt2CsXLDaKi+5Bg2SEcNa4Tz5QgPR04SEGPn8spgES0+yS6kOTGUSJbO9Q423c339H6wYb8y/Jj+CxwE90I7Ehge12nq5Lb+n6sK0ov0mEBEEQO/EOPfFOC/Hx9ECu9kPliRBMnQNpcIr9XsVVtLx/tVMAst30437CB4PYo9WVMc6BG1VCLWaGN3CHSlWjyK93NvyA/6Ko3+amfn30bzK+7UjFdXme9l8ufJ1Gq35ydT6P47udfx1f8JbehO6Laq5MJjHxzfjW+0m9n3y7G17o4m4Dq4m4Cpd8XZ/fLKdR+nkTpBGUJapXUFI/QxVxKa86/Sivu0hpHaQ0g7Lr067NvH96fnpzJ0SCtQZOWi98vbs7kjBGxZDmYcWMqB7S8dlpaW5w7c1U5biNPVeV413BVAQixN7vh6PQRmv0bybMegjUIgQcVPvlOLGoa1aLYRI55ehJY6OyMZF1oBmdYw9eSONSYpj2KGnQqkpw2GkNbOI7thq8xc2kRV38b1FjGKDYD6yQapf4AtCU5iiJvi875WfradsfQN5KaTWC5xiiKomCUJsg+GaWA2yejVFd7lIbUDwx3+Po9h6JgN0qh/g2MUtR+G6lIIz3E33EMbaEnfZCF1YzV8ESW7YtbR2xU5IJRinc0To8XufY4dhunFkVj6cGuQONp0rfAsPbOp1I1FtxcpWpKRmodkB7q/T2KvsgQ4LPCoejJ4HdEG6Bml4TDt+db9JTP/8pUJMiPpl1R6jdxqgdS6xPaKS6saYhaQqvRReflI6ghU78RFBV8taVqwq3eSHqyVm8MfbjVE6Uo9F26OJlNLAzz0RY4cGWoQI9M51Fcba3TIXBVq06FuJa0RoPY9Z86JULXfmqUiFyHqVEhdg2mRkng71D8PuNJeraInOTXqBA6867RIXIeXKMCn4fSRbl0cykT40/Zpgp1mLKVCJ0hNOgQPjuo0+UEUYR6GGGK6An6YrwLGgBR8H5aRVk2xiVDahKgQ7e9eC1HJw0QUKNT1OCjXmcpFIkwhdgX1kExWnPnusRN7ljyrUhwHWYpQS7XUhUEjiNXvmz84rtspprQN0EU+VAV8CKBW7csZSHYCF3wY+uIYdouZx17aRG4yMeSDx8EY+QIqug6mrtJblMk9G8MLbudJW5yk1dAp7K41ZLRtmenKhxHrvx9qyJTDaoeMuXnq4dUPbnqIVPPvnrI1IKrxxAFOzsEDuwtNGO7QgMrEK4N+E3OAWjo8mmLBkEnStu0YBvK1JDFC5Ui3ZdqneAx1t2NO6yhbdGBTmjJlI+EwtoCB+yhtTNCODPGkbNlanQMj05MBEy+eLThiFLyakoWok+eArTbjW+XwGcYR1AzfN5To4g2wWiGiAqee4pOT8pojFmafGmaUCSOYjQVmSp0+plEXWQ6v0rk6yCFTZqWYuURogaEoeeTiAboX2IqChFasAyRLgTy2g5d3MInwSY0UKjG4gMSFmdEVUJstvWjGNXu9Hkuo3XPDHT0Wgwn23QDenlKsI99LFqqEKOknRIeP3QM3sIjl64tdo1s00U2KisYui2q3y4oEDmwLQjG5TFrgCQosP0Yle5HIGjYWRCOvStN3xE5sygoQC6cMgtOx3hP/ILFG2Rnr22h40YXX5KiufjGlTSon6C+m7RQFDlqrIS3LVUVw/fo2oTjirohAeFKtyWJUZj25WWDicyTnIp6ThIUpps9UK0ZAgstNBuO2NJWUYSb1TSqmzlsgWivK6x0lSLlpt0ZrJIrFPZ1Dac6YOeHYsEXujQhguNtCAwL3RZKRs/YRy9xYpu8APxrgLRH0VBzl2/6uOtZrQSWWQUI7dw71cvqORioF9itFyrKSQfIqfX75V9a4OqszyuUbh6vIisdy5B9eRBbK2529UJs+L930O7vBMmCooZKimC96uBuViel27ivTsoLfxGqEZF0cDjLPAVAjAqJ7pI70XKdsUBRPaovh1DLEyquczxODpnCBfZob+qkZi3PflTXtaWoiMxGPQJF6Ssjsk3dBGEMyaPLCOBIY38LjEgVPYZM3MJhk40uF22RHIKI3Dap5fhGmrFDu282QJeP7p/PccTptpMH7SIDOEZBZn0EL1jkI2iZPTSIROGn1zZwLNgTYWG9BP2ehADaDQ5tXHx/XX9RpoF+9k+OLSRABLVtHwmojIFwEAgiYggI1PLgba8OAvx4i5svC8AZY+xSh6fnt0cf02qA/onq3f7wR/okzv3EsdF1M8LDaGWusc0agQX++dquslXGjud40zGVcQfH5p9hYut/7NnXnv9jSVGWTJ2RYf2GKTbRqzPk/mZwOEows/iroUqtaGLS9KNb978OZgeLq5u766vzq+Wv+mL5/eLqVr+7uFkcfDr48S/QBA8PPyBnJajqp4eD4/nRwwF8AtBt07A8wEffl18OPzwc/AXqhEpTnfATD069f2JxPSdZUKSKhMK0AextXxYm/BsmpbIOsGj4Afz/H9e+Y4FwL59kaOEb+iUcae6/2996oiMAqBeGL1MQAOYLsTB66NjeI36CCxsxZ6NsOhdL/fafDCchcxNhGqqxvUSCr7mERIqKOPQdocLp/XXnmcOOMNH40k2y42eBVbLJOQX10fGjRgpv/pFN4mXeGfEW/kxCG5krTizb/0Trr0aLOJGV1Wv86wc5dXQJXOTPAUTV0rQNbq+m2H4heqYv/PO5Y2GdWWO6N3TV+lyV6Dybtaa5KEY0OZdOJMOZWmw4/ka0AnJjYG4vSJ5wU6zw7GZUIl+46SvyZeHH99zaeBnP7E+jbzuQVaLRGoLG6V3vxoA9ZWa2DZXOntZextc1achuUu33NanI8K4lVW3aj8fPXElrBLhm0iF5ra3CNtb8srZ20FNWnY3QAHyAwBqx2WUeAoQ3qUC3hAhTQRUVmp3aK0geaPOAvv+kbX0XaC6eAqCVKe0CnSZAlTJ9WLwTkGyp4gV0WPF4zioMuCyl2rQKtE/hOhjlbFJAJ8oOjH5jakGlrrJ0Kcyk2VIGMzwXGDW0dMHOpIQZeKRwrlxaNDnrCqIhvAVUjmqf4Ynp7Sp5kV3SNlkeZNF3KRLhZa549eGkRItQhDMtnpyblGkRinCmuYgqk9LM4ZDSVhYvfpy8khbhyGGc3kY5PdcUiPR+XwWyJTxSOFeuv5ycdQWRcN6FS2En5VtAIoOnIs1UAYkMnvtApVPz3COR1UYpVFcLaITzLd9FOyndMhjxbIlXvRoNUxmMJLbp/cUKUE2RTDbHHJaYe/98gExRi7uVJq3+Nt1JygXvVb+TL0cw5yWlG5YntGANokFm4y4801OvB9bPAj2LTN9klQ03Et1I2N5T7qo7sc0UvrhUxi7UxXCwjfKvyGax3A0oQiJ3werDuLWEBsnqcdu41I0nqo1cqK68UQjMMSyS3rquukVSmCNZhF4J/wqsQqGOZZn0zvrXYJkU6hiW+YJDE78Cu2RAx7BKeq216jZJYY5hkfQ+btUtksIcwyLfzr5dvAaTUJxj2CS9+lx1k6QwR7HI3euwyN1oFsluV1fdJhnQcazy+XXY5POIFnkV7SvFOZJNXsWkh+L8V3RFlOGwJWBVnFlsmEdQJi856VpkFZx4vx/WOTaV+BfBqbVwr+SKnNDFtxLhS4UWTy4FrI6U6H1VaCz6VcCAs0RPoTm7gHl5iZxC028BU+wSubuff9Wvz759eH96cqYKyzImgXQVmiQLmAiXyanTxohvYr5f3ChTQCkWkfRUmpkLmX1XCCozyRYwkWYVzvFdU+oL51BPFFbhVIUfBTOqxwS1S2nyuL8+VKy/grRTRPmLsyfKzZbrvKU4yBZuqFaLdwZLjmfw/i52dWjnQEnL7fTmdnVI50DJIz2Fs3sbZ3lu74XL7dVincGSRnxtu+rRTkFJI70J0ovG1aKdwZJGvHj9sFrsi9jkmWCnYIFPQUkj/Vt6P7NarCkqabRD1YYsOVDSSMfGygH6dOelW+hX4Ek2xFQnvLjMIO/EV6aH3n2pGH0KSxrxRMkuPpHdwyMF+i40gkDFbC+jk2eG/M30itkgD+1f5Ewgukw92ILQcFLGfQ/z1MiXcj7QdHzzUU8CKw2jP1ExqdoOHxAso5MTeyOcIh5TC/McMCmkyVKZkrQzaFKI4053ivB3HMz32KRQx/2uksQpMmm0s/5WWfp5hHLMEBnkahQF+VNok3uOjbF3VOjUphuZMfIDjdDK6KR1ucoxzwGT2OUqSVvexpmRPOshWIMQeCbQn3wnni6CQIshGqFKKRGGpWg1SIFJCu435SpsU9035S3EIoQGCQKvJvcCPjkmmHJDtYm6vE1Vc9LDCo2c5fmHWIaijVoKTE7fPvHWeVPfLnX7HHhbdKuHNfEeehP/EkIpZlCWvUzSU3sQNNCW60WwmXYnuYm3zN1k+0TRlj0FJom0on14CkwOaUWHqba84akfGO4UsTI5WGfQ5Li1TuoL1EBbpj/Qb0DRBjwFJoe0st2WVCcoJBzdNBQruvhWxCfHG2BSH7AG7lL9wNQdnoZSh6eRZftTBkNrIJ5Bk0TcBYp2Zhk0OcRV3ViIJJ7HiVxb1VKeIpNDW9VOXGYfHqnLWirtlyiMFZ1077FJpK5vgWEhnxiFTZDHKNNlSUkT7LHJc1lSkrhUJ2ZFHJhb6Et3YiZ+QWryp9CkEH8yLDVpp8CkkN4l4ZRnVBpYU2TiL+lxprtYq4V3AZoM4pPdnNZOXOJValB6eh/SqR4o2KdX8f2LnM6AtkQGEXskw3ty38i4CkXMUY/mAkgKub5GAel124vXE/oGp5mjIXuSa8gbUQqLx1pjGgRD38KagdUqaZcqRAFNlbgL7qX4UTMzDRvCAmsjUcG1tJBhqD2tgSe7BFerjUI2aUapRDlWqePC92I6KHNeSWCslT/l7CVnr2wAnyKS4+8YTX6+nEU5D0uOj0jgJopxppDk+Ek4jmJ0U0Ry2CqXuVLzVoWQQEzS8uMBBaFvgijyoRrgRZMeUGBagAFPjrsA2Ey8t8ain0MliXUMsdmTLsSweedwyWE+6cYak7PE7TSoLFCzgpeQSdtB09GKl3Ij0xIyOdsoCsSBYXEXFgSmlvluZ025tM4iTSGpdtRd2u3zeFA+4RJaLg9ovAEKSdo8QS26KSLZI2fFSBeASRtBqEU6RSR9BKEW6xIy6SMIxdgXkUkeQajFvYBL3ghCLdIU0mvdmC3aOHfrw0Q2zoUo7G7UzrbonqA8UtvZIXBA1D26YEWSC1w/fOk57CtlpGs4jm/qq2S9Hj++GjWJRhhpVTDS87XGxCAMPb+3hQWP0et2CzHIqbIMKy9ubmd4VLiXZug2WcnohNu4c9KSrdFUNIMxqolF1SpYUjwQq16tIES0qw1Cz4CPYsMce/iU5TuxV8mDhIlO4FVXRKmOx2mx7djxixr0GaDEsyY2RvbdhAZax9a3hmc5o0egbLBBI0SxFtmXODMEFlrYN5zJxgh1laEE7V+w72EU/ok6ojQPUm8gBqgxa6QyNmiEKMkiirF/tUMS23QDMTOp1BwButZtoiYSkdFKOHrmSj23iQpehVuPEieq0Kzt0N0ZIdCTANZ4q693esnIJam4JZmqJJUZlh9k4IQUL6bwicoZH/MJC1//aU/dAI+sok02rssP6PZQRLVbKsxjCEMhk5daz3HDcVZwMqivQ/hm54fTTVoL50CYsKaqOvE2BIYFOw9RFcimp64SJ7aJdDD2RlNm+Iyd1gBsKtNv/SjWXTMRtviD6AmdZNm754/H7/XIN3XPDHQEeKqcpMZKn9dBe5UDbmO7IutXa6P3sT7ZS4GopUaHtGAWoAOVsOmaqiQUrJVtJVaxiZ1lBo4Rr/1QIdYlUHLo6hSAkrwL6GSs860StYgXUAkljHrHrElViXMFmEDa5YbDV6h6s7HJKOTkcJUyxKu4/gXXr9ObKsYPG1Fj+NztGQLiRTDvUogNPX4JwNiRIloIF3GJJk2m7moRzjAJJuueqkWU4BFM0les+Poyim3wCKdaG3fs8wYtVPOoBBNGVNQiSxEJJrqzI4AGFFsjtPACbgTiZOxY8S3U6zGKNoZjeDRwwyThNtoMwcQnwwgWWNueaj1zGZnE6Y4yvBnAJNGeItADJ3EhwR6qkx2CSCXKOUivct2y/5yoeU9qqu10r7In1T9naqMZeVFseKPfplcmyUAjmijaHsZmtKfrWUpsy5DEUp52tlegOnSSV0cR78JkzZgSVKuQxFK2/Rh1xY9gsulQgW4Rjliq+OYW03emXacp0K1CEksZXVijVptcQSSYcGzEiSJMMyhiKapTeoUXWgxn2oFsSrCERKXDhlyftnzU9rpfTN5q1F0QIwcg3TU8Y4MOjvLQG7bTz3ZjXRmRbY50pCGLolkknz/QwYTDX8aaOMIeBb1VgmAeixh2JghjiMg0YgDbVzjgVYEmE9RAvpPy4sXfpdEa6s3VdDBiAlsRL60SCNk267YgwbbYGKPBOqvljpD0HAKyOVnexGxSAEN52IH0wR0HmTyKoYwUoCOMC9avAKEijqH9zJRUePGLGPHWNKmryErXG/oNTgc1ydAE1mqEHNiTJJHuqdreZQdKsMmp9EnQ53QPpfAOynk3GYlMe/9aDGet5hi1uERgr7c/dNmrjnXQeywvlqG/jNEHlHG/DGvwE6lXz9aATvivlZ1iXWPlG6HVdVWDWGGCxQxyQQJELHHGg+Vna2MhvZUhVar0DGePVF4xL5hnf2lFqrR33cykpJ4wSSj7RGw9kSqEIWPMTWD74+dKRfEQCvaJOQmDgt4hBIKdOwmBgt4hBKKJylAkqgil9w9PwqGkWtWumG6Fdu2NkR2m2VjAOTDqKWxqI/ySLtg2wFB/EReBH89gdNWWalV6ONOQtfJakKLB8puhbBhDGkUidoT16AZSopahsbTR3IfqCQ1xF6phJXvJs56MkEVOXNcnQK9yX0u87jvPezn7y2oeyI/GQhjRLpE75kq/RWPeZp1xh7hl2WhWRQJ5yvVUSk1CrwhnaeYqnxUSphvZ0QjezEUCFa09wY/Q35SAd+1jGDNQAMCHoxPpTXEReEVrT/DydzVLuDtuYNa3V2Mh5i7VffuB+hflti0EkZ+EJqhf36z2Jnv/l7ZV0ZKpjR26E8KGFsk70cwD4M7NUPjWQEZNyyPW2kG05EktpyC0n5BT0CN4weLQ36NzqgHRmRNsw8K1DRwLzgSwoPGYsFR3w/97EgJ9ZTix7aJTEuMyqFXeiYNpIKkj4i4q7IYVF72x8VaU9sBMa8mYkHM6OyFGW24gHNnKVaU9MI9r5YrOToiRdHxcfTzAZZV1eLtO+/x42+qEXWJvexZ4nm9jV/iV2nvuGJZW1NSZMuMF61HZJBtgPvoIj346P50fMYxTXahOo3N1GCD1mm4PmGXGvmsXj31HcWLZ/icNWZ4SKM8Qs1T9Bs0rO+6qMk0yZBrqRyesSEMcylnpeyGxc6LAc6zHRvSIroO2o7h0XrIdVausfrYCXuJ2tQ9N00+jEUUg7Fwg9qn6zu57lYRh+Q/Hp2E5TDqH1n2qnlodWCg6K6WJ+jKtLFpxMeVbcOq3Gtd7WbK5rpmcHGkYvxZZg2pRNyy5VIPKc0et+1Q9tb5EaI8p6qw3l25ITeqqliaSs2JTU9jPbxZXi64jiXM47ey3RX7lmU7S6baD8qwK1wq08GWXL3Bh2hjz0xBgLdWtVUX03g4iotBdkmXnqm5gchJ6Y4l/RyvDMWwsegEpJh9okY3JMVqstUaauj8GvCpSiq/HDSGXuDcCN0h0I3Sf3veCUEg98XmG++Xt4mTSug57QF4rYrClwpQm752VfqTHtvnYD0IusWzXkAWe/PY3NoSKrhy2S1cVtlIlerViclX3qXseOyfn9nXbs3ue6hnqGZYDoHvwn+1ZRN3ncynpQIMlTHXHpQrm1urIMkAhjFhR2MTNrO3D0S4w6teApBYvqp2/WNEUtEzlJQxyjU7l6GHMMYBuQ0OlqF66M+txl+qMMd2izkkQZv/BaKiUiSsX6pjARFWL6MZtDX95Joly89G8iIFu40jUIwg94AzEsxeievXKG5C7TKec907veRHi8mAYnr0QVUdcwLXCp67jLa79DRmFBZi+BdrzBJPKr0lm6SZu6bwn980E7RxSqzs+z9SBmA4lwM1JIaXS7QhCylsyMD18LDtN1P9UObLPBngg5BnzMrTnEw9DsTU4WisWgjThYO362jGibW8M++TDkODS2gsETSm7nDv2qn85h4kx2PObU7wQZ3RgCtNqjPTq9k3tlhK1OwQ7a7McXqzGnMiKqG3MJVHI6Zyi4qgBiAjuHfdJeuynpKm7tIIlxfxtoHx3WOSZy+/okfN36VpO1yEAYez3DCuA1047NSJDlyOZeb9fwq2rN8ieBbcgypss/9LlyYKgDu1/57CbwxfBmYagrBpXw9tsQVely8I6ByOtweYGvl8/RuiMLhMnJb+GdLBk2jWkegR+GBsrp0+5KEn6en4u6grUs/sb1G1/EXlxGyLao/ISC2vUTBpkqVF4GpUp8L4LJNI1zNDvUXxbsWaCX+WtFTfAvTFE3Xe9BUagnwooECkqbS9QpZDKNaa0xXQGLe6YrUZMYWjdHDQbAMHinaD4Y8Mh5SUNBGWBIATI/9kityLh04r1rmbcEOvlDgQMntDxmg20QCAAZlnaQHBfoBq04TscWF7SQFCNDovcgLp4MDaAcUEUGRugr5L1usEziRtWVd5QgEFC7oeonp7sB7AiTwDAXWgEAQgFwctLGwiO9jzDgeUlDQUV+v8NGyEB1spLGgjqtwQkAsyUiRkIJwJusBVQH/dyhgKKUdQTPCgUkHFlaQPBLZC4G0HYSsIG2w3vKYtqXyviBsJDHtrDUVEpQ8GgOwEF5OBejtRFE/ZosvcsIS+h92J/YQDVG0pZSm84jS7lrTD4fMsb1JPWuLf+LHn/nfNCde0NpCKmv781rKkDCkaWvD8AUjf7I8jST+2fAzb9L/PBjhBPNtgNWq2+/Pr18n7ovJxI0e+XS/5MIdy1PQ2NSNGKwob26lgYf3fQgkrEOGNPTxQqKmy65WKB20fMs8bFVaAgmJtB0P0QNRzqP9nouImG98WM2A+1TJhWr9A1bE+cxr20BpV4JxlFWXzfJ9QXS21RYoNqY/iVV+4KWLETaSEIfLQvHhrhi2ZUr68qa468YyggGnwXFVt/XnoLil1ox/JQZNIbUKyMCLw7lQJhL7pJv71Bp5al6M9EN+g3TTnKU7lNmu1gWxpoCVOeiW7Vj1dwJILI5DchSeOt4YvW5WApa2hCE4e6Fa42coDkhDdgAKa1laKfCm7WHRmylBPJjdrllMZUbrNm3UzCJ0ndUlF8Ew4vDv1gcOhNNoi97AYE20drLUU9Fdyk2zVMedWvIL1pJDb4wg6merdyJUd5uRnI6Y1SuU2aH83orRzdVHKT9tS1TA6AnPAGDNHWOHn7TgqCvehm/W+PT2TpT0U36H9+e/RRinYquEU3ul3XkDQaLslv7AXMoQjSuFnkjR4lAdqPoh9SeLHtvZjhS0AOjaZam3Hpw8cE/aDpHGMG+NHwUUNfeO2jijD0Bw+1+6Cjehuw+bao26G6IEu1NvYIE8AKKudUKqiEzFh6QeOZywSPQlYWeuHjWXUIHoWsOfTCx7MeQTtrHGF5CpRl/e29lqirv7vAzKtuQYitrpvRFO1fRX8D1vOfr+7OUUr/7ux6CcXgH/3WQ/M5SXEv7F+ePx6/15r0tMC7QcPovnjwqZPUaAVhLUrvUh7wez98EaefJbed/+GN4Ti+KdQMBZlNI+QYlsMkSKP/6feL42f4n9RinV5AZO9w0fl8f3H65s2Hs4wAPrBdi6pp8TcI+oRnrdtZ2DYqu6OpbsiFzv0yDzwbbuCAqFKx9qDYirog62GTPrg47XW+NbzyGXIJqHJqGlDdx/EC763Tz2XlIltRF2Ry7MVSw5WLsGIanhXJL/ZFTZ2wyS5iOT08uC49dOB+hJaioKgLMskGy6nhQbWALTFsWeTbq6CoCzLJ9sqp6YDqAqyNxOk5yOsBr6CvB85xjJjT1oDxDIpHcXphur/2u6aEA1pVCTeiGzgjkJaxdaq6oRvDZlRRA7LPZKO8B5rygHovqV2dkBF8XlbL5OHa32zKQbd7anWIKK0ktgHAEjzHt57zQr8WQp7CYApvALPAJeYcX9rd1xzV2W1RJq96gdPrstQGCIOzoayd1/SovL75QDr3vqaPAJruBcaL4xuWVpbIq7w39Qb1PZYTBNRGttSmeTyJrUWcxHoAEDV7x6G+SlgKsFMn/Tsj3gqYqYsTTjsh8RLLFUucBhzWRaCwuvU9sUqyA8WihP7+++96WiKAhdZuDmksNlEa8rXDc8jNAmQ3VDiZoirbH0FNx0VoHINHBg7WNvMImoTbttSYS62iE5SI9h5AKijWRaI03uQqsvTINx/BNDBIjGb6BbGTayaaFdrosoQ0oA/5lcYjvyA/rkao34MRm3ggqjTGyUqeB+KdH6IzrXg1XMniF/ouzUqV4KFoZ5q5tYNJUK18I7ToByqZheYalIi9vg1Hp49UgklyT82WIaucaURLJQDu7BDAWUGEHJk8Xz1YtumWZ7wTI1rbobszQqAnwSY0FOkl9/ZSLQMjR/cUGgBluIztSrc9KG1toPD7isArtBd44cJB0ifBhwPTmL6DX46HgH0B79i603t5Rzb5Ph46h+qWWx77SqjepjVMUuE6p76iaq6i6SuuHH2+v5w0Tm5HAZyBPIVJLYYkES2WGbZxaE7nL0QZls0dxlu9zs4PZbq/lqIkCUckusgC5D0UVvn1xa+L5SW09e23L1df9e+LS31xe/7Xy+WCV8rl35f61f3/hRK+f1viNfonw0nQm/dveWV8uT5b/KzfnX2F2q/+32VByunRx3e8cm4+X14srxeUzZer66Ksh4f/9Vvix/8nXec5RBO0w3Td7NCke2LpR7xKb++WVzcQtb68+vbr+f2vd0v9bHHDm/ru/vZvV4ur22/6+c9n375dXuuX384+X19e8ApYXP3yd726nl3//f3ZTdXKR89HR0en8H9H3695Je353t1DCyyv/nbJXWog6q8Q9M3x8fHN1+XnM+5011cQPKabQ3/cOfnno2EC/q7fnH9Ps0onxffz2eLyQr/8++X59yXMTxHyz29vbmDJIPJvbi8uxQjFleP+7OLqVv98e3Z/gaHrf0NtkBTxUPJJX9GpiG9nN0XypI7ShdpuNTaTen/5N4bQs6OTzvK+XS5Rbt3dfrv8BtvDb+fX3y/467CuL5Zny6tzmPD66luRKPYQMeED23Nsr9zrNldzlK/lam7yV/C6puJkbXZpJ5h15uru5rt+dnfF32Jcp0Jw/dURtJus4+pXukiLj/q8u9vF1d/1y/v7b7dD68Dtly/Xt2cXqET8cnv/V5Sz53/lbxa7tOSZztSmtx2Mmc+Sq2/Ly/svZ+eX3C3/mX5xeQkHD9foz3wr1aMd587+X66+XA2oZCS3v32HRfrir/ry5/tLmEvXt+dnsGAtb+/R4OPuFptiUSgDJx0g7tGdny3Prm+/wq7xcnGJBkZ8Mu6XSzwIwyOIfKXjBpFFYNIXl+eVjog0bPuPmA1duk35peCMsTHLA0vmZ54PB6I8H0axZf7pT41f8o3JOe66YSPg4uOWPop937kNUpujH1cW/Gr/dJ6Yc/TL3Bq2h03v4+dNn83NICnkkgmnQuD50D0dQ/m6pHwdPJ0eRuXlUjmqHd+IdWNlF3s8fx2v++iH/eMjWm5pUk6+Sf9amKEdxAXl/4bi7wIz1owk9jfA08iXaIFGX/jnc8fqAYxecd8MjX41XyeeiR7qEcB/RwWEcZiURwESMFhGbAjV3yFzPMPzdVOH9XEK5r5rx/o6hNVfD3y8tjsBCGgA8GyCYKrsh/rDOLZHznjq8HRjBLgVHp+3qaP4T5YRWsUG+ePHEXQ/P9do/9OfjssjUQn6d0bo2d4mmhuOM4HpM/XgOQ6NKQEEwDI8NOkqdIuGE40JAu0N4rAQ0RQw0Beu/Ts+nFDsnO3f+dS7xiNAvSYk4s7RmCw2wg2Iy/prPqsMiQ5d+OSnbgOjgRDibeKuSiDSZ/KVl0dlhy588lM6Nju0jstronJAMMdnEAp6fgif/9RhrFZRsm/4WvHsP61roQ/hfOIn3ma6QX7qbc8HBsVqrWu0CSDullswJFb/fbj2/EPydBJANQMaDCv/bryyRBtbvdzjHf6Cn4xrJrloetml2hUf/pI+m8g20hB1sU9t73h4O7j8drWMTCxdbFI/YTxco3eH+3fjGmg0YF2s1TzFP1zT95NZbXSAnepf8xT9cI0+OMQfHGYfjFwtx4LInl7XfFa/7jVsuWsgKrzgU1nuOYQjXWBGP6G3c/zPMbDQNQid/NZdIyii+nsq7+GHwxsj+Onf/v32+/Lu+1K/uLr/D+3f/v3u/vY/L8+XaMPyP+Y4sfCCZ0cm44YMLPrajuJMfGEouvESOBgt77doezwdUG79KFYXJgQ1J95xc9sC8J9vTghYK56TowzWKrEdCy9Ez6FCMkilVFA4+jKXnMjK9+SzOaI7x/5+6IofQcRbU7ZUkdb0zBtNGr5fp5chHjrA28Tbn8r7Up0yiuzs4ExKV93Ldk8d9fygvAix23w8fu8eHx+7m3jVc+xX0y50LrYJ/KEHIWzD1zqeGXe06S/O7PBwY9b0pHzJ4RQKDZEPw90zlLNxkR+o2Ko+krWkV3XazvNUc/wtreCOtXaMTTRB2RCduf0ayA52S7+mlvtXsVttLz28Vgxtx8vnlAT169KJya/unfp1ob36q+6bK2UdBQhwV0LKxDP8kYk73Nnx9rAakUSRfqCrONMOzcQxQgsEwLOAZ77028lSh5EHGwWrMjnj34ca0tsIoLHvuTpkzY9aOiDFv3748S/ProM+BSEK1QI/Pp4TB2KAAurY3gY++r78cvjh4eAvRAAd0GaORIk5d30rgTUKB+aZn+NjI3fkszto488YeBYFZo4drmB6KCkAYfyyMOHfP5GrpvFQOW/6AArAzBcxCP4M4Rd+j0RpCBlNHiyLhMlbgDjGO6tqoErM1Fx9s7x8dWa6gsNqiothleZmaOrpaQczJBpRWYHWyaoBfJRFn2E3W/lrEYtl62B2sLi6ubu+Or9a/qovlt+RJ/jd/e3d5f3y6nJx8Ongnw8HuWhHnx7ggwc4qzOeACyvvvn4NyO00VGgCD3+hP5AH6D/YAsQ2PAr6/HaN8mad/riE/3HBpiPPjoSp5/OT2E2pY9n9B/oGM5tUE1XmVSmz/8gf0ABB2nAxVcD+Q+YFUQ7cqeJoOX/sTc9sKAklLGzrIDh00aIHCkdues8dRSwDcW9gh/7ob2xPcNJv/YSx4FP07oBHxzPsIAYDrfhr8Pjd0cfj05O359++GPWSTs586un1VfH7XTUE8PJ0ceTd6cnb951xHC/vNQvyCJEGvirh/K3MH/ev3/35n13A+BIDmllTUJcenqB+Hh89O70w9HbNwMgxKHv9LPAyfHRm+O3H09Pjjuq/xICgE5+7uMVdlcOs/34+OjtMXfxo0vhkDu5NHxreFa6R9FZ/fHR+5OTtx/h/7qqZ6zE96t8x6enx+8//PFfB3/8f7Etadk==END_SIMPLICITY_STUDIO_METADATA
