/*******************************************************************************
* @file  eap.pem.h
* @brief
*******************************************************************************
* # License
* <b>Copyright 2023 Silicon Laboratories Inc. www.silabs.com</b>
*******************************************************************************
*
* The licensor of this software is Silicon Laboratories Inc. Your use of this
* software is governed by the terms of Silicon Labs Master Software License
* Agreement (MSLA) available at
* www.silabs.com/about-us/legal/master-software-license-agreement. This
* software is distributed to you in Source Code format and is governed by the
* sections of the MSLA applicable to Source Code.
*
******************************************************************************/

#pragma once

const unsigned char eap_private[] = "-----BEGIN PRIVATE KEY-----\n"
                                    "MIIJQgIBADANBgkqhkiG9w0BAQEFAASCCSwwggkoAgEAAoICAQC0ZquSz+CkuqWh\n"
                                    "7FSqIIX1ssscp3FcE6VUnBUdPC2SQZfoqarpGiArLPyvL36346sXQHPeXAE+/z72\n"
                                    "hkdVyyVtVrv2QSFmRlBz+hloYkS+Sqqbn4EIiV70gqxExQIseA7mIzUNYOOnbIkf\n"
                                    "ItR35uyvsL+9Vcd49ZR9oA4nfBE8AdSeJ/rqRgt0mwfbIxqqkGsLOIzYGmblbT9h\n"
                                    "NdceSS81h2Jt1NJI9kqOzjtpKVDWKMmOcWTCpBYrBQEk0feeGv7JjUalwvXY3Lnn\n"
                                    "Qx/oIjpIro6e9N02UrypazVEWZdQXIr1xOFlh4AtfDNOcfVIPhja2TCsdus0ZX4U\n"
                                    "x4Vj3QFwgOcL6tDq41aZ0vi2ZhLYn4lEYeJvu3ITbTUdZcgKqeXTxB/IAmcHmnwi\n"
                                    "UxjNr8iCm0lMfS8s421FIXDm3bv5VpudiIMPqq93vtdVh7zvt5DUwigT0hrtnCU1\n"
                                    "FlOGEbjtovGAulzU51eZQ9ETUivFkXc/3nIVrUrhsAeP9gDth2IwV6jUxG9cn/AB\n"
                                    "K3o0n3H9cqpYwB9daCucltEg3NtHvckSE9rjal4/2Ec+JINOR9wXTeutfUntB5Ws\n"
                                    "IAucY2pbs8QjsmwNsHyp9RsayrStnmmSoeveaCypZg5S8REx+dm8LXCrGmEyBGzl\n"
                                    "IZ2EK7ZhjaH2QpqvGnn2mCXslb2TgwIDAQABAoICAARC9qOhtdipBhekpGgJG6ZZ\n"
                                    "t72bYQH//s8DCZFRZhwx4ND2DRuzlSCf+poi1kH+0VWxHUDv+HbmAwqXfSDpix6h\n"
                                    "nBAYVXMmjxOmS/+ww+yg3pXi4eKd6CMri76WJCkrxDerNj9001FAWZ7lgj0Q30op\n"
                                    "M+ZY8TzfbvIRcV7Safp6apeP3I1jOTW4dyo15+qGky4b2GE/LRYXYMC+9lrN93Jd\n"
                                    "b+BQqjpfWGng36YU0Ubghh5kzwYKvUan4saID+rpZVfFNsQyA6prUG2botR81oFN\n"
                                    "X6t2n7EpqYZGX5GX8jX2RwbA72LSyB7gSQ/91ixY4dpto143nZ0fwVI5V7fWX93K\n"
                                    "c2COMHO3ntf02mcEMzHs2mVRbSdotAZdCAWOn3FgHsx9rsuggvsVabdN8RlKnOkM\n"
                                    "EZ7iy4PLw0fkGnsGShLsIuPUSMbaxJWkGjJRe9OV9JGiq7VZ9ouQt7IDRYbwpDie\n"
                                    "ad2HGnwrXAtiSH24bw46AgrAu2Mf2Jxd1jhgef58QGKHO7fNUywWXH2sf3naUwPc\n"
                                    "cUcym1UadkEwYOCWb8KfHY53k0Qr4sdmnW/LpZDgaVkPtOWWjA/M8jT15p5r4SMW\n"
                                    "mZyybYJ5OKmhigCxk3Ey28jjxm/qxxHlMSPpogZkGjstNwNhjSeRzq4PfvnMPbm9\n"
                                    "wIHfNCs+c19EZ8FZMPIdAoIBAQDwfKKF4Z2wQQPFr18gNlrg5Pu8R3lyLUtBTqb5\n"
                                    "keJaT0DSkpMa7eSE9IdIExa3wRgYHIdzcOr2HnM9FEagf4xUHK58NKE0Q5TbrMbO\n"
                                    "GmqGxCqQ3GaBWfmi8JVhsty2w/ClEtw4z1kRrEKWG8l38zkT6QWsaZ7jHrqB0vFD\n"
                                    "WXZ2qi5z1ymJ8n+9L7IGo+cAhhBXOChkB3HuoBN2X0G8ckYsxX+sGviUfeBiULHB\n"
                                    "sxIPTSkAEhLIo1keQikNnvXU7vM6zBILXecgv6aSFvZlLofcunZqOWoTB/f7gjyU\n"
                                    "mY0HemJ9LBmNja6otY+g64oHu3daqNjKnvhwiEH0ilGwT9avAoIBAQDACcmCwL3S\n"
                                    "ufAqmwVujyqI4A8+CprsLwbG/xYNBWev71MebRqPyeXrbKTiHMxuJKFU5v8erWBH\n"
                                    "eEV+4al0XcPs1mnL9wuERDApKqdANh4LQ/Rs/Npt9NC1gQIZL36xYmlVUYw7OAEV\n"
                                    "NrG1XOCIUtdxFPM2SBhVFqYn2j6e3DhhyuwLE/+p4y2aF2s6lZc1xsXemWkRkU/o\n"
                                    "cLkO5/EnWk6rvqjYLmroIQj/J0nQ6K038USASnBwTlR33NQpZVlj66nG38R6u6dk\n"
                                    "MwweCk34iAf/a4VY2inU1BureLIcGUbWbzvLoW2aE5Gj75PCD3AWOV4XJu0RH+FV\n"
                                    "bXd+bScnvkVtAoIBADkW/WYXB14+MO0PEuAMx0o4UeKCfTwzsHfSeiUpErkps1PJ\n"
                                    "5A4yh1tgyXS8w1ngBx5CN42aMs02sVjApXuYi/Gz1WA7BkHoAUCdJZzr/Hn9u7Uj\n"
                                    "/VmbyH1765qD4Y2pukkVzx3Va2mcoToNYqiNHvGxEd26PTPhqZkEQK4iYNMO13Q8\n"
                                    "kenjnZuF5RdadY5URTDPbhdBBTUG31fsiSh5YFtkj0iGJpjpwQjV6zz2i8UCJkeU\n"
                                    "As2Kqa9bOW+4Wtev2iINLANyyVmm5Z4swVWH1Ez8HvxcoOffrmkQo90LDsXFsffR\n"
                                    "LkfCaMI4R96FzADF6jGlf8GqN4RPdIjfBUF70pUCggEAeofEI8GHXOV28Dhphtmi\n"
                                    "ciNElnl90CVRVbd9AmHofsFdb5R91jEkmsp/iiaF6eFFbz7UmWZWgEOlVAf4b19E\n"
                                    "m+FTL+k5V/OKJzon7TiaguWhF8leNbp3UNg31ooPdG8udlnJ+B8L0dVMHkRcn578\n"
                                    "CBMt+/yUSfZhnhwKyKIK95racVcZUfS6LA+1Q3QfPxjNN/L6r1LggZcq/O/RVyKv\n"
                                    "/7VvVkCHxgUOEH+pAbr0izVOV+0nQQE5tCEa3i7kknTTpykv3H/Plodbu+8nQOTK\n"
                                    "9ZZNRxwshLexz/765iLaqAfhR1SA8kZ6Lve2d6QSCJwiBPO5X6vPwwpNrEVJLnqh\n"
                                    "IQKCAQEAp0layer8c8W8o8MSCWj+QhdGp3O4GtKw6M/1BFUlZaZ7gAMOHZ9q51vs\n"
                                    "9R/9QIIwAP8JqBCQ1DODFylfKilUIgVY0htMmi1U+40AOJPX6rSvg9+awJ49BlSw\n"
                                    "MtNqYrnLuJFGmIsZuFp+2lbBKt9+b77W1UT7qI6R7cxazKvh9C+90xoWbBverDc+\n"
                                    "1nAQ8w4GCubu5MjxccCijLQtkLX/HO0owahyJikCuq0cJZZz0xcIV6n2uKpFPcn+\n"
                                    "ooAzI/9diMd8484prHLP+kh/xEQfwgP3iKRz06k4rAolpnZyv28k+2+fT1Br1rP2\n"
                                    "4jhjo2tBsgjiASVRjxBoOEGSUaV67g==\n"
                                    "-----END PRIVATE KEY-----\n";

const unsigned char eap_public[] = "-----BEGIN CERTIFICATE-----\n"
                                   "MIIFMzCCAxsCAxAAATANBgkqhkiG9w0BAQsFADB2MQ8wDQYDVQQKEwZzaWxhYnMx\n"
                                   "DDAKBgNVBAsTA3NxYTEfMB0GCSqGSIb3DQEJARYQYmhjaGltYXRAYWJjLmNvbTEM\n"
                                   "MAoGA1UEBxMDaHlkMQswCQYDVQQIEwJ0czELMAkGA1UEBhMCaW4xDDAKBgNVBAMT\n"
                                   "A2FhYTAeFw0yMzExMDcxNTAzMzBaFw0yNDExMDYxNTAzMzBaMEcxCzAJBgNVBAYT\n"
                                   "AmluMQswCQYDVQQIEwJ0czEPMA0GA1UEChMGc2lsYWJzMQwwCgYDVQQLEwNzcWEx\n"
                                   "DDAKBgNVBAMTA2FhYTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBALRm\n"
                                   "q5LP4KS6paHsVKoghfWyyxyncVwTpVScFR08LZJBl+ipqukaICss/K8vfrfjqxdA\n"
                                   "c95cAT7/PvaGR1XLJW1Wu/ZBIWZGUHP6GWhiRL5KqpufgQiJXvSCrETFAix4DuYj\n"
                                   "NQ1g46dsiR8i1Hfm7K+wv71Vx3j1lH2gDid8ETwB1J4n+upGC3SbB9sjGqqQaws4\n"
                                   "jNgaZuVtP2E11x5JLzWHYm3U0kj2So7OO2kpUNYoyY5xZMKkFisFASTR954a/smN\n"
                                   "RqXC9djcuedDH+giOkiujp703TZSvKlrNURZl1BcivXE4WWHgC18M05x9Ug+GNrZ\n"
                                   "MKx26zRlfhTHhWPdAXCA5wvq0OrjVpnS+LZmEtifiURh4m+7chNtNR1lyAqp5dPE\n"
                                   "H8gCZweafCJTGM2vyIKbSUx9LyzjbUUhcObdu/lWm52Igw+qr3e+11WHvO+3kNTC\n"
                                   "KBPSGu2cJTUWU4YRuO2i8YC6XNTnV5lD0RNSK8WRdz/echWtSuGwB4/2AO2HYjBX\n"
                                   "qNTEb1yf8AErejSfcf1yqljAH11oK5yW0SDc20e9yRIT2uNqXj/YRz4kg05H3BdN\n"
                                   "6619Se0HlawgC5xjaluzxCOybA2wfKn1GxrKtK2eaZKh695oLKlmDlLxETH52bwt\n"
                                   "cKsaYTIEbOUhnYQrtmGNofZCmq8aefaYJeyVvZODAgMBAAEwDQYJKoZIhvcNAQEL\n"
                                   "BQADggIBAA85hLqUbiy2OggbqWv+jjmwUq0SEM9oJxZnZ1w0zm2oDEcWzS5k/n49\n"
                                   "fpjuimwsOoD6z4yYKHOuFb7fGsu0mPdXIXxitmVHWs6uo/Awqc6wiCOVRqSiFXB/\n"
                                   "UyyjfgKEsYBERh+6QXUjwNVQTfzKOevxcQmlkTc7Co4aPUGNexrxsQJzZqp0Xv/o\n"
                                   "v0Xwzvez2/Y57Xwi6/e+3n/iyj+KYi4Ll0h8Mmx+MoGfCss64pA6ae9PlPd7TM1+\n"
                                   "9S1hMApc87UEtqNUyuwwiYC7JIzpz/qp9kZzmghZ2E5brfMvWoHSiPNWbfIyxfLo\n"
                                   "CD0zlhDTMVK8AW9bKWyuVThZ1BiVK82rg7z1OWjX6ew6j8bieLDu/BHQALUCuItC\n"
                                   "c669vQEx0u+sfKF0dyNmKoUvveYmLPflJB0fq+HRjpP9UAZcWj0/nUqQXcF2qLx5\n"
                                   "kdPJju1Jg/FsgVXIXvbZXdhHmcOxeVBkQpgxkB1mQuSyvi4wlxoNq82+4gi9B9nz\n"
                                   "hSxoeVBOZm+9fMeXtxKW0fzMUX4S2po/OZA5Tz46X/TnBNYk+p25B6FwLMabUyux\n"
                                   "ANVqU0vJl90IMNgHdDmVeDW5Nc2pcsXo4XIiGXiKUcmVR4HxkVJ5VlFhgUuJsEXb\n"
                                   "doOfExzPhHnkHh+6KRUOWHNi3UaxFqHd/tSG9b+9h2CjI5JdFU+4\n"
                                   "-----END CERTIFICATE-----\n";

const unsigned char eap_ca[] = "-----BEGIN CERTIFICATE-----\n"
                               "MIIGYTCCBEmgAwIBAgIUQZOnCDBBtLkmtp7Ho2hc4xZ43TMwDQYJKoZIhvcNAQEL\n"
                               "BQAwdjEPMA0GA1UEChMGc2lsYWJzMQwwCgYDVQQLEwNzcWExHzAdBgkqhkiG9w0B\n"
                               "CQEWEGJoY2hpbWF0QGFiYy5jb20xDDAKBgNVBAcTA2h5ZDELMAkGA1UECBMCdHMx\n"
                               "CzAJBgNVBAYTAmluMQwwCgYDVQQDEwNhYWEwHhcNMjMxMTA3MTUwMjI2WhcNMjQx\n"
                               "MTA2MTUwMjI2WjB2MQ8wDQYDVQQKEwZzaWxhYnMxDDAKBgNVBAsTA3NxYTEfMB0G\n"
                               "CSqGSIb3DQEJARYQYmhjaGltYXRAYWJjLmNvbTEMMAoGA1UEBxMDaHlkMQswCQYD\n"
                               "VQQIEwJ0czELMAkGA1UEBhMCaW4xDDAKBgNVBAMTA2FhYTCCAiIwDQYJKoZIhvcN\n"
                               "AQEBBQADggIPADCCAgoCggIBAM2F8xTDak8/fYXw+1Ot/EzPCpyU6yaLRBjecCWs\n"
                               "8Xs99yWeXSmQU0pehrqOAMy7Ae8jbBRXXFYzkCwz/Si/0DTzddEH04no3TiemPoK\n"
                               "uGNEj62vooC9yBOIp4jLVCCx4txWi4ez9q8vcuP+qXUNMT+3jFOssyV2dVwC3A2x\n"
                               "o0EwRpFl4pEBmY4Y8Au38Q1fBwsXakkdBp0fg9lE65ggkKA3MJM3TQF7WW0PLLpi\n"
                               "NC1Kc0DLq6npMhKdN1ou3BKO0hnsTjaNq9pvjqXmyDoMS4ZPU2EHaFlJ4UvQHlFo\n"
                               "1AYWoT7pmoxCgCIiKMZgSSSlHnV+l0wel6z+L90dyzbfPtB65z6gGxAxEmOHxo0f\n"
                               "mLTzlEPoX5EqlU5kOhJKfjJ/arf57icJT2FZeaAKcEVxHs7FScUv90Fyx5fcPrVQ\n"
                               "zMtjI+hvfpVkoIwIT7Bqt0s/8ayIChO/f0bK9YX9q/14CWeTv+GeJgAQk9jZcrTY\n"
                               "OY/jV7su5Gni0pX3JLwD5nxgHJnkr2aC/hhKT9N5xPWK7YI3qqKwnRMgH4z6WcE+\n"
                               "JrFTK/MQinW4+tQXTeblw4MFMWRKQe0W3VBouhm21DchT9pJDn7d/L2QfItlyGQ6\n"
                               "Ookg0DZ0Ubnn2N5klBTFDFCSShoot/eal2Fn6+ds0IVlUDjKgdW9c6Ioa55B8C7R\n"
                               "p2FrAgMBAAGjgeYwgeMwDAYDVR0TBAUwAwEB/zAdBgNVHQ4EFgQUTsi2X06+jgAv\n"
                               "o88d0UbNkavEMY8wgbMGA1UdIwSBqzCBqIAUTsi2X06+jgAvo88d0UbNkavEMY+h\n"
                               "eqR4MHYxDzANBgNVBAoTBnNpbGFiczEMMAoGA1UECxMDc3FhMR8wHQYJKoZIhvcN\n"
                               "AQkBFhBiaGNoaW1hdEBhYmMuY29tMQwwCgYDVQQHEwNoeWQxCzAJBgNVBAgTAnRz\n"
                               "MQswCQYDVQQGEwJpbjEMMAoGA1UEAxMDYWFhghRBk6cIMEG0uSa2nsejaFzjFnjd\n"
                               "MzANBgkqhkiG9w0BAQsFAAOCAgEAw+fT7O872lzdwYFBHPGqQFzIhvUHVV8+/4DI\n"
                               "IRp3lx2cs1plBwVa+COqCYQdGnOeimaZcfFgRs0CfLunF0PnrIHxqKLaBsmTFRV5\n"
                               "2uZ5R9pNkxSmoGxDC0RSBZinn8uvGku5ES2/5ezkMo19tlvaoKn++PFTimRuVbrB\n"
                               "h3yzI/yxXR2cebbE1hgl3GOncLZ8wAI75dMZYtOFKHF8N6Jn4wC2Qh7ia/Z4/T6d\n"
                               "7S/iVLQgRwlsgF6gFG3RGbEBkQbpz4Hj/mt0dj5KOxibSsub2vdm46UdkMds6lmR\n"
                               "y+JQUcG0NfUDH6+ZZUJ0TZGXxOOkwhPdphwDR+a+26UoIaB4e/6DPF1udXEyHKKC\n"
                               "Qyt76CtAXhj17iMvw0v38h2koBVohlzjW0cY3pyPfNgnS0TxEgcsSQ5LX7KNMIMX\n"
                               "StobOEWduKg8YUcK034TZCqXlDv8Az8kXMZQpsPa0BTtMoFL2INRkIKc5Xs6c16R\n"
                               "IPY+0yDfDMTKiDFG73juA0Q6O8jqLExT+hIn11m49R5DPkmEXdy+4+iMpyaiJpRn\n"
                               "umPIa6cU6rN4R8NcsXiINcXX1lnGaI2OAbhx/P5xhZKuJIUB+dgU9x+3TFAa/5yA\n"
                               "6/8UWNlKGLEqpBi3JRd4PqLB1+G+ua9dnezJqgmqfaODG6xBFzd80DvVrew0O5lK\n"
                               "VEEfDdk=\n"
                               "-----END CERTIFICATE-----\n";