/*******************************************************************************
* @file  wifiuser.pem.h
* @brief 
*******************************************************************************
* # License
* <b>Copyright 2023 Silicon Laboratories Inc. www.silabs.com</b>
*******************************************************************************
*
* The licensor of this software is Silicon Laboratories Inc. Your use of this
* software is governed by the terms of Silicon Labs Master Software License
* Agreement (MSLA) available at
* www.silabs.com/about-us/legal/master-software-license-agreement. This
* software is distributed to you in Source Code format and is governed by the
* sections of the MSLA applicable to Source Code.
*
******************************************************************************/

#pragma once

const unsigned char wifiuser[] = "-----BEGIN RSA PRIVATE KEY-----\n"
                                 "MIIEowIBAAKCAQEAzPbx2S7+xlC0jx5Ev5OH35KyXt8x70tAnSDEiHtNlmA4JspF\n"
                                 "pC7PmQKJNy6rXXNsF8iKKuLBnbOevorb/QQ0PghEGw/+tqAP4VHYaCdq/L6LlfXZ\n"
                                 "BT5H3QHThBcH6w2mPcby1+R9y5/o8TsDcvxwOJt/ALOv2E8mcKxNxnKRmt8dQ9Ui\n"
                                 "4X5wR3TyUR4glbVerN0QdXLbFhsQ5EDw44bM8DW5NoZaL9CzEtqPUGG0x0C/7IGD\n"
                                 "qnpp04ydrw3VCnC1NbS+1u/qJS/bmTSkBAlQ9Uvq/RhVFi2eI+L3utcSkjDB2+UO\n"
                                 "U1jHDAxV9GRCrpp6Tw8iw0T3r/dpds/84LvpMwIDAQABAoIBABqVXMDCa6DlDsYR\n"
                                 "MvF1/QVuTVworp1OsU6v1U2uUF3UlPPTAD1PJPW/cnSJxQgV1EsxY1o0ltARX+Fu\n"
                                 "uSGTzgLNp6eq52pgUC71IpA/rIyjWg9VF5Sqgz+S4RAcvJYr6wfQKeb+Z6JlVx0S\n"
                                 "flwHibaN1GcO5xuzCFVMw7mdWm0vjz8vyvxEVez4lSKRhzx/rbmvbFT1TxrMHCZ0\n"
                                 "ExCFKbsFMqk8CWh5bjPjoyopOVvVAF296idGXQ3nX5/lualZOjMVOpmuGRppDd+j\n"
                                 "rZMUCk1+7rNi+pQfOCc/gUcRCLr3t7gVPACZ36rA4WOc4t24HFebXVooT4fgvFEy\n"
                                 "NXFUw0ECgYEA+p+K95Sa6x/rkgg73KV4OxNW5txnyDT9z6rX6U6/9gkWw4gWFHv4\n"
                                 "9CEoUm+j7+DHV2GWNIVlBVCSpBeiPXQMacUztfWrSoG9mQvpdJ5vwXIjDXHly+RR\n"
                                 "+RbjMf1koSa0xF+M8hcOX8nzRMDKtygPACbBXUwIZvKboW+/69mKxqkCgYEA0Vyj\n"
                                 "fi6ry/OoopGwNzpcZPliUm0FppK2KeVvfUNU7U4I+8CMYf9prPRKiob6nwpsgxWD\n"
                                 "GvH9DDLZw2bUeZ5BfgccB5ZvTovjvBX7J/cUZiUI70208kWudcCCtUdQ9VXJQFpX\n"
                                 "vw50j1sjqhBala/lpca7QA8Zk/yY+XuaKrPChnsCgYBR2Cwvse3tft0VMW8rHTZo\n"
                                 "RGaKucuCjBue57He1QLHPCyc6iIbymiAgRuD4EVvHr66gHnm6PEWjTt2Lumim/U5\n"
                                 "zVaXw4SOrlPWWReCKANi7v0XdOyQax2B9MF5H8DvB47c2j9TB8h/65lwCG2q5oAP\n"
                                 "kphu+Vd9FxlP3QiV4tL5EQKBgQCFmyfe26vY8PraHD0nUYArFBcR4O8tOQ01OWzn\n"
                                 "tHNbKWSEPIGZ/GQU8qUrOC5yFjXfhXfwVyOUiFL95v6LSlojMihKE0+fAZjoq+Jm\n"
                                 "w7/p25KTHLTvs1Y9YQhI5WUd24weHElI7NGntpLQ8bTNN75HB8bxf3FkRlvdQmrE\n"
                                 "+4iVRwKBgEAr82q1Crr1yps3Xxc5pMuD70OdsLOtzgspxFe9fXzHpPAgZRqS3kIG\n"
                                 "iOL+yeBXDutByp9QorQn5afJo4BJjnf3cEUrMucb0oxEr+ZKxiYu/R6CYiTDp3Fx\n"
                                 "BjKG6fhBonoiURm0KIqLXiW/k2iNXYsUwuOwBHCdlyRpcWnu7ZtU\n"
                                 "-----END RSA PRIVATE KEY-----\n"
                                 "-----BEGIN CERTIFICATE-----\n"
                                 "MIIFFTCCA/2gAwIBAgIBBTANBgkqhkiG9w0BAQUFADAjMSEwHwYDVQQDExhXaUZp\n"
                                 "LUludGVybWVkaWF0ZS1DQS1zdGEwHhcNMDUwMTAxMDAwMDAwWhcNMjUwMTAxMDAw\n"
                                 "MDAwWjBVMRUwEwYKCZImiZPyLGQBGRYFbG9jYWwxGDAWBgoJkiaJk/IsZAEZFgh3\n"
                                 "aWZpbGFiczEOMAwGA1UEAxMFVXNlcnMxEjAQBgNVBAMTCXdpZmktdXNlcjCCASIw\n"
                                 "DQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMz28dku/sZQtI8eRL+Th9+Ssl7f\n"
                                 "Me9LQJ0gxIh7TZZgOCbKRaQuz5kCiTcuq11zbBfIiiriwZ2znr6K2/0END4IRBsP\n"
                                 "/ragD+FR2Ggnavy+i5X12QU+R90B04QXB+sNpj3G8tfkfcuf6PE7A3L8cDibfwCz\n"
                                 "r9hPJnCsTcZykZrfHUPVIuF+cEd08lEeIJW1XqzdEHVy2xYbEORA8OOGzPA1uTaG\n"
                                 "Wi/QsxLaj1BhtMdAv+yBg6p6adOMna8N1QpwtTW0vtbv6iUv25k0pAQJUPVL6v0Y\n"
                                 "VRYtniPi97rXEpIwwdvlDlNYxwwMVfRkQq6aek8PIsNE96/3aXbP/OC76TMCAwEA\n"
                                 "AaOCAiAwggIcMD8GA1UdIwQ4MDaAFLCM4rLBhvxWYXi/HwbV8xGSsTgAoRukGTAX\n"
                                 "MRUwEwYDVQQDEwxXaUZpLVJvb3QtQ0GCAQMwQgYJYIZIAYb4QgEEBDUWM2h0dHA6\n"
                                 "Ly9zZXJ2ZXIud2lmaWxhYnMubG9jYWwvY2EvY3JsL3dpZmlpbWNhc3RhLmNybDBE\n"
                                 "BgNVHR8EPTA7MDmgN6A1hjNodHRwOi8vc2VydmVyLndpZmlsYWJzLmxvY2FsL2Nh\n"
                                 "L2NybC93aWZpaW1jYXN0YS5jcmwwTgYIKwYBBQUHAQEEQjBAMD4GCCsGAQUFBzAC\n"
                                 "hjJodHRwOi8vc2VydmVyLndpZmlsYWJzLmxvY2FsL2NhL2NhL3dpZmlpbWNhc3Rh\n"
                                 "LmNydDAgBgNVHRIEGTAXghVzZXJ2ZXIud2lmaWxhYnMubG9jYWwwMwYDVR0RBCww\n"
                                 "KqAoBgorBgEEAYI3FAIDoBoMGHdpZmktdXNlckB3aWZpbGFicy5sb2NhbDALBgNV\n"
                                 "HQ8EBAMCBaAwHQYDVR0OBBYEFAvBhZsRvOlqwE4Is4e8Ka81blgjMB0GA1UdJQQW\n"
                                 "MBQGCCsGAQUFBwMCBggrBgEFBQcDBDBEBgkqhkiG9w0BCQ8ENzA1MA4GCCqGSIb3\n"
                                 "DQMCAgIAgDAOBggqhkiG9w0DBAICAIAwBwYFKw4DAgcwCgYIKoZIhvcNAwcwFwYJ\n"
                                 "KwYBBAGCNxQCBAoeCABVAHMAZQByMA0GCSqGSIb3DQEBBQUAA4IBAQAPGCPlaHYA\n"
                                 "efDmwaFHJuB7+VpqivrSkFI9mIZaQ0vnbAdzQ56MbKelkijoS7nphpq52pz0VDgT\n"
                                 "yKGvWs3LkmLvRcVXWObCjvzChMf4ufCQRaQEKWHEedjL0+jwGZpyOMqvcfj3ll7N\n"
                                 "TWQ1l2filgHwNl7WXcx7AzzeZ61EdYbuHCER/vBEvInEDCAnNlQDk8FXqRyqa4Df\n"
                                 "Q8rHP32r1lKPwgTcCEXVn+y9cBim+qbtW2Zw/LAx6T3bYsze9pHWEMw9fSxGCPgf\n"
                                 "VjUmqpJUXtygDwa4/OY48KpglvetwKGGg4zNbDC5ucG7KY/kD3XG/YHffu4lenab\n"
                                 "gELU9DvJIT1+\n"
                                 "-----END CERTIFICATE-----\n"
                                 "-----BEGIN CERTIFICATE-----\n"
                                 "MIIEVzCCAz+gAwIBAgIBAzANBgkqhkiG9w0BAQUFADAXMRUwEwYDVQQDEwxXaUZp\n"
                                 "LVJvb3QtQ0EwHhcNMDUwMTAxMDAwMDAwWhcNMjUwMTAxMDAwMDAwWjAjMSEwHwYD\n"
                                 "VQQDExhXaUZpLUludGVybWVkaWF0ZS1DQS1zdGEwggEiMA0GCSqGSIb3DQEBAQUA\n"
                                 "A4IBDwAwggEKAoIBAQCi/p4AsGV9dkTmCjPQ8vLA7vdAIUUAvMpPUQ2kqh7xN82c\n"
                                 "4/4xvtVkSDHsTTgZMWNc+wxGt0L+5XgI5evJx6ZSDWKiBtERTudJW8KnuS9D9uD7\n"
                                 "vk3pMRhVqHMMJdXtZk3D7WtxdO+0UZAyWoO5bkifDtQhyIlgULmsKAbjqjapFpJO\n"
                                 "0yoGrj2LGpIAmUk+lSlWn1tFk5Ct2j5BDwPlgSJTUkt/Qpi7Yh7p9l3kz2ldXBCf\n"
                                 "J3O47tr2zENW0yIpGn7lirdBz8iUADE0iSprJzWbFr7/VBLqGMKXOujhZ70CCTRM\n"
                                 "WLh53hrbE1xQYZGTZSZNHxFjGyhrRZq7BuFMIUk3AgMBAAGjggGgMIIBnDA/BgNV\n"
                                 "HSMEODA2gBTXHXTI1mqUjBDPBU/jlqbWz7Ji86EbpBkwFzEVMBMGA1UEAxMMV2lG\n"
                                 "aS1Sb290LUNBggEBMEEGCWCGSAGG+EIBBAQ0FjJodHRwOi8vc2VydmVyLndpZmls\n"
                                 "YWJzLmxvY2FsL2NhL2NybC93aWZpcm9vdGNhLmNybDBDBgNVHR8EPDA6MDigNqA0\n"
                                 "hjJodHRwOi8vc2VydmVyLndpZmlsYWJzLmxvY2FsL2NhL2NybC93aWZpcm9vdGNh\n"
                                 "LmNybDBNBggrBgEFBQcBAQRBMD8wPQYIKwYBBQUHMAKGMWh0dHA6Ly9zZXJ2ZXIu\n"
                                 "d2lmaWxhYnMubG9jYWwvY2EvY2Evd2lmaXJvb3RjYS5jcnQwIAYDVR0SBBkwF4IV\n"
                                 "c2VydmVyLndpZmlsYWJzLmxvY2FsMCAGA1UdEQQZMBeCFXNlcnZlci53aWZpbGFi\n"
                                 "cy5sb2NhbDAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBhjAdBgNVHQ4E\n"
                                 "FgQUsIzissGG/FZheL8fBtXzEZKxOAAwDQYJKoZIhvcNAQEFBQADggEBAJTw1owK\n"
                                 "3hDQfaWw3v2NHsuK7GBmdCIxsXitDgJTmcZ1EGVgWVdgduWHWIK0b7YRuW2dCX9V\n"
                                 "ICikaUURSp5tONRrJroF2kwS40CG3X9Lx/G39K7hxbk7S4pkkVca8Z5VVhbOP9HY\n"
                                 "KUrCgZruksg8Q4WqLVsvnGgA11b0/oVf8kWauScZeFh5PNtTa0WU8iIJ4PXD/7w9\n"
                                 "7UEzY+U7TOJR0h36/NGilu5XTwjcMesfnb2fTHXAzU95H3xbamFc51Tzv7Tn6eQB\n"
                                 "7k4aD5rAInKwN5xR5i9RZOzfgG/ZCFtYrN0y9KYvTRgdkl4uFq929k0v5xP6dqci\n"
                                 "V0zlAVNpC/k0urU=\n"
                                 "-----END CERTIFICATE-----\n"
                                 "-----BEGIN CERTIFICATE-----\n"
                                 "MIIECjCCAvKgAwIBAgIBATANBgkqhkiG9w0BAQUFADAXMRUwEwYDVQQDEwxXaUZp\n"
                                 "LVJvb3QtQ0EwHhcNMDUwMTAxMDAwMDAwWhcNMjUwMTAxMDAwMDAwWjAXMRUwEwYD\n"
                                 "VQQDEwxXaUZpLVJvb3QtQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB\n"
                                 "AQC555sEVFOZC7ZtUJfIQjaC4JOkUbd+nmrcIj052lzQoilRj+E2o0UHzJwkydNb\n"
                                 "vDSD6/3iedZwERae2oPA/nCYL9sOnQCpfJm6u8TbSuLuRqylNRvCvfDgancpNG5t\n"
                                 "X1HeZ/0n8VACv+kblS6ZC7NNfLxeSyldUuMU3tNt+rQHbLeD51qzUcZzppbrly+6\n"
                                 "BPDy6+7AuJUpmMqvi8knrSKTF5yIUXmQMcufmEe2XAPRD5i/6jKXZdNU1XELUn9V\n"
                                 "p4ixCwTVhHGnYihTuzO+Ef2YfToDmBdzt9beAldHOZ0MJheqM0JEWrANjxr3vxi/\n"
                                 "LTIqMgxMusnqqS4HvkzSxFn3AgMBAAGjggFfMIIBWzAPBgNVHRMBAf8EBTADAQH/\n"
                                 "MA4GA1UdDwEB/wQEAwIBhjAdBgNVHQ4EFgQU1x10yNZqlIwQzwVP45am1s+yYvMw\n"
                                 "QQYJYIZIAYb4QgEEBDQWMmh0dHA6Ly9zZXJ2ZXIud2lmaWxhYnMubG9jYWwvY2Ev\n"
                                 "Y3JsL3dpZmlyb290Y2EuY3JsMEMGA1UdHwQ8MDowOKA2oDSGMmh0dHA6Ly9zZXJ2\n"
                                 "ZXIud2lmaWxhYnMubG9jYWwvY2EvY3JsL3dpZmlyb290Y2EuY3JsME0GCCsGAQUF\n"
                                 "BwEBBEEwPzA9BggrBgEFBQcwAoYxaHR0cDovL3NlcnZlci53aWZpbGFicy5sb2Nh\n"
                                 "bC9jYS9jYS93aWZpcm9vdGNhLmNydDAgBgNVHRIEGTAXghVzZXJ2ZXIud2lmaWxh\n"
                                 "YnMubG9jYWwwIAYDVR0RBBkwF4IVc2VydmVyLndpZmlsYWJzLmxvY2FsMA0GCSqG\n"
                                 "SIb3DQEBBQUAA4IBAQCRdTUh+WTd+LFz32QZUPbJ3Qb++STu7ZsdT9p2B/zbhyAT\n"
                                 "tscIJZoIczLWttbkxwCI0mB9hU6D5p7RdWyodpYbkheZFYVvJ2yuSKEx0jTakOq4\n"
                                 "sDCFy6LCwI67RTE12ngU0Uo2TZe/MxrF5tqKnhXCh9GEMeu9uAT2l/o4plI0sx7N\n"
                                 "G/vCPkwvygpgl3TQkQygmOgXYyc7cqAHsC9vOgCv10zbN5y1Hme1gV7JucF74Ma1\n"
                                 "AozWbdQAC1d+95lQ1IO8j/TrrSD0InivVSzS3FXa7vLneyR2GbguHdo3GLuFd+/r\n"
                                 "LrQ+weBJZ7Sk+f+f3HaskrSW7Lo2RoDMpPmJPvl9\n"
                                 "-----END CERTIFICATE-----\n";
